### PR TITLE
ResponseCheckTx/ResponseDeliverTx BlockGasUsed

### PR DESCRIPTION
**Pull request by alexanderbez**
## Description

Introduce `block_gas_used` (int64) to the `ResponseCheckTx` and `ResponseDeliverTx` types.

ref: https://github.com/tendermint/spec/issues/196

### CODE REVIEW

**Review by melekes — APPROVED** [review]
👍

**Comment by melekes** [comment]
Docs https://github.com/tendermint/spec/blob/master/spec/abci/abci.md#checktx need to be updated ⚠️ .

**Comment by alexanderbez** [comment]
> Docs https://github.com/tendermint/spec/blob/master/spec/abci/abci.md#checktx need to be updated ⚠️ .

Updated. Thanks.

**Comment by alexanderbez** [comment]
Do we need any other consensus on this @melekes?

**Comment by alexanderbez** [comment]
Also, this introduces a new field, so why is this breaking?

**Comment by melekes** [comment]
> Also, this introduces a new field, so why is this breaking?

I thought `deterministicResponseDeliverTx` is going to produce a different hash (Block#LastResultsHash) - hence breakage, but now I'm not sure. Have you verified this?

**Comment by melekes** [comment]
> Do we need any other consensus on this @melekes?

Would be good to receive a few more acks before this is merged, but looks good imho.

**Comment by alexanderbez** [comment]
> LastResultsHash

Ahh I see, yes, if a call to `deterministicResponseDeliverTx` is used as input to `LastResultsHash`, then it is a breaking change 👍

**Pull request closed without merging**
