### PR TITLE
ci: use gh pages

### PR DESCRIPTION
**Pull request by marbar3778**
## Description

- removes last pieces of circle ci
- migrates to using github pages.

Pre-merge:

- [x] enable gh-pages on the repo
- [x] set it to look for index.html
- [x] test deployment
- [x] remove circle 

Post-merge

- [ ] get in touch with AiB about proxying `tendermint.github.io/tendermint/master` to `docs.tendermint.com`

Closes: #5478 

DEMO: 
- https://tendermint.github.io/tendermint/master/
- https://tendermint.github.io/tendermint/v0.33/
- https://tendermint.github.io/tendermint/v0.32/

### CODE REVIEW

**Comment by marbar3778** [comment]
> Post-merge
> 
>     *  get in touch with AiB about proxying tendermint.github.io/tendermint/master to docs.tendermint.com

@alessio I need some help with this stage. Do you know how the tendermint domain is managed?

**Review by erikgrinaker — APPROVED** [review]
Love seeing `.circleci/config.yml` go! 🎉

**Comment by alessio** [comment]
Thanks for the great work @marbar3778, greatly appreciated.

We can't work on this yet because we're experiencing a few issues with our DNS configuration. Rest assured that as soon as we get those issues sorted, we'll implement the required changes.

**Review by melekes — APPROVED** [review]
👍

**Comment by marbar3778** [comment]
> We can't work on this yet because we're experiencing a few issues with our DNS configuration. Rest assured that as soon as we get those issues sorted, we'll implement the required changes.

Should I keep the circleci deployment?

**Comment by marbar3778** [comment]
Got so close to removing circleci, but we have to keep it till DNS is resolved.

**Comment by alessio** [comment]
@helder-moreira am I right in thinking that we are now in the position to work on this?

**Comment by helder-moreira** [comment]
@alessio you are right. I am on it. Is this the only reason why we still have circle CI here?

**Comment by marbar3778** [comment]
I can remove it now. Was waiting on this migration to happen first

**Comment by helder-moreira** [comment]
@marbar3778 you can do it. I have already changed DNS. Should be ready in a few minutes. I will also remove old AWS Cloudfront deployment after this is ready.

**Pull request merged**
