### PR TITLE
p2p: bust up into sub dirs

### PR DESCRIPTION
**Pull request by ebuchman**
makes new subdirs in p2p: pex, types, tmconn

### CODE REVIEW

**Comment by melekes** [comment]
```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x860024]

goroutine 7 [running]:
testing.tRunner.func1(0xc4204000f0)
        /usr/local/go/src/testing/testing.go:711 +0x5d9
panic(0xa0bf60, 0xe781f0)
        /usr/local/go/src/runtime/panic.go:491 +0x2a2
github.com/tendermint/tendermint/vendor/github.com/tendermint/tmlibs/common.(*RepeatTimer).Stop(0x0)
        /go/src/github.com/tendermint/tendermint/vendor/github.com/tendermint/tmlibs/common/repeat_timer.go:172 +0x34
github.com/tendermint/tendermint/p2p/conn.(*MConnection).OnStop(0xc420142c00)
        /go/src/github.com/tendermint/tendermint/p2p/conn/connection.go:186 +0x85
github.com/tendermint/tendermint/vendor/github.com/tendermint/tmlibs/common.(*BaseService).Stop(0xc420142c00, 0xc420429401, 0xc42020c860)
        /go/src/github.com/tendermint/tendermint/vendor/github.com/tendermint/tmlibs/common/service.go:145 +0x2a8
github.com/tendermint/tendermint/p2p.(*peer).OnStop(0xc420410460)
        /go/src/github.com/tendermint/tendermint/p2p/peer.go:169 +0x53
github.com/tendermint/tendermint/vendor/github.com/tendermint/tmlibs/common.(*BaseService).Stop(0xc420410460, 0xc42018fd80, 0xc420441748)
        /go/src/github.com/tendermint/tendermint/vendor/github.com/tendermint/tmlibs/common/service.go:145 +0x2a8
github.com/tendermint/tendermint/p2p.(*peer).Stop(0xc420410460, 0xe43a60, 0xc420410380)
        <autogenerated>:1 +0x44
github.com/tendermint/tendermint/p2p.(*Switch).OnStop(0xc4200c0780)
        /go/src/github.com/tendermint/tendermint/p2p/switch.go:189 +0x184
github.com/tendermint/tendermint/vendor/github.com/tendermint/tmlibs/common.(*BaseService).Stop(0xc4200c0780, 0x0, 0x0)
        /go/src/github.com/tendermint/tendermint/vendor/github.com/tendermint/tmlibs/common/service.go:145 +0x2a8
github.com/tendermint/tendermint/p2p/pex.TestPEXReactorRunning(0xc4204000f0)
        /go/src/github.com/tendermint/tendermint/p2p/pex/pex_reactor_test.go:118 +0x8a1
testing.tRunner(0xc4204000f0, 0xbbc5b0)
        /usr/local/go/src/testing/testing.go:746 +0x16d
created by testing.(*T).Run
        /usr/local/go/src/testing/testing.go:789 +0x569
exit status 2
FAIL    github.com/tendermint/tendermint/p2p/pex        0.516s
```

**Comment by ebuchman** [comment]
Don't understand why it's only showing up now, but I think this is the reason: https://github.com/tendermint/tmlibs/issues/127

**Comment by ebuchman** [comment]
Maybe we can fix the pex_reactor_test to not call Stop() until it knows all asycnhronously attempted connections have finished starting or failed to start

**Comment by ebuchman** [comment]
Let's hope it was that easy :)

**Pull request merged**
