### PR TITLE
add bonder's signature to BondTx

### PR DESCRIPTION
**Pull request by ebuchman**

### CODE REVIEW

**Comment by ebuchman** [comment]
as for how to handle perms, I'd like to say the inputs should need Send, and the PubKey/Sig needs Bond, but I can also see wanting to forbid Send but allow Bonding (eg to emulate dual currency, one for bonding, one for whatever). So maybe for the inputs we allow Send or Bond, and for PubKey just Bond?

**Comment by jaekwon** [comment]
I don't think we'll be implementing a dual currency too soon.  If we do, it will probably be bonded validators + currency_type_1 + currency_type_2, rather than bond_currency + other_currency.  The reason being that bonded coins need to stay accountable by being slashable, and so transfers of bonded coins must be accompanied by more state to track.  (I don't think it makes sense to bond already-bonded coins, if that's relevant).

I think only Send should be required for the input, esp if we might want to disallow validators from being able to send coins.  When could this be useful....  maybe we want your node to become a validator, so we send you coins.  Then it's the node-admin's job to bond it (e.g. to schedule around maintenance schedules maybe?), but the node-admin can't possibly run with those coins.

This is good to merge

**Comment by ebuchman** [comment]
> I think only Send should be required for the input, esp if we might want to disallow validators from being able to send coins. 

this is the reason I think it should be Send or Bond, since we might not want to enable Send on the bonder, but he should still be able to provide inputs to his bond.

**Comment by jaekwon** [comment]
Oh, right.  Doh!

**Pull request merged**
