### PR TITLE
docs: add version dropdown and v0.34 docs

### PR DESCRIPTION
**Pull request by marbar3778**
## Description

- add version dropdown

@lovincyrus I am getting local errors when trying to build. Is there something I'm missing?

Closes: #XXX

### CODE REVIEW

**Comment by lovincyrus** [comment]
I'm still making sure the version switcher works properly on cosmos docs staging since I couldn't really test it locally. I'll release a new version to fix the issue.

Will revert to this PR once that's fixed 👌

Ref: https://github.com/cosmos/vuepress-theme-cosmos/issues/91#issuecomment-726360883

**Comment by lovincyrus** [comment]
> @lovincyrus I am getting local errors when trying to build. Is there something I'm missing?

@marbar3778 Build and run fine locally for me. Try rm -rf node_modules, package-lock.json and run npm run i; npm run serve.

image

image

**Comment by lovincyrus** [comment]
Updated the merge base to `docs-staging`. Let's see how it looks on https://docs.staging-tendermint.com before merging with `master` 👌

**Comment by marbar3778** [comment]
modified this back to master to see the changes.

**Comment by marbar3778** [comment]
@lovincyrus recreated docs-staging so it doesn't have all the changes. We can merge this now.

**Review by lovincyrus — APPROVED** [review]

**Comment by okwme** [comment]
found a broken link on docs.tendermint.com when clicking one of the version in the bottom right, is that fixed with this merge?
https://docs.tendermint.com/v0.32

**Comment by lovincyrus** [comment]
> found a broken link on docs.tendermint.com when clicking one of the version in the bottom right, is that fixed with this merge?
> https://docs.tendermint.com/v0.32

Someone must've removed/renamed the v0.32 branch. Check https://github.com/tendermint/tendermint/blob/master/docs/versions#L1

image

We just need to update the branch name. Which version of v0.32 should we use for the docs?

**Comment by marbar3778** [comment]
> found a broken link on docs.tendermint.com when clicking one of the version in the bottom right, is that fixed with this merge?
> [docs.tendermint.com/v0.32](https://docs.tendermint.com/v0.32)

Oh didnt realize we removed the old branch. Will fix this shortly

**Pull request merged**
