### PR TITLE
WIP: Enable loading transactions directly from BlockStore

### PR DESCRIPTION
**Pull request by NateWilliams2**
This PR allows fetching transactions, by hash, directly from the BlockStore. As discussed in https://github.com/tendermint/tendermint/issues/6325 and on discord, this is useful when using Tendermint as a library without the TxIndexer enabled. 

If `Config.BlockStore.IndexTransactions` is set:

Indexes transaction references with `txHash` -> `(blockHeight, txIndex)` on the BlockStore
Enables `BlockStore.LoadTxByHash(Hash)` to fetch a transaction directly, without having to search for the right block/tx

### CODE REVIEW

**Review by p4u — COMMENTED** [review]
I think we would need a test for this: https://github.com/tendermint/tendermint/blob/master/store/store_test.go

Also, how (from the Application) are we gonna get the transaction hash? Shouldn't we export `txReferenceKey`?

**Comment by cmwaters** [comment]
Just carrying this over from the discussion in the issue: 

My feeling is that the use case for searching for tx's either via a query string or directly via the hash should be sufficiently covered by the tx indexer. We are even in the process of adding greater customizability on that front (see #6307). If a user wants to use the blockstore as the source of retrieving txs then I would recommend they set up their own secondary index which they can use to store the height and the index and then perform the same query of retrieving the block and then the tx at the specified index.

Wdyt? @alexanderbez @tychoish @marbar3778

**Comment by alexanderbez** [comment]
The tx indexer already stores transactions by height _and_ hash.

**Comment by cmwaters** [comment]
Yup exactly so the argument of the above blurb was that I don't think this PR is necessary

**Comment by NateWilliams2** [comment]
Yep, our use case for this was accessing transactions with the txIndexer disabled, which is why this proposal adds redundancy to the indexer. We ended up going with our own secondary index as @cmwaters suggests, and accessing transactions from the BlockStore with this index. 

I'll close this PR, thanks for the discussion :)

**Pull request closed without merging**
