### PR TITLE
Expose max_peer_height

### PR DESCRIPTION
**Pull request by vlasveld**
Addresses #3365 

- Creates new interface for exposing data from the blockchain reactor's peer pool
- Adds max_peer_height to the RPC status output

This PR is a work in progress.

To implement:
* [x] Max peer height during fastSync
* [ ] Max peer height during consensus
* [ ] Event fastSync => consensus

PR todo:
* [x] Referenced an issue explaining the need for the change
* [ ] Updated all relevant documentation in docs
* [ ] Updated all code comments where relevant
* [ ] Wrote tests
* [ ] Updated CHANGELOG_PENDING.md

### CODE REVIEW

**Comment by melekes** [comment]
Closing due to inactivity. @vlasveld please drop a comment here if you are still planing to work on this.

**Comment by vlasveld** [comment]
I was waiting for feedback at the issue. 
I'll assume this path is better for passing data than 'polluting' the Switch or Reporter functionality. Also, I'll assume the event doesn't need additional data for now. Will pick it up, but I might not get to it this week.

**Comment by melekes** [comment]
> I was waiting for feedback at the issue.

Oh, sorry about closing it then. To my defense, I've found no indication of such request, although we've should given the feedback anyway.

I will try to review on Monday. Also, @brapse may want to take a look.

Thank you!

**Comment by marbar3778** [comment]
hey @vlasveld just checking in, would you like to continue with this PR? Sorry for the delay, we can provide feedback if you still have an interest in contributing?

**Comment by brapse** [comment]
This appears to be missing an implementation in `v2`.

**Pull request closed without merging**
