### PR TITLE
lint: cleanup pending lint errors 

### PR DESCRIPTION
**Pull request by tychoish**
for v0.34.x

### CODE REVIEW

**Comment by cmwaters** [comment]
I think some of these errors is because we only introduces stricter spelling conditions in 0.35 onwards (i.e. American English)

**Comment by tychoish** [comment]
> I think some of these errors is because we only introduces stricter spelling conditions in 0.35 onwards (i.e. American English)

The more confusing thing is that all of the remaining issues seem to be `typecheck` in CI which is turned off and don't fail locally?

**Comment by cmwaters** [comment]
I have a feeling that the linter doesn't update until after the PR is merged so it still has all the old linting settings

**Comment by tychoish** [comment]
looks like it worked though!

**Review by cmwaters — APPROVED** [review]
Nicceee

**Pull request merged**
