### PR TITLE
blockchain: rename to blocksync service

### PR DESCRIPTION
**Pull request by cmwaters**
Closes: #6751, #4594

I have tried to rename both the blockchain package and service as well as the term fast sync to the single term block sync. There are some exceptions. In all ADR's, the term of fast sync is left as is. In the config, in order to avoid a breaking change, `FastSyncConfig` remains the same. Do we want to change this and thus break the config file (we might have already broken it with the privVal changes)?

### CODE REVIEW

**Comment by alexanderbez** [comment]
I honestly feel like changing fast-sync nomenclature will be too much. It's already so engrained in so many things. Can we stick with just renaming the reactor/service for now?

**Comment by marbar3778** [comment]
Tend to agree with renaming of blockchain to blocksync. Ideally, we just rename what is "fast sync" to "block sync". This may only be docs

**Comment by cmwaters** [comment]
When I was making the change I also asked myself whether renaming fast sync would be too much. I do agree that it is engrained in the minds of us as developers and many members of the wider community and it will continue to be called fast sync long after this gets merged. I do however think that having consistent terminology throughout the repo slightly outweighs this and I've tried to be very thorough about it (with the exception of the `FastSyncConfig` which I'm still not too sure if we want to rename or not).

**Comment by marbar3778** [comment]
> When I was making the change I also asked myself whether renaming fast sync would be too much.

I am onboard with the rename, but not with renaming blockchain to blocksync. Blockchain is a generlized pkg for serving blocks, we just happen to have fast/block sync in it. 

If we pull out fast sync from blockchain this would be simpler. 

Also this PR doesnt solve #4594?

**Comment by cmwaters** [comment]
> Blockchain is a generlized pkg for serving blocks, we just happen to have fast/block sync in it.

But I don't think it is a generalized pkg for serving blocks. Its purely for "block sync". It's not linked with the RPC, which serves blocks by directly connecting to the blockstore (and the blockstore is its own package). You can also (if you really wanted to) use consensus to fetch blocks.

**Review by alexanderbez — APPROVED** [review]

**Review by tychoish — APPROVED** [review]

**Pull request merged**
