### PR TITLE
mempool: return error to RPC caller when mempool is full

### PR DESCRIPTION
**Pull request by cmwaters**
Closes: #8928

Note: For v0.36 and onwards where `mempool_error` is removed we need to have a different approach to returning the error to the user

### CODE REVIEW

**Review by tychoish — APPROVED** [review]

**Comment by creachadair** [comment]
FWIW this is already subsumed in the change I'm preparing. This is small enough there's no reason to hold off on it, but please try to avoid making other changes in this part of the code, since it's all going to get changed soon.

**Comment by cmwaters** [comment]
Thanks for the heads up @creachadair. I just was trying to fix this bug. As long as your new work also resolves the users original issue, I'm happy to close this PR.

**Comment by creachadair** [comment]
> Thanks for the heads up @creachadair. I just was trying to fix this bug. As long as your new work also resolves the users original issue, I'm happy to close this PR. 

Well, the code does populate this field anyway. The fact that the message changes in later versions may still support making other changes later. But for v0.35 and before this is in.

**Comment by cmwaters** [comment]
This is solved in https://github.com/tendermint/tendermint/pull/8944

**Pull request closed without merging**
