### PR TITLE
Deterministic builds with CGO

### PR DESCRIPTION
**Pull request by cwgoes**
Work-in-progress

Ref https://github.com/tendermint/tendermint/issues/1545

### CODE REVIEW

**Comment by Liamsi** [comment]
(copied over from https://github.com/tendermint/tendermint/issues/1545)

On macos running `make build_nix` fails with:
```
/nix/store/vvzyx5ymmjnc0vbx0axr1vzbnnlx4jmh-tendermint-unstable-2018-05-10-bin
rm -rf build && mkdir build && cp result-bin/bin/* build && unlink result-bin
sha256sum build/tendermint
make: sha256sum: No such file or directory
make: *** [build_nix] Error 1
```
The command is just named differently on macos.

If I run `shasum` (or openssl) I get another hash:
```
shasum -a 256 build/tendermint 
6c1d06ca0905669c0cd564bdceaca98bfbbf47a31b1c9ebf1819751a0c543c9b  build/tendermint

openssl sha256 build/tendermint                               
SHA256(build/tendermint)= 6c1d06ca0905669c0cd564bdceaca98bfbbf47a31b1c9ebf1819751a0c543c9b
```

**Comment by Liamsi** [comment]
Running `make build_nix_docker` yields
```
 openssl sha256 build/tendermint                               
SHA256(build/tendermint)= 3f23ec462526f4bb9c3a5ec67ee1492a329d0b16390b604b6687d157408f5179
```
though 🎉

**Comment by cwgoes** [comment]
^ No idea what these test failures are, seem unrelated to the build changes.

@greg-szabo As far as I can tell, this works (with `CGO_ENABLED=1`), I can reproduce build output across different Linux installations, with and without Docker - thoughts / anything else to test? Can we integrate this into signed binary release flow (for both tendermint & gaia) a la https://gist.github.com/devrandom/806265?

**Comment by cwgoes** [comment]
Added to CircleCI, click "details" and scroll down to the bottom of the logs to see the output binary hash. 
Would be cool if we could show the binary hash in Github directly, not sure how to do that.

**Comment by cwgoes** [comment]
Fixed up automatic dependency parsing with some upstream modifications, `deps.nix` will now be updated when you run `make build_nix` to the latest version of `Gopkg.toml`.

**Comment by cwgoes** [comment]
- [ ] Lock dependency versions and Docker image versions
- [ ] Avoid `ADD .` in Dockerfile if possible

**Comment by cwgoes** [comment]
Closing in favor of simpler approach in https://github.com/tendermint/tendermint/pull/1721.

Users who want to use Nix can still reference this PR for an example approach in the future.

**Pull request closed without merging**
