### PR TITLE
p2p: make NodeID and NetAddress public

### PR DESCRIPTION
**Pull request by tychoish**
This is a big PR, but I think it has to be. It's split up into two
commits whith the substantive changes in the first commit and more
rote changes in the second that just update references. 

This change moves a couple of types out of the `p2p` layer and into
the public types directory. I don't want this to be a referenda on
`types`, which I think is a problem we should address later, but
before 1.0.

### CODE REVIEW

**Comment by cmwaters** [comment]
And the main reason for moving NodeID to the types folder is because we need it exposed because it is a response in the RPC?

**Review by alexanderbez — DISMISSED** [review]
I know we don't want to have a lengthy discussion on this, but can we please just move the necessary types to `pkg/p2p` please? `pkg` being our external package used by external processes and clients. There is nothing stopping us from doing this now. We shouldn't be moving stuff into `types`.

ref: https://github.com/golang-standards/project-layout#pkg

**Comment by tychoish** [comment]
> And the main reason for moving NodeID to the types folder is because we need it exposed because it is a response in the RPC?

Yes, and also because some of these functions are useful for people attempting to construct config objects. This request grew out of my conversation with @ValarDragon and seemed quite reasonable to me. 

> `pkg` being our external package used by external processes and clients. There is nothing stopping us from doing this now. We shouldn't be moving stuff into types.

I don't really think this is the right form to have a conversation about this, but: 

- `pkg` doesn't exist now, and I don't think this is the right place to be creating new paradigms. 
- I think it creates a more fragmented experience to have public types spread throughout the legacy `types` location and new locations, and think that we should avoid having a release where public types end up both in `types` and in the `pkg` directory. 
- 
I think it makes sense to break `types` into `pkg` packages at some point, and if we have plans to do that before 0.35, that'd be cool, but I think we should handle these changes distinctly. If we're going to break apart types, we should do that, and then apply this change. If not, we should just merge this, and break apart types in 0.36.

**Comment by alexanderbez** [comment]
I do not think we should proceed with this PR by just moving these the `types` package -- I'm strongly opposed to this.

**Comment by tychoish** [comment]
Let me think about this a bit more and see if there's a better path forward that preserves the general release timeline without sacrificing the coherence of the API.

**Review by marbar3778 — COMMENTED** [review]
This was one of my fears with not thinking the internal work through thoroughly. Types is already a mess, we have had this discussion countless times, adding more things into and passing the work on to a later date is something I'm not a fan of. `pkg/p2p` is a step in the right direction and I would wish to avoid breaking the API twice and aim for once, not already plan for two breaking changes. 

Also CHANGELOG!!

**Comment by alexanderbez** [comment]
> We shouldn't do a release that has some things in pkg and some things in types because it significantly hurts discovery and usability, and leaves the repo in an "aspirational state"

Why? We can move things into `pkg` piecemeal until we hit 1.0, in which `types` should be completely removed and `pkg` is stabilized.

**Review by marbar3778 — APPROVED** [review]
approving to unblock upgrade to sdk. Still think we should move to pkg directory

**Pull request merged**
