### PR TITLE
.vscode: remove directory

### PR DESCRIPTION
**Pull request by tessr**
How do we feel about remove editor-specific config files, adding them to .gitignore (which has to happen in a separate PR, I think), and letting people manage their own editor settings? `.editorconfig` is meant to be an editor-neutral style config, so any common settings could go there. 

(I initially ran into this problem because I had installed a plugin which wanted to modify my .vscode settings file, but I don't know that everyone needs to have my plugin settings.)

### CODE REVIEW

**Review by marbar3778 — COMMENTED** [review]
could this be added to `.editorconfig`? I am fine with keeping these settings local but that means everyone working with proto in vscode will run into false error.

**Comment by tessr** [comment]
Do you happen to remember the documentation around making this settings.json change? I wonder if there's an editorconfig-compatible way to do it.

**Comment by erikgrinaker** [comment]
Don't think editorconfig would handle this, since it's an extension-specific setting. Was looking at options for having both committed and local settings for a repo, but that ended up being a rabbit hole. tl;dr it's not supported.

>(I initially ran into this problem because I had installed a plugin which wanted to modify my .vscode settings file, but I don't know that everyone needs to have my plugin settings.)

Why would the plugin want to modify the repo settings rather than the global settings?

**Comment by alexanderbez** [comment]
I am in favor of the proposal. These settings should be managed locally by the developer/contributor.

**Comment by melekes** [comment]
I am fine with removing the file and adding it to CONTRIBUTING.md

**Review by marbar3778 — APPROVED** [review]

**Review by melekes — APPROVED** [review]

**Pull request merged**
