### PR TITLE
Protocol-agnostic URLs in RPC endpoint

### PR DESCRIPTION
**Pull request by nickray**
Replaces https://github.com/tendermint/tendermint/pull/1245

### CODE REVIEW

**Comment by ebuchman** [comment]
Huh same issue. @nickray do you have some setting in your github or on Circle that could be preventing this from building ?

**Comment by nickray** [comment]
I don't think so, no. I don't have a Circle. This sucks.
Maybe you can just change the two lines directly?

**Comment by xla** [comment]
@nickray Hej Nick, sorry for the inconvenience. We followed-up with circle and see if escalating with them will help with the situation, if we don't resolve it swiftly with them we gonna re-create the PR from one of our accounts so the change goes in soon.

**Comment by xla** [comment]
@nickray Closing this in favour of #1276. Didn't manage to make you proper author, guess not using the right email.

**Pull request closed without merging**
