### PR TITLE
mempool: move errors to be public

### PR DESCRIPTION
**Pull request by marbar3778**
## Description

Move mempool errors to be public, this is used in handling abci error codes

### CODE REVIEW

**Comment by tychoish** [comment]
I'd move these to `types` until we decide about `pkg` in #6616, but this seems fine.

**Comment by marbar3778** [comment]
> I'd move these to `types` until we decide about `pkg` in #6616, but this seems fine.

sounds good. is it okay if i do a sub directory or should keep it top level

**Comment by tychoish** [comment]
top level.

**Review by alexanderbez — APPROVED** [review]
Perfect. Thank you!

**Pull request merged**
