### PR TITLE
Keep the original subscription "id" field when new RPCs come in

### PR DESCRIPTION
**Pull request by michaelfig**
Closes: #4492

## Description

Capture the subscription ID that is set when the subscription begins, so that the emitted events use that same ID.

______

For contributor use:

- [ ] Wrote tests
- [x] Updated CHANGELOG_PENDING.md
- [ ] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [x] Updated relevant documentation (`docs/`) and code comments
- [x] Re-reviewed `Files changed` in the Github PR explorer

### CODE REVIEW

**Comment by michaelfig** [comment]
@jackzampolin can you help shepherd this through?

**Comment by erikgrinaker** [comment]
Thanks! Can you add a regression test for this please?

**Comment by michaelfig** [comment]
@melekes, @erikgrinaker 
> I think this is a correct fix, but better to write a test for it.

I would love to, but am having a hard time.  The Go client doesn't use the subscription id at all (it matches based on the query instead of id).  It doesn't reflect the ID field to the caller of Subscribe, so I don't know how to test it without punching some serious holes in the abstractions.

Technically, the subscriber is not supposed to rely on the JSONRPC id, so even though this fix works for me, it might be better to fix the clients for the eventuality when the publisher doesn't send ids at all.

**Comment by erikgrinaker** [comment]
Yeah, it looks like we don't have a whole lot of existing tests and fixtures around this either. Let's drop it for now and aim to improve overall testing of that module later. Could you add a changelog entry and rebase/update with `master`?

**Comment by michaelfig** [comment]
> Could you add a changelog entry and rebase/update with `master`?

@erikgrinaker done!  Not sure if `circleci/proto-breakage` is a flake.

**Comment by erikgrinaker** [comment]
Thanks @michaelfig, much appreciated! `proto-breakage` is faulty, see #4506.

**Pull request merged**
