### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by shamb0t**
Fix dead links

### CODE REVIEW

**Comment by melekes** [comment]
@shamb0t thanks! you can use `[ci skip]` for doc changes (https://circleci.com/docs/skip-a-build/)

**Comment by shamb0t** [comment]
@melekes cool thanks for the tip!

**Comment by shamb0t** [comment]
@melekes Not sure how to get this to work, I tried to add [ci skip] to the commit msg but doesn't seem to have an effect.

**Comment by melekes** [comment]
hm.. maybe it is not how it works for PRs

**Comment by shamb0t** [comment]
Yea I think you're right "Currently neither [ci skip] nor [skip ci] supports fork PRs." :/

**Comment by melekes** [comment]
Adding `[ci skip] [circle skip]` works!

**Comment by ebuchman** [comment]
Thanks for this. We added redirects to avoid the push to master. Fixed on develop.

**Pull request closed without merging**
