### PR TITLE
blockchain (v2): comment out TestReactorTerminationScenarios

### PR DESCRIPTION
**Pull request by melekes**
Refs #4442 

Commented out the test to unblock development. See the issue for details.

### CODE REVIEW

**Comment by tessr** [comment]
tbh I'd rather delete this test than comment it out. or at least leave a comment explaining why its commented out and how its failing?

**Comment by melekes** [comment]
removed

**Comment by marbar3778** [comment]
This works locally but fails in ci? I haven't run into this failing test locally. Maybe we figure out if its a nondeterministic failure or its is failing because of something else

**Comment by marbar3778** [comment]
this now passes on master: https://circleci.com/gh/tendermint/tendermint/93510?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by melekes** [comment]
I believe this is a non-deterministic failure.

**Comment by ancazamfir** [comment]
> I believe this is a non-deterministic failure.

Yes indeed. Never saw this failure, neither locally nor in circleci until merge preparations. They are very likely caused by the sleeps (1ms) that seem now to be too short (ci machines more loaded?). The solutions to make the tests without sleeps was a bit too involved and we did not pursue. So we can remove the tests or try with higher values (2-3 msec). Any preference?

**Comment by marbar3778** [comment]
we do run into issues where the ci produces non-deterministic failures because they get overloaded. This isn't as present anymore but could be the issue.

**Comment by melekes** [comment]
> with higher values (2-3 msec)

should work, I guess

**Pull request closed without merging**
