### PR TITLE
config/logger: Add mono mode in the tm logger output format.

### LINKED ISSUE #1760: Debug output color scheme to dark - not visible in console
**Bug**
Maybe it's more of a feature request to somehow be able to have a sane color for debug output, maybe even automagically adjust it according to shell settings?

**Tendermint version**
0.20.0-27bd1dea

**Environment**:
- OSX
- oh-my-zshell /zsh
- loglevel debug for * in config.toml

**What happened**:
Debug logoutput is not visible in cmd line, probably due to color tags.
Marking the output sections reveals them. Changing my background color to something really light works too.
Seems as if it matches my background color of 0x002933

**What you expected to happen**:
Is there a way to have a more sane approach to text coloring? 

Changed background color of terminal
differentcolor

Debug visible after selecting
marked

Debug output not visibile
inv

### PR DESCRIPTION
**Pull request by JayT106**
Add mono mode in the tm logger output format. 

Closes #1760

### CODE REVIEW

**Comment by marbar3778** [comment]
oh whoops, seems that issue was properly updated nor triaged. We should get rid of colors entirely rather than add a new type.

**Comment by JayT106** [comment]
> oh whoops, seems that issue was properly updated nor triaged. We should get rid of colors entirely rather than add a new type.

Just don't want to break the original settings. If everyone agrees to get rid of colors entirely in `plain` mode. I can make changes.

**Review by alexanderbez — CHANGES_REQUESTED** [review]
I do not believe we should be adding to or changing the current logger. I've mentioned in a few places that we should move to zerolog which handles all of this for us.

**Comment by tychoish** [comment]
I like Marko's idea of just stripping out colors ever where. I don't think there's a good reason to maintain colors, and I wouldn't worry too much about breaking the interface.

Having said that, this is a relatively small change, and I don't think we need to block it on replacing the logger.

**Comment by JayT106** [comment]
@alexanderbez I guess I can close this PR because  #6534 ?

**Pull request closed without merging**
