### PR TITLE
types: height uint64

### PR DESCRIPTION
**Pull request by marbar3778**
## Description

- Migrate Height to uint64

ref #2684 

Spec PR https://github.com/tendermint/spec/pull/253

Please ignore the amount of changes. The chunk of changes from mbt updated JSON

### CODE REVIEW

**Comment by Shivani912** [comment]
Three issues observed so far:
1. considers a commitSig invalid when `block_id_flag = 1` and zero timestamp is present 
https://github.com/tendermint/tendermint/blob/d8810315b1e8233a4a8aae617850803df1f3be02/light/mbt/json/MC4_4_faulty_Test2NotEnoughTrustFailure.json#L140-L145


(Didn't look deeper into this and simply fixed it by removing that particular commit sig)

2. Next, there was hash mismatch error here
https://github.com/tendermint/tendermint/blob/d8810315b1e8233a4a8aae617850803df1f3be02/types/light.go#L152-L154
seemed like an encoding error here as it does not account for uint64 values
https://github.com/tendermint/tendermint/blob/d8810315b1e8233a4a8aae617850803df1f3be02/types/encoding_helper.go#L10-L47
so added additional case there like below to fix:
```
case uint64: 
 	i := gogotypes.UInt64Value{ 
 		Value: item, 
 	} 
 	bz, err := i.Marshal() 
 	if err != nil { 
 		return nil 
 	} 
 	return bz 
```

3. Now, it is failing at
https://github.com/tendermint/tendermint/blob/d8810315b1e8233a4a8aae617850803df1f3be02/light/verifier.go#L253-L259

**Comment by Shivani912** [comment]
Okay, MBT fails on master too with the latest MBT json files :/ Could be possible that we diverged somewhere??

**Comment by marbar3778** [comment]
> Okay, MBT fails on master too with the latest MBT json files :/ Could be possible that we diverged somewhere??

Not sure. I think it fails on master because the files assume uint64 as height and there we use int64? This is a theory, not sure if it's the case since uint64 and int64 are both displayed as strings in proto/amino flavored json. Could it be that the rust impl is encoding uint64 as a number instead of string?

**Comment by Shivani912** [comment]
> > Okay, MBT fails on master too with the latest MBT json files :/ Could be possible that we diverged somewhere??
> 
> Not sure. I think it fails on master because the files assume uint64 as height and there we use int64? This is a theory, not sure if it's the case since uint64 and int64 are both displayed as strings in proto/amino flavored json. Could it be that the rust impl is encoding uint64 as a number instead of string?

No, I don't think that's the case (uint64 is also encoded as string). Master is also failing with the error mentioned [in this comment](https://github.com/tendermint/tendermint/pull/6025#issuecomment-786634407) in point 3

**Comment by Shivani912** [comment]
It's [this issue](https://github.com/informalsystems/tendermint-rs/issues/687) causing the problem. As a temporary fix I'd suggest the same solution we used for tendermint-rs. Mind if I push a small commit to your branch? 

We're currently refactoring the way MBT works and generates test cases so this should be fixed soon :)

**Comment by Shivani912** [comment]
> 1. considers a commitSig invalid when `block_id_flag = 1` and zero timestamp is present
>    https://github.com/tendermint/tendermint/blob/d8810315b1e8233a4a8aae617850803df1f3be02/light/mbt/json/MC4_4_faulty_Test2NotEnoughTrustFailure.json#L140-L145

Having a zero timestamp was most likely a workaround as mentioned in [issue#4797](https://github.com/tendermint/tendermint/issues/4797) and seems like it was fixed later.

Copying the relevant part from above mentioned issue here: 
`
Additionally, at the same check (CommitSig validating a BlockIDFlagAbsent block), it is checked if the timestamp is zero. here I would have expected that field to be missing or set to null based on the ADR. But in Go, zero time means 0001-01-01T00:00:00Z which is a syntactically valid timestamp. I feel this should not be set to zero like that but to null.
I understand if this latter issue is not high priority enough. If it won't be changed, I'll work around it in Rust I just want to make sure I'm doing the right thing.
`

**Comment by Shivani912** [comment]
Hi @marbar3778, curious to know what's the plan with this PR? Just want to check if you're blocked on anything or need some help from us?

**Pull request closed without merging**
