### PR TITLE
Add license file

### PR DESCRIPTION
**Pull request by compleatang**
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA256

This pull request adds a license file to the repository in order to continue the open dialogue within the community of contributors to the Tendermint codebase.

It is Eris Industries interpretation of any rights associated with this code base that Ethan Buchman, as an employee of Eris Industries, was committing on our behalf in his capacity as Eris Industries Core Developer for Blockchains. His commits in the various https://github.com/tendermint codebases are thus the property of Eris Industries (copyright 2015 -- the year of that effort). These are released under, and governed by, the [GPL3 licence](http://www.gnu.org/licenses/gpl-3.0.en.html), since all of Eris' tooling (including derivative code we've contributed to this repo which relies upon previous work belonging to Eris Industries) is GPL3.

For the record, Eris Industries's commits to the https://github.com/tendermint/tendermint repo were made in accordance with and in reliance on the representations made in this repository's previous LICENSE.MD file (which can be viewed in the Changes tab of this Pull Request) - chiefly, that Tendermint would be released under GPL3/APGL or similar copyleft licenses. We agree strongly that open-source licensing is the way forward in blockchain development and it's our hope that the community will also come to a similar conclusion. From this commit moving forward, we are operating on the assumption that the existing codebase marked as of the time of this commit is available for our continued use under terms at least as favourable as GPL3.
-----BEGIN PGP SIGNATURE-----
Version: GnuPG v2

iQIcBAEBCAAGBQJV2KhVAAoJEAc7b81T8FTlyksP/2/kM0RGlbFFQanhveSktU9d
0t5Wo8/YMNKM/+f3fw4LLDbXdvIUheOao3LvBYzWzrR0ZPgikUw2o4kDNRkce8vE
F15pmzlpQITxoE7Z4GVKQ7O+rPDdclUezMP96K+H4tCSWUUf7JnNd+ASlQL8+5fx
OnksVfC77Oh6mx7CTNYeptB1TkWF7htyU9dxGFh4QbAs9dc4pTNy04dunugHIaYA
7AOe5TyuGJ8pytjBv2AQHpk/FMn5b0bdciJcSdPopjp8nfYGkRgGkGGmD1y3yt3G
bD0FJS1In281hxqUjXvx2rIHkslpql5iI58x3RjjCrKfgiwrfeaaDMgrbudraYtV
KBEp11cYSITU8ZdTQEzTf1GHG5D8yFDcocYLSPCZd1hTPaf80OyUb1Rtvd7fNU/3
fsi1u4MoxBVKV3P5LYo3INbgVm9301pEuT2gmIQk9yn3PRl3Bqbj7i/s/cGax0OG
I5PjyqiwS5CEeeaHSjFKXmyB+Y40F6SxUyViBz9y12xM73kv6cFE/AGOgw8J2mGE
Mww9BVD0PZi6xRY/ow7yUgI31nyYU0vXPG/QpO3w+nsS5zt9EvmUgT2Je7eAiUOx
xjO0/gaJYanjrKSX3Z8B1NsA2btSmc3L2yBkSAtYXCqXthuqygriEE2aNGqZOceC
JKxuWu7gy+jld7aP3Hq5
=7XR3
-----END PGP SIGNATURE-----

### CODE REVIEW

**Comment by jaekwon** [comment]
```
Some people have asked me about licensing -- in the minimum all source code will be available via a copyleft license such as GPLv3 or the AGPL. *MIT and other very liberal licenses are being considered*, but I'm a kopimist at heart, so until then, forget the copyright system. For my true peers, my publishing this code is good enough.
```

The license file never stated that only a copyleft license would be adopted; it stated that the codebase would be available at minimum with a copyleft license, implying that more permissive licenses were also considered.  Thus the clarification in the next sentence.  Eris never had an agreement with Tendermint that this codebase would become GPLv3, so, you can't suddenly state that they're GPLv3 -- that's incompatible with the MIT and other liberal licenses that are being considered.

How about we publish this as Apache2.0 and move on?

**Comment by prestonjbyrne** [comment]
GPLv3 certainly satisfies the stated minimum set out in the licence. As to matters of copyright I refer you to Casey's PR above.

**Comment by prestonjbyrne** [comment]
This document is not a licence. It is a promise that all source code in this repo will be made available on an open-source licence. Apache 2.0 is not listed; GPLv3 is. As to the matter of copyright I refer you to Casey's PR above.

**Comment by prestonjbyrne** [comment]
The current "license.md" document, whether a license or not, is almost certainly a promise that all source code in this repo will be made available on an open-source licence. In the "license.md" document Apache 2.0 is not listed; GPLv3 is, and has been since January. It is therefore entirely consistent with the terms of this document, whatever it might be, to submit GPLv3 code to this repository. As to the matter of copyright I refer you to Casey's PR above.

**Comment by jaekwon** [comment]
I reserved the right to consider liberal (permissive) open source licensing for the entire codebase, to which Eris contributed.  Are you challenging this?

**Comment by prestonjbyrne** [comment]
With respect, you do not own Eris Industries' code, over which we assert copyright and release per the terms of the GPLv3 licence and only per the terms of the GPLv3 licence unless and until we say otherwise. Please see Casey's comment above.

**Comment by prestonjbyrne** [comment]
Please leave this branch open as it serves to put people on notice as to the current status of this codebase.

**Pull request closed without merging**
