### PR TITLE
consensus: release the cs lock during ApplyBlock

### LINKED ISSUE #3767: blocks lag when consensens reactor handle message for a long time
**The problem**
WX20190701-195019

Every 5000 blocks, we have a special block that will take more than 20 seconds to commit. 
We observe that the sentry node or witness node can't receive 2/3 precommits until validator have finished `FinalizeCommit` the block.

**The reason** 
in the `gossipVotesRoutine` routine of consensus reactor:
```
for {
                ...
		rs := conR.conS.GetRoundState()
                 ...
}
```
however GetRoundState will fetch lock of `ConsensusState`.
```
func (cs *ConsensusState) GetRoundState() *cstypes.RoundState {
	cs.mtx.RLock()
	rs := cs.RoundState // copy
	cs.mtx.RUnlock()
	return &rs
}
```

while the lock have alreay fetched by `handleMsg` when validator receive the latest precommit:
```
func (cs *ConsensusState) handleMsg(mi msgInfo) {
	cs.mtx.Lock()
	defer cs.mtx.Unlock()
        ...
}
```
if the latest precommit make 2/3 precommits, `ConsensusState` will `enterCommit`.

Because `EndBlock ` and`CommitBlock` of our block will hold `mtx` of `ConsensusState` for about 20 second, it will cause the downstream node will not get the last precommit in time.

### PR DESCRIPTION
**Pull request by melekes**
Closes #3767

As Ethan mentioned here
https://github.com/tendermint/tendermint/issues/3767#issuecomment-510974810,
this is a hack. The long term solution is to redesign the consensus
package.

### CODE REVIEW

**Comment by melekes** [comment]
> I don't believe ApplyBlock() is thread-safe; are there conditions under which it can now be called concurrently?

good question! I don't think it's possible for others to enterCommit because it's guarded by https://github.com/tendermint/tendermint/blob/ceac02b891415cf8178d6a83cd50aca36c8c035f/consensus/state.go#L1359

**Comment by erikgrinaker** [comment]
> good question! I don't think it's possible for others to enterCommit because it's guarded by

Ok. I'm not very familiar with consensus, so I'll take your word for it. :) But I think that's probably the biggest risk here. Would it be possible to add a test case to verify that, or is it too hard to test?

**Comment by melekes** [comment]
> > good question! I don't think it's possible for others to enterCommit because it's guarded by
> 
> Ok. I'm not very familiar with consensus, so I'll take your word for it. :) But I think that's probably the biggest risk here. Would it be possible to add a test case to verify that, or is it too hard to test?

agree. I'll try to write a test case

**Comment by ebuchman** [comment]
Wrote some thoughts here: https://github.com/tendermint/tendermint/issues/3767#issuecomment-648552928

While I don't yet see a reason why this is unsafe right now, it's the kind of thing that could bite us in the future. 

Did something motivate picking up this issue right now? 

In the linked comment I suggest a possibly more robust approach by moving the mtx into the RoundState ... still requires thought and careful review, but probably a lot safer.

**Comment by melekes** [comment]
> While I don't yet see a reason why this is unsafe right now, it's the kind of thing that could bite us in the future.

I agree, but I am not expecting too many changes to the current consensus package. I remember there was a convo about rewriting it using the new `blockchain v2` design.

> Did something motivate picking up this issue right now?

Nothing in particular. I thought it would be easy to make the changes you initially suggested.

**Comment by melekes** [comment]
Okay, let's lean on the side of caution here.

**Pull request closed without merging**
