### PR TITLE
pubsub: unsubscribe locking handling

### PR DESCRIPTION
**Pull request by tychoish**
This (potentially) addresses an issue that I found when looking into
the code relevant to the #6808 report, where a read lock might not be
released in some situations.

### CODE REVIEW

**Review by marbar3778 — APPROVED** [review]
wow, nice find!!

**Review by creachadair — APPROVED** [review]
Good catch, and I much prefer this style of lock management. 

I wonder if it's practical to write a check that calls to mutex (R)Lock have a non-escaping path to a (putatively) corresponding (R)Unlock? We use a fair number of locks, and while such a check wouldn't always be right, it would have caught cases like this—and might encourage a safer style of lock usage.

**Comment by tychoish** [comment]
> I wonder if it's practical to write a check that calls to mutex (R)Lock have a non-escaping path to a (putatively) corresponding (R)Unlock? We use a fair number of locks, and while such a check wouldn't always be right, it would have caught cases like this—and might encourage a safer style of lock usage.

Maybe! I'm certainly not opposed. I'm sort of surprised that such a thing doesn't already exist.

**Comment by creachadair** [comment]
> Maybe! I'm certainly not opposed. I'm sort of surprised that such a thing doesn't already exist.

It might. I wasn't able to find one with some cursory searching, but I haven't done a thorough investigation. There is a tool to check for recursive mutex misuse, which is pretty closely-related, but it doesn't quite do this.

**Pull request merged**
