### PR TITLE
test: remove P2P tests

### LINKED ISSUE #2805: test: use `make localnet` instead of current p2p bash setup scripts
In `/test/p2p/` we use a janky set of bash scripts to set up local docker networks to do various testing.

It would be great to eliminate much of those scripts and use the `make localnet-start` functionality as much as possible instead.

These integration tests can probably be improved in various other ways as well. 

Replaces https://github.com/tendermint/tendermint/issues/1532

### LINKED ISSUE #4641: test: run p2p integration tests with all blockchain reactors
The p2p integration tests on CircleCI currently only use the v0 reactor, we should run tests for the v1 and v2 reactors as well. See e.g. #4640.

### PR DESCRIPTION
**Pull request by erikgrinaker**
Replaced by end-to-end tests. Closes #2805, closes #4641.

### CODE REVIEW

**Review by melekes — APPROVED** [review]
🔥 🔥 🔥

**Review by marbar3778 — APPROVED** [review]
LGTM, nice to see so many scripts being deleted

**Comment by erikgrinaker** [comment]
@tessr In order to merge this, we'll need some changes to the GitHub branch protection settings:

* `setup_dependencies`, `test_p2p`, and `test_persistence` on CircleCI should no longer be required

* `e2e-tests / test` should be required

**Comment by tessr** [comment]
I've marked `setup_dependencies`, `test_p2p`, and `test_persistence` as no longer required for `master`, and I'll do the same for any other branches that rely on those tests. I couldn't find an `e2e-tests / test`, but I did see a  job called `e2e-ci`--should that be required instead?

**Comment by erikgrinaker** [comment]
Hm, odd - it should be `e2e-tests / test`. See PR actions below and definition here: https://github.com/tendermint/tendermint/blob/master/.github/workflows/e2e.yml

**Comment by erikgrinaker** [comment]
Will merge this for now, we can revisit branch protection settings tomorrow.

**Pull request merged**
