### PR TITLE
RPC: don't cap page size in unsafe mode

### PR DESCRIPTION
**Pull request by gotjoshua**
actually belongs in a config file i guess, but this hard coded max creates weird behavior in downstream clis:
https://github.com/regen-network/regen-ledger/issues/272

### CODE REVIEW

**Comment by marbar3778** [comment]
Instead of changing the max value here, we should allow the maxPerPage to be overridden by what the user sets in the request.

**Comment by cmwaters** [comment]
I thought that the `maxPerPage` limit was to avoid clients requesting enormous amounts of data and thus slowing the node down. i.e. if we didn't have `maxPerPage`, a client could just make a query for all txs above height 0 and the node would have to load every tx (maybe there are other rate limiting mechanisms that I am not aware of).

> we should allow the maxPerPage to be overridden by what the user sets in the request.

If the user can override it then we don't really need a max right?

**Comment by marbar3778** [comment]
> I thought that the `maxPerPage` limit was to avoid clients requesting enormous amounts of data and thus slowing the node down. i.e. if we didn't have `maxPerPage`, a client could just make a query for all txs above height 0 and the node would have to load every tx (maybe there are other rate limiting mechanisms that I am not aware of).
> 
> > we should allow the maxPerPage to be overridden by what the user sets in the request.
> 
> If the user can override it then we don't really need a max right?

Agree here. Was trying to compromise, but clients should implement handling pagination

**Comment by gotjoshua** [comment]
> clients should implement handling pagination

agreed, but only when it is really needed... a hard coded limit of 100 seems way too low, 
with the default of 40, 1000 seems like a reasonable max... thus my proposal

**Comment by marbar3778** [comment]
> > clients should implement handling pagination
> 
> agreed, but only when it is really needed... a hard coded limit of 100 seems way too low,
> with the default of 40, 1000 seems like a reasonable max... thus my proposal

I would agree, if the RPC wasn't such a large DOS vector. There a known issues with mutex contention that slows down nodes when the RPC is used. My take is, I want to avoid defaulting behavior that could expose a larger dos vector.

**Comment by gotjoshua** [comment]
> such a large DOS vector

hmmmm. excellent point. perhaps the large pages could be allowed only from localhost, or otherwise configurable in a safe way.

During the regen testnet, I ran an extra node just for data queries and stats calculations. It was not even exposed. In this case and other cases with other security measures in place to prevent DOS, this hard coded value is not cool.

Perhaps this PR is far too simple and dangerous, but could you imagine to add a config option in the future?

**Comment by cmwaters** [comment]
I think the best option, at least in the short term, may be to use the `Unsafe` config variable. When this is set to true, we remove this upper bound and let the client decide the perPage value in their request else if `Unsafe` is false, we keep with the 100 `maxPerPage` upper bound.

https://github.com/tendermint/tendermint/blob/3a690568ae9fd3b9248fbebc480feae10ca5f5f2/config/config.go#L398

**Review by marbar3778 — APPROVED** [review]
utACK

**Pull request merged**
