### PR TITLE
refactor: Cmap improvement

### PR DESCRIPTION
**Pull request by shotonoff**
Small improvement of `cmap.CMap` mutex

### CODE REVIEW

**Comment by tychoish** [comment]
While I think this is probably a fine change, I have a few observations:
- RW Mutexes are slower *except* under certain kinds of workloads, so while I think it's theoretically and logically safe to make a lot of mutexes RW, there's a really  good chance that this class of changes will end up making things slower. 
- My inclination at this point in the history of go, is that if you need/want a thread-safe map, it makes sense to just use the `sync.Map` implementation rather than cooking one up ourselves.
- Based on my grepping of the code, I'm pretty sure that this code isn't used at all, and I think in light of that we should delete it rather than change it. Would you be interested in changing this PR along those lines?

**Comment by shotonoff** [comment]
Hi @tychoish, thank you for your feedback. 
* The idea behind RWMutex is not to block readers at all. it is suitable for the scene of more reading and less writing. which we have, correct me if I am wrong. CMap is used in `p2p` and `pex` packages.
* in terms of using `sync.Map`, everything depends on use cases. but, it might be right decision in high-concurrent application, what `tendermint` is

**Comment by tychoish** [comment]
> * The idea behind RWMutex is not to block readers at all. it is suitable for the scene of more reading and less writing. which we have, correct me if I am wrong. CMap is used in `p2p` and `pex` packages.

I just grepped the code base and I don't see any cases where cmap is used in master at all. I also locally deleted the files and ran a compile of all packages and didn't get any errors. I can definitely imagine use cases where RWMutexes would be useful, but it's hard to say in this case.

**Comment by creachadair** [comment]
This library doesn't appear to be used by the SDK either, so I think we could safely delete it.

**Comment by shotonoff** [comment]
I close PR since CMap is already deprecated in a master, thank you for feedback

**Pull request closed without merging**
