### PR TITLE
light/http: added check for err == nil

### LINKED ISSUE #8471: light/provider/http: (*http).signedHeader should just check if err == nil instead of checking on the type of the err is it is nil
**Tendermint version** (use `tendermint version` or `git rev-parse --verify HEAD` if installed from source):
e80dfa1ef51997a341b1a384eee0686aee925eaa

**Have you tried the latest version**: yes

If you look at the code in https://github.com/tendermint/tendermint/blob/8682489551b69d6b31947c9253c8c2f86fe4f2c7/light/provider/http/http.go#L238-L241

which relies on the underlying client's .Commit method to return a nil and untyped error. However this can be fallacious if at all a typed error would be returned yet the results was nil, we just need to check if the err == nil
```go
commit, err := p.client.Commit(ctx, height) 
if err == nil { // success!!
 	return &commit.SignedHeader, nil 
}
  
switch e := err.(type) { 
```

and this is an exhibit that can trivially show how things can fail https://go.dev/play/p/e9iAD00bhZB or inlined below
```go
package main

import (
	"fmt"
)

type myErr struct{ reason string }

func (me *myErr) Error() string { return me.reason }

func do() ([]byte, error) {
	var err *myErr
	return nil, err
}

func main() {
	_, err := do()
	fmt.Printf("%T\n", err)
}
```

which prints out NOT nil but instead
```shell
*main.myErr
```

### PR DESCRIPTION
**Pull request by jmalicevic**
Closes #8471 

Instead of checking whether the returned error *type* is nil, we check whether the error is nil. If not, only then do we check for its type.

### CODE REVIEW

**Review by creachadair — APPROVED** [review]
This change is fine, but I'm not sure I understand the motivation for it. The new code is exactly equivalent to the old.

**Comment by cmwaters** [comment]
> This change is fine, but I'm not sure I understand the motivation for it. The new code is exactly equivalent to the old.

I believe this is explained in https://github.com/tendermint/tendermint/issues/8471

**Comment by creachadair** [comment]
> > This change is fine, but I'm not sure I understand the motivation for it. The new code is exactly equivalent to the old.
> 
> I believe this is explained in #8471

The issue doesn't add anything: Returning a typed nil (as in the quoted example) would also cause an `err == nil` check to fail in the same way. The two are literally equivalent.

It's totally fine to make this change, I am just pointing out that it has no effect, and if it did it would be a bug.

**Comment by jmalicevic** [comment]
I am sorry I did not think more about it, it seemed straight forward but I agree with Michael, we are actually having identical code in terms of functionality. The return value will never be nil if we return values like this, even if nothing happened. If there is no error, then there should be an explicit nil on return. Tbh, we can merge this, but it was not a bug, I will remove the tag in any case.

**Comment by creachadair** [comment]
> The return value will never be nil if we return values like this, even if nothing happened. If there is no error, then there should be an explicit nil on return. Tbh, we can merge this, but it was not a bug, I will remove the tag in any case. 

The main argument for it in the issue was that if someone later changed the return type of the function we're calling to return a concrete error type instead of the error interface, and then returned a nil of that concrete type, it would change the behaviour of this code. But if someone did that case this code wouldn't even compile because one can't type switch on a concrete type. 

And in contrast if someone returned a concrete nil inside the error interface, both versions would skip the nil check case on error anyway. That subtlety is real and a valid corner gotcha in Go, but it generally has to be fixed on the upstream side when it occurs.

**Pull request merged**
