### PR TITLE
rpc: use HTTP error codes

### PR DESCRIPTION
**Pull request by ebuchman**
https://github.com/tendermint/tendermint/issues/457

### CODE REVIEW

**Comment by mappum** [comment]
👍 Good choices of response codes

**Comment by ebuchman** [comment]
Thanks. I wasn't sure about some - like 404 when the http endpoint is found but the jsonrpc method is not ...

**Comment by mappum** [comment]
That use of 404 is common in REST APIs, it should be fine.

Soon we'll be able to make use of 402 (Payment Required) 😄

**Comment by mappum** [comment]
Looks like it matches the JSONRPC spec closely enough: http://www.jsonrpc.org/historical/json-rpc-over-http.html#errors

**Comment by ebuchman** [comment]
Cool. What's the deal with those codes, beside status? 

And should we be doing things like 202 for broadcast_tx_sync where its in the mempool but hasn't been committed?

**Comment by mappum** [comment]
Those are the codes to be set in the response JSON. But honestly we don't need to adhere to the spec 100%, people will probably just check the HTTP status code over the JSONRPC code. I'd never heard of 202, and some clients just check `statusCode == 200` so probably not worth it.

**Pull request merged**
