### PR TITLE
wire: json time in nanoseconds

### PR DESCRIPTION
**Pull request by ebuchman**
json marshaling of time.Time would drop the nanoseconds (while official blocks keep them), making it impossible for eg a client to verify the block hash given the block from json. fixes https://github.com/tendermint/tendermint/issues/138

### CODE REVIEW

**Comment by ebuchman** [comment]
fixed to be backwards compatible and added pong handler to the client. this was all for stuff that came up when testing the mint-client

**Comment by jaekwon** [comment]
Check out the json_time2 branch, which strips anything more granular than milliseconds.
The reason is that Javascript has a hard time with nanoseconds.

**Comment by ebuchman** [comment]
welcome back :)

I didn't fully investigate the client problem: it worked fine natively but it was failing across docker containers, where adding the pong handler fixed that. 

As per json, nice, didn't realize javascript had such issues. But why change the format like that? Why not the old rfc just only with milliseconds (I'm just thinking for backwards compatibility ...)

**Comment by ebuchman** [comment]
also do you want to bring my time test across to your branch too? we just want to make sure the test actually tests the precision we're using

**Comment by ebuchman** [comment]
ahh string sortable ok I guess that's a good enough reason to break things ...

**Comment by jaekwon** [comment]
Sweet, yeah lets port the test, though the comment "we support nanoseconds!" is now wrong.
Adding the pong handler fixed the issue on docker containers?  Or the ping handler?

**Comment by jaekwon** [comment]
Good to be back, Ethoshi.

**Comment by ebuchman** [comment]
sorry I meant the ping handler (presumably that was it since the pong handler just returns nil and the server doesnt send pongs autonomously)

**Comment by ebuchman** [comment]
gorillas default write timeout seems to be one second: https://github.com/gorilla/websocket/blob/master/conn.go#L24 
we can bring it down from 30, I just copied what was used by the server

**Comment by jaekwon** [comment]
I think the 30 is okay.
(I was concerned about SetWriteDeadline in the gorilla impl.  The code isn't easy to grok for me but it seems like it'll unset the write deadline when writing non-ping/pong messages later, so I guess it's OK)

**Comment by ebuchman** [comment]
ah I think you/the impl is supposed to set the write deadline each time, since its always an absolute time

**Comment by jaekwon** [comment]
It looks like wsc.WriteJSON() calls gorilla/websocket/conn.js NextWriter's Write() which calls Conn's flushFrame() which calls write() with c.writeDeadline which always sets the write deadline to c.writeDeadline.  So it looks like the client user doesn't need to worry about it.

**Comment by ebuchman** [comment]
but I'm not seeing where `c.writeDeadline` gets set, besides calling SetWriteDeadline, which is only called by functions that take a deadline, and in all instances of those calls `c.writeDeadline` is being passed, which seems circular, so presumably the client is supposed to deal with it. else, what happens if the deadline is in the past?

**Comment by jaekwon** [comment]
From the golang net docs, "A zero value for t means I/O operations will not time out."  We never set it, so it's zero.  So, though our custom ping handler may time out after 30 seconds, once we send a message the deadline gets reset to zero.

**Comment by ebuchman** [comment]
so we should also set the write deadline before the WriteJson's?

**Comment by jaekwon** [comment]
No, it looks like we don't need to.

**Comment by ebuchman** [comment]
because the control messages will just keep resetting it for us

**Comment by jaekwon** [comment]
Yeah.

**Comment by ebuchman** [comment]
great. shall I add that and the test to your branch

**Comment by jaekwon** [comment]
Will merge in json_time2 which includes the ping handler and a test

**Pull request closed without merging**
