### PR TITLE
rpc: reformat method signatures and use a context

### PR DESCRIPTION
**Pull request by tychoish**
I was digging around over here, and thought it'd be good to
cleanup/standardize the line formating on a few of these methods. Also
found a few cases where we could use contexts better so did a little
bit of cleanup there too!

### CODE REVIEW

**Review by creachadair — APPROVED** [review]
This seems good. A lot of these will also be less spammy once I sort out the kinks in the change to make the method handlers take structs instead of positional parameters. (That in turn letting us have control over the encoding of basic types again)

**Review by thanethomson — APPROVED** [review]
Awesome to see the `Context`s being effectively employed :+1:

**Comment by tychoish** [comment]
> Awesome to see the `Context`s being effectively employed +1

It's sort of wackamole with them, but I'm trying. In general, any place that could use them but isn't is probably just an oversight in a corner of the code I don't look at much or that is in a form that's hard to  grep for. 

> This seems good. A lot of these will also be less spammy once I sort out the kinks in the change to make the method handlers take structs instead of positional parameters. (That in turn letting us have control over the encoding of basic types again)

That seems like a lovely future to be working towards, and I'm excited about it! Sorry if any of my changes stampled on things that you might have been working on.

**Comment by creachadair** [comment]
> It's sort of wackamole with them, but I'm trying. In general, any place that could use them but isn't is probably just an oversight in a corner of the code I don't look at much or that is in a form that's hard to grep for.

There are some tools that we could probably adapt if we want to be more systematic about it, but whack-a-mole seems safer given how much entanglement we still have.

> That seems like a lovely future to be working towards, and I'm excited about it! Sorry if any of my changes stampled on things that you might have been working on.

No problem, this is easy to rebase. My main issue right now is we have a bunch of custom code that allows both array-format and object format parameters to be interchangeable. That's relatively easy to fix, but there's still a big knot in the encoding logic. So this is not the long pole, and is anyways worthwhile.

**Comment by tychoish** [comment]
> There are some tools that we could probably adapt if we want to be more systematic about it, but whack-a-mole seems safer given how much entanglement we still have.

Yeah, also I think I got all of the big culprits, so the things that are left are small fries, but it's still good (if nothing else to clean up the stack trace during thread dumps,) but I don't see a big problem with things as they stand today.

> No problem, this is easy to rebase. My main issue right now is we have a bunch of custom code that allows both array-format and object format parameters to be interchangeable. That's relatively easy to fix, but there's still a big knot in the encoding logic. So this is not the long pole, and is anyways worthwhile.

Funtimes. Deeply worthwhile.

**Pull request merged**
