### PR TITLE
docs: Add BSD install script

### PR DESCRIPTION
**Pull request by ValarDragon**
Add quick installation script for FreeBSD. This is in relation to #1663.

### CODE REVIEW

**Comment by ValarDragon** [comment]
Can this be merged? (I don't have permission to do so)

**Comment by melekes** [comment]
Tests have to be fixed. Sorry. @xla is on it.

**Comment by xla** [comment]
Tests are fixed in #1702.

**Comment by ValarDragon** [comment]
Thanks! Rebased this to develop.

**Pull request merged**
