### PR TITLE
test/fuzz: bring changes from v0.34.x into main

### PR DESCRIPTION
**Pull request by elias-orijtech**
Completes PR #9183 by adding the rest of the fuzzing change from the
old default branch (master).

### CODE REVIEW

**Comment by elias-orijtech** [comment]
CC @cmwaters @odeke-em

**Comment by cmwaters** [comment]
Hey, it looks like you'll need to fix a few things to stop the linter from complaining

**Comment by elias-orijtech** [comment]
> Hey, it looks like you'll need to fix a few things to stop the linter from complaining

Done.

**Comment by elias-orijtech** [comment]
Rebased. The markdown-link-check failure doesn't seem related.

**Comment by thanethomson** [comment]
Sorry @elias-orijtech, it seems there are a bunch of new conflicts now.

**Comment by odeke-em** [comment]
@thanethomson and team please help take a look again, Elias rebased almost 2 weeks ago. Thanks!

**Review by cmwaters — APPROVED** [review]

**Comment by cmwaters** [comment]
Thanks, apologies for the delay, most of us have been away.

**Pull request merged**
