### PR TITLE
Remove obsolete abci methods, no longer called by ABCI++ Tendermint

### PR DESCRIPTION
**Pull request by sergio-mena**
At a first stage, we had decided to leave `BeginBlock`, `DeliverTx`, `EndBlock` in the ".proto" file, marked as deprecated. However, since Tendermint will not be calling them, an App developer might be tempted to implement them, which would result in dead code.

This PR removes those ABCI methods from the ".proto" file.

The PR also adds a link to ABCI++ spec in the "UPGRADING.md" file, as a preliminary step to documenting the upgrade process.

### CODE REVIEW

**Comment by creachadair** [comment]
The reasoning here makes sense, but I wonder: Do we need to worry about being able to read stored responses in order to validate old blocks? I seem to recall we do rely on some of the ABCI response data being persisted in order to deal with synchronization.

**Review by tychoish — APPROVED** [review]
seems good but fix lint

**Comment by sergio-mena** [comment]
> The reasoning here makes sense, but I wonder: Do we need to worry about being able to read stored responses in order to validate old blocks? I seem to recall we do rely on some of the ABCI response data being persisted in order to deal with synchronization.

Are you thinking of `ResponseDeliverTx`?
If yes, the first version of this patch was indeed nuking it, but then I realized it was used elsewhere (I saw it was used by RPC-related code). So I decided to leave it there (check the [4th commit](https://github.com/tendermint/tendermint/pull/8633/commits/e0ee9f5) of this PR, the one with an unfinished commit message 😊).

The rest of the protobuf data structures deleted in this PR are just not used elsewhere in the "manually generated" code.

**Comment by creachadair** [comment]
> Are you thinking of `ResponseDeliverTx`? 

Yes, and I wasn't sure if there were others.

**Pull request merged**
