### PR TITLE
support multisig address

### PR DESCRIPTION
**Pull request by ylsGit**
## Description

_Please add a description of the changes that this PR introduces and the files that
are the most critical to review._ 

Closes: 

ethsecp256k1.PubKey is not support in tendermint. The original problem is: 
* ethermint issue: https://github.com/cosmos/ethermint/issues/716
* ethermint PR: https://github.com/cosmos/ethermint/pull/718

### CODE REVIEW

**Comment by marbar3778** [comment]
Hey thanks for opening this PR. Could you add a description to the PR to better understand the need for this change?

**Comment by ylsGit** [comment]
> Hey thanks for opening this PR. Could you add a description to the PR to better understand the need for this change?

update above

**Comment by fedekunze** [comment]
I don't see any value on adding support for custom multisigs in v0.33 especifically. Ethermint will be updated to stargate so this change won't apply anymore. 

I think adding multisig support for custom key types/algos needs to be written down in an ADR (not sure if this is the best place to do so tho).

**Comment by tessr** [comment]
This PR needs more context and justification. What are the use cases here? What's the connection to Ethermint? This appears to be attached to Amino, as well, which we are urging people to move away from at their earliest convenience. 

Finally, this PR seems to change the library we use for some crypto stuff to a fork of the original library. We are cautious about dependency changes like this and would need more context on the new dependency.

**Pull request closed without merging**
