### PR TITLE
p2p: use fifo in test

### PR DESCRIPTION
**Pull request by williambanfield**
My hypothesis is that using the priority queue in testing will allow for a message to not be dropped that is needed for consensus.

### CODE REVIEW

**Comment by cmwaters** [comment]
Don't we want to test for all supported types or at a minimum the type that is default?

**Comment by tychoish** [comment]
> Don't we want to test for all supported types or at a minimum the type that is default?

I believe that the content of this test is not the queue type, and that the load shedding in the priority queue caused the test to flake.

**Review by tychoish — APPROVED** [review]

**Comment by cmwaters** [comment]
> I believe that the content of this test is not the queue type

It's not just a test, it's all tests

> the load shedding in the priority queue caused the test to flake.

Does FIFO load shed at all?

**Comment by tychoish** [comment]
> It's not just a test, it's all p2p tests

Good call. I don't think, given the fact that the entire networking layer of the tests isn't used it tests, the tests that use these fixtures (e.g. the reactor tests) aren't particularly interested in the inner workings of the router plumbing (which isn't to say it's bad that we use "real" p2p code in the test fixtures, as I think that provides some confidence in some of the higher level plumbing, but by the time we get to the queues, I don't think there's a lot of milage that we would get out of using non-fifo queues. (Except that it would make many tests less reliable if we shed load in tests.) 

> Does FIFO load shed at all?

Nope.

**Comment by tychoish** [comment]
Should we put this in `master`?

**Pull request merged**
