### PR TITLE
abci: add priority to checkTx response

### PR DESCRIPTION
**Pull request by ninjaahhh**
## Description

our team is leveraging tendermint for [our own development](https://forum.cosmos.network/t/introduction-to-abcix-an-extension-of-abci-with-greater-flexibility-and-security/3771) and realized there may be something worth contributing back. 

after chatting with @marbar3778 and @zmanian we agreed that a good first step would be on mempool: we would like to help improve current implementation of mempool to support packing transaction based on priorities (we have a [working prototype](https://github.com/QuarkChain/tendermintx/blob/master/mempool/tree_mempool.go) using left-leaning red–black tree), which also includes some work on generalizing current mempool interface.

Closes https://github.com/tendermint/tendermint/issues/1861

this minor PR will be a starting point, where the change itself should be backward-compaible and self-explanatory. we would like to also hear more feedback on how to go further (e.g. RFC process, etc.) on future non-trivial PRs.

### CODE REVIEW

**Comment by melekes** [comment]
> we would like to help improve current implementation of mempool to support packing transaction based on priorities (we have a working prototype using left-leaning red–black tree), which also includes some work on generalizing current mempool interface.

that's great @ninjaahhh 👍 the good first step would be an [ADR](https://github.com/tendermint/tendermint/tree/master/docs/architecture#architecture-decision-records-adr) outlining the pitfalls of current implementation and suggested changes. When we reach consensus, we should be able to move forward w/ the implementation. Note: it's better to break up work into smaller PRs, if possible.

Relevant issues: https://github.com/tendermint/tendermint/issues/2147, https://github.com/tendermint/tendermint/issues/2484, https://github.com/tendermint/tendermint/issues/3905

**Comment by marbar3778** [comment]
Thank you for opening this PR, prior to merging we should update the spec repo with the corresponding changes.

**Comment by tessr** [comment]
Thank you for helping out here! I agree with @melekes that we need to all agree on a design and a high-level direction first. In fact, before starting on an ADR, I would recommend that we begin with an RFC, which can address the high-level direction before getting into the details addressed in an ADR. 

We haven't always been the best about writing RFCs, but we're currently in the process of cleaning up our spec and design work, and this is a great opportunity to practice and develop our RFC process. RFCs live [in the spec repo](https://github.com/tendermint/spec/tree/master/rfc) and there's a template for them as well.

**Comment by ninjaahhh** [comment]
thanks for the pointers! rfc PR added https://github.com/tendermint/spec/pull/154

feeback will be greatly appreciated

**Comment by melekes** [comment]
Refs https://github.com/tendermint/tendermint/issues/1861

**Pull request closed without merging**
