### PR TITLE
Sol events

### PR DESCRIPTION
**Pull request by androlo**
Simple update to send LOGX events to event switch. It adds a small struct to vm types that is used both to add the event data as proper hex-strings for the event-switch but also to use for the log entry in vm dump since the normal one prints garbage characters.

It is far from ideal, and I only use the proxy object because I don't know how to make it work with 'binary', though i guess it should be easy for those that know how to just take care of that. 

There is also a test there that runs a LOG4, fires off the event, catches it and makes sure the data is correct.

I cant do more on this. Either if someone pulls into dev and does any modifications when there is time, or keep it on this branch maybe until it is high enough standard.

### CODE REVIEW

**Comment by ebuchman** [comment]
This is great. Short and sweet. Need to remove that IDE file. And why the fake_app_state rename? Presumably thats a mistake

**Comment by androlo** [comment]
It is mistakes. If You think the feature is good I will clean it up and make another pr. Was also gonna ask about the event name, like what should the name in types be. I put 'EventStringSolidityEvent' now but that doesn't sound very good.

**Comment by ebuchman** [comment]
ya, let me just review the tests and the use of the Log elsewhere in the code (I think we've mostly ignored it, not sure if we should stick it in the chain or not)

**Comment by jaekwon** [comment]
Thanks!
See: https://github.com/tendermint/tendermint/commit/0a72c1ee50d706bbfbfb218d610e3744d80e0489
Modified tendermint/binary to support fixed-length arrays.  Does this work for you?

**Comment by androlo** [comment]
I have pulled latest and done some tests, and things look fine.

Again sorry for the mess. I was about to go in and update the branch today and make another PR but I guess that's not needed. Looked at the vm.go file and how you changed, and it looks much better + the event id is better.

Here's some output from javascript btw., just as confirmation. Running this solidity contract:

```
contract testevent {
    event TestEvent(int indexed anIndexedInt, bytes32 indexed anIndexedBytes32, bool anUnIndexedBool);

    function(){
        TestEvent(-1, "haha", true);
    }
}
```

This is the event I get:

```
{ Address: '0000000000000000000000009FC1ECFCAE2A554D4D1A000D0D80F748E66359E3',
  Topics: 
   [ '88C4F556FDC50387EC6B6FC4E8250FECC56FF50E873DF06DADEEB84C0287CA90',
     'FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF',
     '6861686100000000000000000000000000000000000000000000000000000000' ],
  Data: '0000000000000000000000000000000000000000000000000000000000000001',
  Height: 1 }
```

The address is correct. Not sure how familiar you are with Solidity and its events, but the first topic is non-anonymous events is the sha3 hash of the "function signature" of the event. The boolean is in data because it does not have the `indexed` modifier.

**Pull request closed without merging**
