### PR TITLE
Update oss-fuzz-build.sh

### PR DESCRIPTION
**Pull request by AdamKorcz**
Fixes the tendermint OSS-Fuzz build by adjusting for some infra changes that were made in OSS-Fuzz.

---

#### PR checklist

- [ ] Tests written/updated, or no tests needed
- [ ] `CHANGELOG_PENDING.md` updated, or no changelog entry needed
- [ ] Updated relevant documentation (`docs/`) and code comments, or no
      documentation updates needed

### CODE REVIEW

**Comment by AdamKorcz** [comment]
> Hey @AdamKorcz can you point to some documentation that describes the change that was made within `OSS-Fuzz`?

https://github.com/google/oss-fuzz/pull/8937#issuecomment-1306992268

**Comment by AdamKorcz** [comment]
@odeke-em PTAL

**Review by odeke-em — APPROVED** [review]
LGTM and thank you @AdamKorcz!

**Comment by odeke-em** [comment]
Kindly cc-ing @cmwaters @thanethomson @williambanfield for w merge. Thank you.

**Review by thanethomson — APPROVED** [review]

**Pull request merged**
