### PR TITLE
broadcast_tx via grpc

### PR DESCRIPTION
**Pull request by ebuchman**
It's nice to have a broadcast_tx available over grpc so app devs can get started with nothing but a grpc lib for both tmsp and sending txs.

That said, grpc is a bit of a headache. It breaks the semantics of BroadcastTxCommit because it doesn't allow you to return a result and an error (eg. CheckTx result but error because it doesn't get committed). It's also not playing nice with glide for unknown reasons.

### CODE REVIEW

**Comment by tomtruitt** [comment]
https://github.com/tendermint/tmsp/commit/3329868a1d19c8f7c67088a275fa6c877d3743ba did you fix this issue with returning results?

**Comment by ebuchman** [comment]
not sure what you're asking here

**Comment by tomtruitt** [comment]
In this issue you said;

"grpc is a bit of a headache. It breaks the semantics of BroadcastTxCommit because it doesn't allow you to return a result and an error (eg. CheckTx result but error because it doesn't get committed)."

In the commit I referenced I see addition of:
`return types.Result{}`
To grpc_client.

So I thought maybe you came up with a fix or a new way to do it. And since we are building on grpc I've been curious about the implications of this issue for us

**Comment by ebuchman** [comment]
Oh no. That commit is just fixing a compile error. Does not address the problems mentioned in the opening comment

**Comment by mdyring** [comment]
Why not just populate ReponseBroadcastTx with the values from the step that fails (be it CheckTx or AppendTx).

I don't think from a BroadcastTx user perspective it matters much if it failed in CheckTx or AppendTx, and the response structures are compatible

message ResponseBroadcastTx{
	uint64 		  code        = 1; // TODO: import tmsp ...
	bytes             data        = 2;
	string            log         = 3;
}

message ResponseAppendTx{
	CodeType          code        = 1;
	bytes             data        = 2;
	string            log         = 3;
}

message ResponseCheckTx{
	CodeType          code        = 1;
	bytes             data        = 2;
	string            log         = 3;
}

**Comment by ebuchman** [comment]
So you don't think it matters if the caller knows whether it failed in CheckTx or AppendTx?

**Comment by ebuchman** [comment]
This is now a breaking change since it changes the response struct for BroadcastTxCommit, but I think that's for the best.

**Comment by jaekwon** [comment]
StartGRPCClient might eventually need to be refactored out so the client doesn't require importing tendermint/rpc/core and thus the whole kitchen sink.  But otherwise LGTM.  We can merge this in.

**Comment by tomtruitt** [comment]
@jae just a reminder the TMSP bindings need to be upgraded for compatibility with GRPC 1.0

**Comment by tomtruitt** [comment]
Sorry i guess that is a separate issue

**Comment by tomtruitt** [comment]
i just now realized this isn't grpc_fix branch.. is that branch still relevant?

**Comment by ebuchman** [comment]
this branch just needs to be rebased and then it should get merged into develop

**Comment by tomtruitt** [comment]
image

that's as far as i can get lol

**Pull request merged**
