### PR TITLE
p2p/pex: fix flaky tests

### PR DESCRIPTION
**Pull request by alessio**
*testing.T.TempDir() causes test cases to fail when
it is unable to remove the temporary directory once
the test case execution terminates. This seems to
happen often with pex reactor test cases.

### CODE REVIEW

**Comment by erikgrinaker** [comment]
I don't really understand why these would fail. Any ideas?

**Comment by alessio** [comment]
@erikgrinaker This smells like the culprit maybe?

```
func (a *addrBook) saveRoutine() {
	defer a.wg.Done()

	saveFileTicker := time.NewTicker(dumpAddressInterval)
out:
	for {
		select {
		case <-saveFileTicker.C:
			a.saveToFile(a.filePath)
		case <-a.Quit():
			break out
		}
	}
	saveFileTicker.Stop()
	a.saveToFile(a.filePath)
}
```

```
// OnStart implements Service.
func (a *addrBook) OnStart() error {
	if err := a.BaseService.OnStart(); err != nil {
		return err
	}
	a.loadFromFile(a.filePath)

	// wg.Add to ensure that any invocation of .Wait()
	// later on will wait for saveRoutine to terminate.
	a.wg.Add(1)
	go a.saveRoutine()

	return nil
}
```

**Comment by erikgrinaker** [comment]
Yeah, seems reasonable

**Comment by alessio** [comment]
This relates to #5732

**Review by erikgrinaker — APPROVED** [review]
I think this fix is fine for now, since it preserves the previous behavior. Maybe add a `FIXME` to investigate the goroutine leaks.

**Review by cmwaters — APPROVED** [review]
Yup this fixes the failures with the PEX reactor test. As anton mentioned, I'm seeing `TestWALCrash` fail - so perhaps we will also need to revert/fix this too

**Pull request merged**
