### PR TITLE
libs/pubsub/query: specify peg version in go.mod

### PR DESCRIPTION
**Pull request by mark-rushakoff**
The code to generate the pubsub queries was dependent on an unspecified
version of the peg tool. This brings peg into go.mod so it is on a fixed
version. This should also enable dependabot to notify us of future
updates to peg.

The version of query.peg.go generated from the current version of peg
correctly contains the special "Code generated by..." line to indicate
to other tools that the file is automatically generated and should
therefore be excluded from linters, etc.

I removed the make target as there were no git grep results referencing
"gen_query_parser"; directly running "go generate" is a reasonable
expectation in Go projects.

Now that "go run" is module aware, I would typically use "go run" inside
the go:generate directive, but in this case we go build to a gitignore-d
directory in order to work around the nondeterministic output detailed
in pointlander/peg#129.

### CODE REVIEW

**Review by tychoish — APPROVED** [review]

**Comment by creachadair** [comment]
Alternatively you might want to consider https://github.com/tendermint/tendermint/pull/7338

**Comment by tychoish** [comment]
I think #7383 is the better solution to this problem, but also this change is fine.

My only concern is that we make sure that the regeneration detector triggers for this would detect if there's an upgrade to the library that causes the code to change. I sometimes see errors caused by the generated code change detector, but haven't had cause to dig into its actual operation.

**Review by tychoish — APPROVED** [review]

**Comment by creachadair** [comment]
To be clear, I don't have any objection to this change either. It's just that we don't need to depend on code generation _and_ we get a massive speedup and reduction in memory use with the other approach. (That said, it's the same API either way)

**Comment by mark-rushakoff** [comment]
I'm okay with the principle of bringing in the alternative implementation #7338 instead of this -- I'm inclined to say it's "safe" for 0.37, but I don't have enough context to say so confidently. I don't mind dropping this PR and porting #7338 instead, so WDYT @tychoish @creachadair?

**Comment by creachadair** [comment]
> I'm okay with the principle of bringing in the alternative implementation #7338 instead of this -- I'm inclined to say it's "safe" for 0.37, but I don't have enough context to say so confidently. I don't mind dropping this PR and porting #7338 instead, so WDYT @tychoish @creachadair?

It's probably simpler to just merge this as-is for now. One thing I forgot is that because `main` is based on v0.34.x, we'd have to re-address the event structure change. That makes a port more work than it would have been.

**Pull request merged**
