### PR TITLE
WIP: Add goreleaser

### PR DESCRIPTION
**Pull request by adrianbrink**

### CODE REVIEW

**Comment by adrianbrink** [comment]
@zramsay @Greg-Szabo

**Comment by zramsay** [comment]
this would deprecate part of the release script introduced by @melekes a month or so ago, so this PR should be updated to sync with that script

**Comment by adrianbrink** [comment]
* look into gitian.org
* builds need to be fully reproducible

**Comment by melekes** [comment]
https://github.com/goreleaser/goreleaser/blob/master/pipeline/build/build.go#L89-L102

goreleaser uses `go build`, so it is not hermetic build per se. But I guess it should be fine for other small projects like gaia.

**Comment by ebuchman** [comment]
Let's integrate this into the release script

**Comment by adrianbrink** [comment]
Closed based on conversation at the retreat about build and release process.

**Pull request closed without merging**
