### PR TITLE
fix #3460: replayBlocks checkAppHash should't wait the last block

### LINKED ISSUE #3460: replayBlocks checkAppHash should't wait the last block
**Tendermint version** (use `tendermint version` or `git rev-parse --verify HEAD` if installed from source):
0d985ede28bd6937fa9d3613618e42cab6fc871c

**ABCI app** (name for built-in, URL for self-written if it's publicly available):

**Environment**:
- **OS** (e.g. from /etc/os-release):
- **Install tools**:
- **Others**:

**What happened**:
there are some code should be enhanced

**What you expected to happen**:
I will contribute code later
**Have you tried the latest version**: yes/no

**How to reproduce it** (as minimally and precisely as possible):

**Logs (paste a small part showing an error (< 10 lines) or link a pastebin, gist, etc. containing more of the log file)**:

**Config (you can paste only the changes you've made)**:

**node command runtime flags**:

**`/dump_consensus_state` output for consensus bugs**

**Anything else we need to know**:

### PR DESCRIPTION
**Pull request by Zerppen**
* [x] Updated all relevant documentation in docs
* [x] Updated all code comments where relevant
* [x] Wrote tests
* [x] Updated CHANGELOG_PENDING.md

### CODE REVIEW

**Comment by melekes** [comment]
How merging develop to master is going to fix #3460?

**Comment by Zerppen** [comment]
@melekes yeah,It's first time ,I used to use JIRA to merge

**Comment by Liamsi** [comment]
Do you want to open a new PR then or should we leave this one open until it's fixed? 
IMHO It's probably worth reading into https://github.com/tendermint/tendermint/blob/master/CONTRIBUTING.md and create a new PR.

**Comment by Zerppen** [comment]
@Liamsi  I updated docs and did tests,I need authority to pull request

**Comment by Liamsi** [comment]
I'll close this for now. If anything this should go on a seperate branch with a pull request against the `develop` branch (currently `develop` against `master`). It does not seem to contain any changes and the author also opened #3465 which supposedly also fixes #3460.

**Pull request closed without merging**
