### PR TITLE
node: always close database engine (#7113)

### PR DESCRIPTION
**Pull request by firelizzard18**
Manual backport of #7113 to 0.35

### CODE REVIEW

**Comment by creachadair** [comment]
This looks pretty reasonable to me. If you can please update your branch, I'll trigger the CI.

**Comment by creachadair** [comment]
This looks pretty reasonable to me. If you can please update your branch, I'll trigger the CI.

**Comment by firelizzard18** [comment]
@creachadair I rebased onto the latest `v0.35.x`

**Comment by creachadair** [comment]
Thanks. It looks like [this error](https://github.com/tendermint/tendermint/runs/6040210228?check_suite_focus=true) is a real (new) failure that we'll have to figure out. I don't see an obvious cause yet, but it looks like we're either closing something too soon or writing after we should be.

**Comment by creachadair** [comment]
> Thanks. It looks like [this error](https://github.com/tendermint/tendermint/runs/6040210228?check_suite_focus=true) is a real (new) failure that we'll have to figure out. I don't see an obvious cause yet, but it looks like we're either closing something too soon or writing after we should be.

Hmm, maybe I'm wrong. It passed on rerun. Given that the WAL code is not implicated here that is something of a relief, but I'm not sure why this popped up.

**Review by creachadair — APPROVED** [review]

**Comment by firelizzard18** [comment]
Tests passing on rerun makes me uncomfortable, but the fix I needed was merged so 🥳

**Comment by creachadair** [comment]
> Tests passing on rerun makes me uncomfortable, but the fix I needed was merged so 🥳. Thanks 😄.

We are in a long process of chasing down and fixing flaky tests. I'm pretty sure in this case it was legitimately transient. Of course, we still need to fix that, but it wasn't caused by your change. 🙂

**Pull request merged**
