### PR TITLE
makefile: Add `make check_dep` and remove `make ensure_deps`

### PR DESCRIPTION
**Pull request by ValarDragon**
This adds a new makefile command, which is used in CI linting, `make check_dep`.
This ensures the toml is in sync with the lock, and that were not pinning to a
branch in any repository.

This also adapts `make get_vendor_deps` to check the lock, in addition to
populating the vendor directory. This removes the need for `make ensure_deps`.

This makes `make get_vendor_deps` consistent between tendermint and the sdk.

This would stop problems like #2053 from happening. 

* [ ] Updated all relevant documentation in docs - anything I should be updating
* [x] Updated all code comments where relevant - i think so
* [x] Wrote tests - n/a
* [x] Updated CHANGELOG.md

### CODE REVIEW

**Comment by ValarDragon** [comment]
I'm not sure why this is failing `test_p2p`. Its failing when running `make get_vendor_deps` in the docker file, but I don't see why this would fail, since it should have had the toml and lock.

**Comment by melekes** [comment]
```
--> Running dep
no dirs contained any Go code
```

**Comment by ValarDragon** [comment]
ohh that makes sense. I've just re-ordered the lines for copying in the files in the dockerfile! That fixes it.

**Comment by ValarDragon** [comment]
Presuming tests pass, this should be fine to merge. (Could this be squashed via github)

**Pull request merged**
