### PR TITLE
libs/bits: validate BitArray in FromProto

### LINKED ISSUE #5705: libs/bits: BitArray.FromProto code invalidly tries to clear pointer receiver, plus uses a reference of Elements instead of a copy
**Tendermint version** (use `tendermint version` or `git rev-parse --verify HEAD` if installed from source):
Version 170cb70e19f6de262598279b9fccaa968ec6d3dc

**What happened**:
Auditing dependencies for the cosmos-sdk and I noticed this code
https://github.com/tendermint/tendermint/blob/4827ed121f3c4da2a621ddb47e4700565c430d1e/libs/bits/bit_array.go#L434-L444

## Problems in it:
a) If protoBitArray is nil, it tries to set the pointer receiver to nil; but that operation doesn't reflect on the outside, because of the way pointer receivers are created demoed at https://play.golang.org/p/6IXb-hsVJ7s or inlined below
```go
package main

import "fmt"

func main() {
	s := &sk{dt: []int{12, 19}}
	s.fromOther(nil)
	fmt.Printf("%#v\n", s)
}

type sk struct {
	dt []int
}

func (s *sk) fromOther(dk *sk) {
	if dk == nil {
		s = nil
		return
	}
	s.dt = dk.dt
}
```

it'll still print the prior result
```shell
&main.sk{dt:[]int{12, 19}}
```
Did we mean to instead clear out all the fields of the receiver?
It doesn't work because to change a pointer value, you need an lvalue aka a variable receiving it. If it were a `**`, then one could do `*s = nil`.

b) FromBitArray blindly reuses the slice passed in from its arguments; which means that someone can later change the underlying slice and mutate the end result
c) ToProto also blindly passes in the underlying slice
https://github.com/tendermint/tendermint/blob/4827ed121f3c4da2a621ddb47e4700565c430d1e/libs/bits/bit_array.go#L427-L430

For both b) and c) we should make a copy of the slice Elems.

### PR DESCRIPTION
**Pull request by melekes**
Closes #5705

### CODE REVIEW

**Review by erikgrinaker — COMMENTED** [review]
I think I share your skepticism on the issue about whether it's necessary to copy slices during Protobuf (un)marshaling. These structs are often just used immediately and then discarded, and I suspect copying every time we (un)marshal would be too expensive in the general case (i.e. for all structs everywhere) - although it would definitely be safer.

**Comment by melekes** [comment]
BitArrays we're creating are small enough (1-4 elems) for us to not care about performance imho. But I can remove copying if you feel strongly against it.

**Comment by erikgrinaker** [comment]
>BitArrays we're creating are small enough (1-4 elems) for us to not care about performance imho. But I can remove copying if you feel strongly against it.

I'm not particularly concerned about bitarrays specifically. But the precedent we're setting here is that whenever we convert to/from a Protobuf struct we must make deep copies of all data. Why are we only copying here, and not in all Protobuf structs? And wouldn't it get too expensive to do it everywhere?

**Comment by melekes** [comment]
> > BitArrays we're creating are small enough (1-4 elems) for us to not care about performance imho. But I can remove copying if you feel strongly against it.
> 
> I'm not particularly concerned about bitarrays specifically. But the precedent we're setting here is that whenever we convert to/from a Protobuf struct we must make deep copies of all data. Why are we only copying here, and not in all Protobuf structs? And wouldn't it get too expensive to do it everywhere?

good point! it would be expensive to do it everywhere

**Comment by melekes** [comment]
Removed copying. Still it feels a bit unsafe to not copy when converting **to** proto because we might continue to use / modify the same struct after.

**Comment by erikgrinaker** [comment]
>Removed copying. Still it feels a bit unsafe to not copy when converting to proto because we might continue to use / modify the same struct after. Maybe we should consider changing this?

Yeah, it's a tradeoff. Normally we just convert to Protobuf and send the message immediately, but not always. Should probably be benchmarked in a few hot paths.

**Comment by marbar3778** [comment]
hmm, do we even need to go to proto and back for bitarray? I think we can remove it from the type and not have to worry about this.

**Review by erikgrinaker — APPROVED** [review]

**Pull request merged**
