### PR TITLE
libs: internalize some packages

### PR DESCRIPTION
**Pull request by marbar3778**
## Description

Internalize some libs. This reduces the amount ot public API tendermint is supporting. The moved libraries are mainly ones that are used within Tendermint-core.

### CODE REVIEW

**Comment by alexanderbez** [comment]
Has there been discussion on what is being moved to an internal private package?

**Comment by marbar3778** [comment]
> Has there been discussion on what is being moved to an internal private package?

Not yet, these changes are made based on the packages that tendermint only uses. There are some more packages, but wanted to stick with these for now.

**Comment by cmwaters** [comment]
There is an [ADR](https://github.com/tendermint/tendermint/blob/master/docs/architecture/adr-060-go-api-stability.md) that Erik wrote about Go API's.

This is an excerpt from it regarding what should be left public

>The following is the minimum set of public APIs that will be included in 1.0, in some form:
>
> - abci
> - node and related packages (e.g. possibly config, libs/log, and version)
> - Client APIs, i.e. rpc/client, light, and privval.
> - crypto (possibly as a separate repo)

**Review by cmwaters — COMMENTED** [review]
I think the only question I have with this is do we want to internalise the `Service` interface?

**Comment by marbar3778** [comment]
> I think the only question I have with this is do we want to internalise the `Service` interface?

good catch, we would not want to.

**Review by cmwaters — APPROVED** [review]

**Pull request merged**
