### PR TITLE
PEX issues #335

### PR DESCRIPTION
**Pull request by melekes**
This is a 2 PR change fixing #335

2nd PR: https://github.com/tendermint/go-p2p/pull/12

In this PR:
- test p2p pex reactor
- save seeds when they are provided to avoid losing them.

Saving seeds while starting the node might look like a hack, but while I was exploring the options, this was the best possible solution I could think of. If you think different, please let me know.

### CODE REVIEW

**Comment by melekes** [comment]
Sample test output:

```
----------------------------------------------------------------------
Testing pex creates the addrbook and uses it if seeds are not provided
(assuming peers are started with pex enabled)
1. restart peer 1
local_testnet_1
local_testnet_1
starting tendermint peer ID=1
af1ed95319785f2a24896139bf4d750cc9782e3285d5114cf04e67b29c4bb05b
with the following addrbook:
{
        "Key": "9a8257adb4be92e57da5414b",
        "Addrs": [
                {
                        "Addr": {
                                "IP": "172.57.0.102",
                                "Port": 46656
                        },
                        "Src": {
                                "IP": "172.57.0.101",
                                "Port": 46656
                        },
                        "Attempts": 0,
                        "LastAttempt": "2017-01-16T14:50:42.949996907Z",
                        "LastSuccess": "0001-01-01T00:00:00Z",
                        "BucketType": 1,
                        "Buckets": [
                                194
                        ]
                },
                {
                        "Addr": {
                                "IP": "172.57.0.103",
                                "Port": 46656
                        },
                        "Src": {
                                "IP": "172.57.0.101",
                                "Port": 46656
                        },
                        "Attempts": 0,
                        "LastAttempt": "2017-01-16T14:50:42.951182011Z",
                        "LastSuccess": "0001-01-01T00:00:00Z",
                        "BucketType": 1,
                        "Buckets": [
                                240
                        ]
                },
                {
                        "Addr": {
                                "IP": "172.57.0.104",
                                "Port": 46656
                        },
                        "Src": {
                                "IP": "172.57.0.101",
                                "Port": 46656
                        },
                        "Attempts": 0,
                        "LastAttempt": "2017-01-16T14:50:42.951244649Z",
                        "LastSuccess": "0001-01-01T00:00:00Z",
                        "BucketType": 1,
                        "Buckets": [
                                95
                        ]
                }
        ]
}
starting test client container with CMD=test/p2p/pex/check_peer.sh 1 4
2. wait until peer 1 connects to other nodes using pex reactor
... peers count = , expected = 3
... peers count = 1, expected = 3
... peers count = 1, expected = 3
... peers count = 1, expected = 3
... peers count = 3, expected = 3
... successful

PASS
```

**Comment by ebuchman** [comment]
Nice tests. I'm not sure if adding seeds right away is good incase they're bung seeds. If we fail to connect, is the address eventually removed?

Also, I might be missing something, but my read on the problem was that if you start node1 by itself, and then start node2 with `--seeds node1`, and then kill and restart node1 (still without using --seeds), it would fail to connect back to node1. Can you replicate that? Is that maybe solved by the other go-p2p PR?

**Comment by melekes** [comment]
> If we fail to connect, is the address eventually removed?
yes
> Can you replicate that?
will try right away

**Comment by melekes** [comment]
@ebuchman can't replicate. added a test just in case.

**Comment by ebuchman** [comment]
Rebased and merged into https://github.com/tendermint/tendermint/tree/release-0.9.0 .

**Pull request closed without merging**
