### PR TITLE
mode: add devmode

### PR DESCRIPTION
**Pull request by marbar3778**
## Description

This pr creates a development mode. The development mode currently exposes broadcast_tx_commit (moved out of the production path) and indexes all transactions. 

closes https://github.com/tendermint/tendermint/issues/5721

### CODE REVIEW

**Comment by marbar3778** [comment]
Part of the issue mentioned is the ability to index all transactions in dev mode. In order to do this, I would need to either pass the config into the indexer or change the index tag on each event to true. Which is preferred? Both are a bit janky to me. 

cc @alexanderbez @tychoish @cmwaters

**Comment by alexanderbez** [comment]
Why does indexing transactions have anything to do with dev mode? I feel like that's a core feature and should exist in both IMHO.

**Comment by marbar3778** [comment]
> Why does indexing transactions have anything to do with dev mode? I feel like that's a core feature and should exist in both IMHO.

@ebuchman mentioned in a channel to override indexing to all true when in something like a dev mode. I can leave this to only being a commit mode.

**Comment by marbar3778** [comment]
gonna change this to rpc mode for debugging. Events is tricky and the app can say index everything easier than me passing config all the way down to the indexer

**Comment by marbar3778** [comment]
closing and will reopen with work for rpc mode

**Pull request closed without merging**
