### PR TITLE
.github: Split the issue template into two seperate templates

### PR DESCRIPTION
**Pull request by ValarDragon**
* [X] Updated all relevant documentation in docs
* [X] Updated all code comments where relevant
* [X] Wrote tests
* [X] Updated CHANGELOG.md - I don't think this change belongs in changelog

### CODE REVIEW

**Comment by melekes** [comment]
How's this gonna work? Will there be a drop down when I go to https://github.com/tendermint/tendermint/issues/new? I thought Github just reads ISSUE_TEMPLATE file if present and that's all https://blog.github.com/2016-02-17-issue-and-pull-request-templates/

**Comment by ValarDragon** [comment]
It'll work like whats on the SDK right now :D

**Comment by melekes** [comment]
awesome! thank you

**Comment by ValarDragon** [comment]
Basically you get a radio button (with a nice UI) asking you to select which of the issue template you want.

**Comment by melekes** [comment]
Looks like we have another RepeatTimer issue

```
--- FAIL: TestPEXReactorRunning (0.33s)
I[07-26|07:57:27.614] Address handler done                         pex=1
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x7de934]

goroutine 71 [running]:
testing.tRunner.func1(0xc420281770)
	/usr/local/go/src/testing/testing.go:742 +0x567
panic(0xb44f80, 0x105a940)
	/usr/local/go/src/runtime/panic.go:502 +0x24a
github.com/tendermint/tendermint/libs/common.(*RepeatTimer).Stop(0x0)
	/go/src/github.com/tendermint/tendermint/libs/common/repeat_timer.go:177 +0x34
github.com/tendermint/tendermint/p2p/conn.(*MConnection).OnStop(0xc4205e63c0)
	/go/src/github.com/tendermint/tendermint/p2p/conn/connection.go:207 +0x85
github.com/tendermint/tendermint/libs/common.(*BaseService).Stop(0xc4205e63c0, 0x1, 0xc4202ce000)
	/go/src/github.com/tendermint/tendermint/libs/common/service.go:152 +0x29c
github.com/tendermint/tendermint/p2p.(*peer).OnStop(0xc4205e6280)
	/go/src/github.com/tendermint/tendermint/p2p/peer.go:235 +0x59
github.com/tendermint/tendermint/libs/common.(*BaseService).Stop(0xc4205e6280, 0xa85bb3, 0xc4202aebd0)
	/go/src/github.com/tendermint/tendermint/libs/common/service.go:152 +0x29c
github.com/tendermint/tendermint/p2p.(*Switch).OnStop(0xc4201f31e0)
	/go/src/github.com/tendermint/tendermint/p2p/switch.go:219 +0x16c
github.com/tendermint/tendermint/libs/common.(*BaseService).Stop(0xc4201f31e0, 0x0, 0x0)
	/go/src/github.com/tendermint/tendermint/libs/common/service.go:152 +0x29c
github.com/tendermint/tendermint/p2p/pex.TestPEXReactorRunning(0xc420281770)
	/go/src/github.com/tendermint/tendermint/p2p/pex/pex_reactor_test.go:123 +0xa01
testing.tRunner(0xc420281770, 0xd1aec0)
	/usr/local/go/src/testing/testing.go:777 +0x16e
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:824 +0x565
FAIL	github.com/tendermint/tendermint/p2p/pex	0.803s
```

**Pull request merged**
