### PR TITLE
p2p: peermanager try dial next

### PR DESCRIPTION
**Pull request by tychoish**
This is an improvement on #8803 with the operative code more well
placed and with beter shutdown compatibility.

The core idea is: if we haven't dialed the maximum number of peers, avoid sleeping as much when we're trying to get an address.

### CODE REVIEW

**Comment by williambanfield** [comment]
I'm not certain I understand how this is an improvement. We'll only hit this case if we return from the `TryDialNext` call without any address to dial. But I'm not sure when that should actually happen. We seem to wake the `dialWaker` when we fail to dial or we drop a peer.

**Comment by tychoish** [comment]
> I'm not certain I understand how this is an improvement. We'll only hit this case if we return from the `TryDialNext` call without any address to dial. But I'm not sure when that should actually happen. We seem to wake the `dialWaker` when we fail to dial or we drop a peer.

There's this `dialWaker` mechanism which is basically a condition variable, (but implemented with channels, and in a way that looks more like a timer, but isn't) which means that `DialNext` calls can (potentially) block forever if the waker never wakes up (which would happen if there are no new peers added, nor no Dialing operation reaches `DialFailed` as is the case if we're at maxpeers or we attempt to connect to a peer that we're already connected to). 

The change that I merged this morning coupled the extra wakeup to the dialsleep method, but I'm proposing that we just try and look for a new peers to dial in a tighter loop while we have less than the max-number of outgoing connections.

**Comment by williambanfield** [comment]
I'm not sure I see which case of 'having a possible peer to dial' and 'having below the max outgoing threshold' can occur where we don't call the dial waker. We call it when a peer [disconnects](https://github.com/tendermint/tendermint/blob/83526cacbcd998b33d2669088a688c7e492da8ff/internal/p2p/peermanager.go#L895) and we call it after the[ retry-dial timer expires](https://github.com/tendermint/tendermint/blob/83526cacbcd998b33d2669088a688c7e492da8ff/internal/p2p/peermanager.go#L642). Given this combination of wakes, I'm not sure I see the combination that should lead to use not waking it again.

**Comment by tychoish** [comment]
> I'm not sure I see which case of 'having a possible peer to dial' and 'having below the max outgoing threshold' can occur where we don't call the dial waker. We call it when a peer [disconnects](https://github.com/tendermint/tendermint/blob/83526cacbcd998b33d2669088a688c7e492da8ff/internal/p2p/peermanager.go#L895) and we call it after the[ retry-dial timer expires](https://github.com/tendermint/tendermint/blob/83526cacbcd998b33d2669088a688c7e492da8ff/internal/p2p/peermanager.go#L642). Given this combination of wakes, I'm not sure I see the combination that should lead to use not waking it again.

I think there are a couple of situations:
- we recieve multiple wake events at once, and because of the non-blocking send into the wake channel, we end up missing wake events. Because we _can_ miss wake events and each wake event means we will attempt to dial one peer, we will eventually try to dial fewer and fewer peers.
- there is a case where a peer dials us as we attempt to dial them, and their handshakes race: in this case we don't send a wake event and we end up with an empty outgoing peer slot. 

Following startup, particularly of new nodes, we see many wake events for every new peer that's added to the peer store, even "bad" peers, which will cause us  to dial often. 

One of the mistakes that's easy to make (and I think I've fallen into this trap a bunch) is that if you look at the code, it seems like the dialing processes of dialing is controled by the router because, the router is the thing that dials peers and gets connections, but actually the effect of the DialNext/TryDialNext implementation is that the peer manager *pushes* peers to the router to dial, and the "dial sleep" that we've done in the past is probably mostly impactful at the beginning of a processes lifecycle and after a while the peer manager is really the thing that drives the process.

**Review by creachadair — APPROVED** [review]

**Comment by cmwaters** [comment]
I agree with William here. If there are no peers to return we shouldn't continue to needlessly call `DialNext`. I actually wrote up my comment in the other PR: https://github.com/tendermint/tendermint/pull/8803#issuecomment-1161378036. 

If we call `Wake` multiple times after each other that's fine. It means there's more than one peer available to `Dial` and we're not going to sleep until all those peers are exhausted

**Comment by tychoish** [comment]
> If we call `Wake` multiple times after each other that's fine. It means there's more than one peer available to `Dial` and we're not going to sleep until all those peers are exhausted

I think this is not correct. If we call wake multiple times, and we don't dial between them (e.g. the wake events are dropped) , then nothing wakes up the dialing thread(s) and we will not dial peers, and we will shed peers over time.

**Comment by tychoish** [comment]
> Is it possible that after restarts, the peers that were formerly perceived as "good" are ranked lower than they should be? (I thought we'd persist the score, but maybe not?)

I think this is definitely true, and we should fix this in a different PR. At the same time, the problem that we're seeing is that *we* (not restarting) aren't dialing new peers, and that the other peer that are restarting *aren't* dialing us. So I don't think that's a full fix (and actually I worry that writing more state could make it so that restarting will clear things up less effectively.)

**Comment by creachadair** [comment]
> I think this is definitely true, and we should fix this in a different PR. At the same time, the problem that we're seeing is that _we_ (not restarting) aren't dialing new peers, and that the other peer that are restarting _aren't_ dialing us. So I don't think that's a full fix (and actually I worry that writing more state could make it so that restarting will clear things up less effectively.)

Yeah, I don't think that needs to block this PR necessarily, I was just trying to find a model to explain how we might tail off after node restarts.

**Comment by williambanfield** [comment]
> we (not restarting) aren't dialing new peers, and that the other peer that are restarting aren't dialing us.

These are both true, but I don't think that this PR fixes the issue. I ran exactly this code in the celestia net and continued to see the tapering off of peers and us cease to dial so I don't think that this is really the issue. I think that, when you wake, you only need to wake once so that you can start to act on the updated set of peers.

**Comment by tychoish** [comment]
> Yeah, I don't think that needs to block this PR necessarily, I was just trying to find a model to explain how we might tail off after node restarts.

Totally, (and not to belabor this point,) but the node doing the disconnecting is the other nodes, not this node. 

> I think that, when you wake, you only need to wake once so that you can start to act on the updated set of peers.

Waking only lets you act on *one* peer, not the set of peers.

**Comment by williambanfield** [comment]
> Waking only lets you act on one peer, not the set of peers.

When the `DialNext` loop gets a peer from `TryDialNext`, it returns before `Sleep` is ever called. Once the first wake occurs, it will dial every available peer because we will never hit the `Sleep` case again until we have no peers left to dial. 

https://github.com/tendermint/tendermint/blob/28d323995891080484617c076649b63a504c5bf4/internal/p2p/peermanager.go#L518

**Pull request closed without merging**
