### PR TITLE
DO NOT MERGE: use latest release of tm-db

### PR DESCRIPTION
**Pull request by faddat**
* upgrades to tm-db v0.6.7
* tm-db v0.6.7 depends on cosmos/gorocksdb
  * rocksdb won't work without it on cosmos chains (don't know about if using only tendermint)

Further, there's this:

https://github.com/tendermint/tm-db/pull/236

That'll move from the gorocksdb library to grocksdb, which is maintained.

Then, there's benchmarks and pebbledb. 

I have a hunch that although someone told me that there's a freeze on tm-db, unless we are going to retire that code, we've got to maintain it.  

* goleveldb doesn't seem to be fully tweaked but is used as default everywhere
* in tm-db v0.6.6, rocksdb doesn't work in most cases, and it's not optimized

You may be wondering:  why is jacob so concerned with db performance?

Basically it is our relayers.  Rocks yeilded a huge impact on their performance, but for some scenarios rocks isn't very good/desirable, mainly because of cgo.  

PebbleDB, from cockroachdb:

* preforms as well as or better than rocks
* no cgo
* actively maintained

If we flip this around-- 

Goleveldb, from an individual:

* isn't actively maintained
* needs further tweaks and configuration in tm-db

### CODE REVIEW

**Comment by faddat** [comment]
Let's put something enlightening in the ci history

**Comment by creachadair** [comment]
https://github.com/tendermint/tendermint/issues/8014 has some relevant context also.

> For the e2e test-- where does its build env come from?

https://github.com/tendermint/tendermint/blob/master/test/e2e/docker/Dockerfile#L7

> These mean that the build env doesn't have the right version of rocks. Why can't we settle on using the latest versions of all the things?

I think it's largely down to the availability of convenient packages. From Tendermint's perspective, RocksDB is an experimental backend. But the Cosmos SDK has its own custom fork of the Go wrapper library, which is very sensitive to specific versions of the underlying C library.

**Comment by faddat** [comment]
Survey:

Are any developers working on tendermint not using Go 1.18?

eg if on your computer you do 

```
go version
go version go1.18.1 darwin/arm64
```

**Comment by tychoish** [comment]
(sorry if I bungled a comment) 

> Are any developers working on tendermint not using Go 1.18?

I actually think this is the wrong question to ask, but rather "are there downstream users of tendermint that haven't upgraded?" The SDK has, but I think it's ok and correct to not be the package that forces downstream users to upgrade before they're ready.

**Comment by faddat** [comment]
@tychoish this is more about the build environment, probably the little taggy things in go.mod are more moot

**Comment by faddat** [comment]
> (sorry if I bungled a comment)

hey, not too sure what you're referring to here I think the e2e stuff is amazing

**Comment by tychoish** [comment]
> @tychoish this is more about the build environment, probably the little taggy things in go.mod are more moot

If we're not upgrading the go.mod version we shouldn't upgrade the dev environment, just to avoid breaking the compatibility promise. 

Similarly, it seems like this patch installs `gccgo` which should definitely not be installed (though having `gcc` seems potentially fine, though I'm not excited about it.

**Comment by creachadair** [comment]
> I think we absolutely shouldn't be using the cosmos fork.

I generally agree, but Cosmos is the primary consumer of RocksDB via tm-db, and it is not clear how to find and fix all the downstream consumers of that dependency. 

For the consensus node itself our plan is to stop using tm-db anyway, at which point it will no longer cause build problems here. For maintenance in the interim, I'm disinclined to break existing use without a pretty good reason, even if it's objectively "better" to use a new thing.

**Comment by faddat** [comment]
Can assure you:

no one uses rocks currently, and part of the reason is that lib

**Comment by creachadair** [comment]
> Can assure you:
> 
> no one uses rocks currently, and part of the reason is that lib

If it is really true that no one uses RocksDB via tm-db, then I think we have a better solution: Rather than extending tm-db to support it better, we should remove it.

It seems there is some general interest in experimenting with RocksDB, which is fine. I think rather than merging experimental code into the release of tm-db, however, a better approach is to fork tm-db and do the experiments there. Having actual usage to guide compatibility decisions is preferable to releasing changes "on spec' to test whether they _might_ address some user need.

As a practical matter, unless an application already depends on tm-db (e.g., via the SDK), this is not the right way to integrate with a database backend. The wrapper library provides no real value apart from the ability to swap backends around. For an application that is performance sensitive, a better solution is to call its backend of choice directly.

And if, on the other hand, the SDK _is_ involved, then we need to make sure compatibility issues are fixed there first.

**Comment by faddat** [comment]
@creachadair you and I are on the same page

**Comment by faddat** [comment]
PS:  I do think this should eventually be merged, after this:

https://github.com/tendermint/tm-db/pull/236

**Comment by williambanfield** [comment]
> rocksdb won't work without it on cosmos chains

Would someone mind clarifying why this is the case?

**Comment by tychoish** [comment]
> my opinion on the matter is to improve sync speed and to improve query perf, and I've been pursuing that via databases.

Databases might be the right answer, and there definitely seems to be a meme of blaming performance on databases, but I think there are a few things to consider:

- What queries are the slow ones? People point at slow queries but it's really hard to see what part of which queries are slow. The database is definitely at the bottom of this call stack so making it a touch faster might have a lot of impact, but the inefficient code (vis a vis database access is almost certainly in the application (SDK) or in the way that tendermint processes data, or in artifacts of access patterns. Some of this is known (e.g. IAVL), and some could use more exploration.
- All of the major chains in question (terra, osmosis, gaia, etc.) are using really old versions of all of the software, (particularly of tendermint), so there's not too much that we can do in the short term that we *can* do. Support chains and do work that will support them using newer versions of the SDK (e.g. with IAVL optimizations or SMT,) as well as the upgrade path to get us there. 
- I think, but am not sure, that the relayer implementations do a lot of subscriptions using tendermint's event system (and possibly depend on the indexer,) and my instinct is that this is always the bottleneck. There'll be a lot of improvements in this area in the 0.36 release, but adoption is definitely harder. 

It's also the case that you could run the nodes that support the relayer on builds using custom components (e.g. dbs/etc.) while we wait for the optimizations to be upstreamed.

**Comment by faddat** [comment]
> Would someone mind clarifying why this is the case?

Happily!

So, before v0.6.7 cosmos chains were all using tecbot/gorocksdb but somewhere in the stack we began to use some features found only in newer rocks, and these were added to cosmos/gorocksdb.

So in order to use rocks in cosmos, v0.6.7 or a replace statement like:

```go
replace github.com/tecbot/gorocksdb => github.com/cosmos/gorocksdb version
```

Is needed.  I've never succeeded with rocks without something like that so you can find that line or another version thereof-- or an import of tm-db v0.6.7 all over cosmos.  

But tecbot/gorocksdb is completely unmaintained, and cosmos/gorocksdb is the teeniest tweak on top of an obsolete wrapper.

grocksdb and gorocksdb do the same thing, but are different codebases and only one of them has any maitenance.

It's also fine to drop rocks support, and cleveldb support.  They both use cgo and in the end it makes for conversations like these, with little clear benefit over Pebble / Badger

**Comment by faddat** [comment]
thank you for all that information @tychoish -- the decisionmaking seems sound and I'll toy with badger some.

I'm also explicitly super-okay with dropping other databases-- especially cgo db's.

I will mark this as a draft because I am working on some container stuff for the sdk, which would make this much nicer.  

thanks to everyone for reviewing.

**Comment by creachadair** [comment]
Just to clarify: When we do swap databases for the internals of the consensus node, we plan to also drop our dependency of Tendermint core on tm-db. We aren't getting rid of the library: Apps that want to use it should still be able to. 

In the interim, though, I'd like to minimize disruption of existing uses of this package, unless there are specific problems that need fixing (bugs, security vulnerabilities, etc.). 

I don't know what the future of tm-db should be. I suspect many performance issues network operators have reported around application storage may be easier to solve by moving away from this highly generic wrapper interface—it hides key performance tools different backends provide around caching, concurrency control, and synchronization. But that is a larger set of design questions and I don't know enough to propose a general solution.

**Comment by faddat** [comment]
@creachadair @tychoish 

I think that I agree with the notion that it makes the most sense to try and go really fast with one database, and that we are missing opportunities by supporting all databases.

**Pull request closed without merging**
