### PR TITLE
light: fix `/commit` and `/validators` rpc calls

### PR DESCRIPTION
**Pull request by cmwaters**
backports: #6026

### CODE REVIEW

**Review by marbar3778 — APPROVED** [review]

**Comment by tessr** [comment]
Does this change the API response? (i.e., is it breaking?)

**Comment by cmwaters** [comment]
Hmm you're right. Technically it is breaking. The RPC itself is unchanged but I added a function to this `LightClient` interface which I guess could be implemented by some user :disappointed:. 

I'm not too sure why this interface is public? My only explanation could be if someone was producing their own tendermint flavoured light client and they wanted to use tendermint RPC.

I guess I can come up with some temporary work around for now or we just make our users wait till 0.35

**Comment by melekes** [comment]
I would not consider this "breaking" as it only breaks API that normally you should not use.

**Comment by tessr** [comment]
If this only breaks a Go API, it's fine to consider it non-breaking.

**Pull request merged**
