### PR TITLE
Merge in ABCI and TMLIBS re #1309

### PR DESCRIPTION
**Pull request by ebuchman**
Follows the process from https://github.com/tendermint/tendermint/issues/1309#issuecomment-398655706 to merge in abci and tmlibs

### CODE REVIEW

**Comment by ebuchman** [comment]
Need to bring in go-crypto so we only have one version of the libs ...

go-crypto still has some open PRs though that should get merged through first

**Comment by Liamsi** [comment]
> go-crypto still has some open PRs though that should get merged through first

No open PR in go-crypto anymore.

**Comment by xla** [comment]
Replacing this PR in steps, strarting off with abci in #1790

**Pull request closed without merging**
