### PR TITLE
.golangci: set locale to US for misspell linter

### PR DESCRIPTION
**Pull request by tessr**
Partially addresses #6030

### CODE REVIEW

**Comment by alexanderbez** [comment]
Let's push this over the finish line?

**Comment by tessr** [comment]
Yep, will do

**Comment by tessr** [comment]
No longer WIP; this is R4R

**Review by alexanderbez — APPROVED** [review]

**Comment by marbar3778** [comment]
For future reference a go file needs to be modified in order to run the linter. This passed because it didn't run.

**Comment by tessr** [comment]
So I squashed the change out, but when I opened the PR I made a change to a go file (complete with misspelling!) to make sure it was working. And it was! But it didn't complain about any of the other files.

**Pull request merged**
