### PR TITLE
fix same tx appears in two different blocks

### PR DESCRIPTION
**Pull request by xiangjianmeng**
Please add a description of the changes that this PR introduces and the files that
are the most critical to review.

If this PR fixes an open Issue, please include "Closes #XXX" (where "XXX" is the Issue number) 
so that GitHub will automatically close the Issue when this PR is merged.

Close https://github.com/tendermint/tendermint/issues/6219

### CODE REVIEW

**Comment by alexanderbez** [comment]
I do not understand why we need a mutex for this? Are `CheckTx` executions concurrent @melekes?

**Comment by melekes** [comment]
I don't think wrapping CheckTxAsync call in a mutex is a correct solution to the problem at hand.

**Comment by melekes** [comment]
> I do not understand why we need a mutex for this? Are `CheckTx` executions concurrent @melekes?

They could be, but no (see https://github.com/tendermint/tendermint/discussions/6171)

**Comment by melekes** [comment]
> What would you advise as the correct solution @melekes?

I don't know what the root cause yet, so not sure.

**Pull request closed without merging**
