### PR TITLE
Pin actions to a full length commit SHA

### PR DESCRIPTION
**Pull request by naveensrinivasan**
- Pinned actions by SHA https://github.com/ossf/scorecard/blob/main/docs/checks.md#pinned-dependencies
- Included permissions for the action. https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions

>Pin actions to a full length commit SHA

>Pinning an action to a full length commit SHA is currently the only way to use an action as an immutable release. Pinning to a particular SHA helps mitigate the risk of a bad actor adding a backdoor to the action's repository, as they would need to generate a SHA-1 collision for a valid Git object payload.

https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-third-party-actions

Also, dependabot supports upgrading based on SHA.

Signed-off-by: naveensrinivasan <172697+naveensrinivasan@users.noreply.github.com>

### CODE REVIEW

**Comment by thanethomson** [comment]
This approach, to me, seems to assume that we would also adopt the following practices regarding GitHub Actions:

1. Watching all actions for new releases
2. Reviewing the code of every action upon release
3. Having to manually update action dependencies' hashes upon new releases

It's not clear to me whether this is really worth the effort.

**Comment by naveensrinivasan** [comment]
The goal is to automate it with dependabot.

**Comment by naveensrinivasan** [comment]
> This approach, to me, seems to assume that we would also adopt the following practices regarding GitHub Actions:
> 
> 1. Watching all actions for new releases
> 2. Reviewing the code of every action upon release
> 3. Having to manually update action dependencies' hashes upon new releases
> 
> It's not clear to me whether this is really worth the effort.

This should be able to upgrade deps by SHA https://github.com/tendermint/tendermint/blob/99f9ee0f63627462e4daa3e785ec23086aa3a0b5/.github/dependabot.yml#L3

**Comment by thanethomson** [comment]
> The goal is to automate it with dependabot.

I still don't understand the benefit here. Dependabot won't do any in-depth security reviews of the GitHub Actions before it upgrades, will it? If not, why bother to pin the GitHub Actions to specific checksums?

**Pull request closed without merging**
