### PR TITLE
crypto: adopt zip215 ed25519 verification 

### PR DESCRIPTION
**Pull request by marbar3778**
## Description

- use std library ed25519 (https://golang.org/doc/go1.13#crypto/ed25519)
- use zip215 for key verification of ed25519 keys

Closes: #5596

### CODE REVIEW

**Review by alexanderbez — APPROVED** [review]
ACK. Is it consensus or state breaking to backport this?

**Review by melekes — APPROVED** [review]
👍

**Comment by marbar3778** [comment]
> Is it consensus or state breaking to backport this?

It is technically not a breaking change but it can cause issues if some validators don't correctly generate their keys so we decided to do this as a major breaking change.

**Comment by hxrts** [comment]
Heads up [ZIP216](https://github.com/zcash/zips/issues/400) fixes an issue with non-canonical encoding. Short discussion on Discord [here](https://discord.com/channels/676527656170160146/676528086061416472/771448612902273044).

**Comment by hdevalence** [comment]
@hxrts those points are explicitly and intentionally allowed by ZIP215; there's not an issue to fix.

**Pull request merged**
