### PR TITLE
Validator set changes tests

### PR DESCRIPTION
**Pull request by akalyaev**
This is **failing** right now, so please do not merge!

Sometimes this test is failing with: "Timed out waiting for all validators to commit a block" (timeout was increased by 10 seconds)

Log:
```
INFO[12-23|13:02:46] Block{
  Header{
    ChainID:        tendermint_test
    Height:         11
    Time:           2016-12-23 13:02:46.052 +0000 UTC
    NumTxs:         2
    LastBlockID:    B52A7701AAFAB980B44D3C7415972FEEC8F7D942:1:E647A8FA90EA
    LastCommit:     83F202126FBA458507F7E200DCCEE7E62E4474DD
    Data:           36721760CD4AA23A7B6B5F7C5515026379272DD2
    Validators:     281D550ECD5DA99E4ADD9FE411299F6EB46B523B
    App:            65B64A51FF9F58D823C23CF034E24291FCEDD2BA
  }#75860B411898B6A27AA40C726DE119A070F40B5B
  Data{
    Tx:[118 97 108 58 48 49 51 51 68 68 55 66 48 51 54 49 70 50 69 53 65 70 65 53 52 53 52 65 50 52 56 51 55 52 68 56 57 69 53 51 49 70 53 67 54 68 52 53 70 67 66 70 65 66 52 68 67 50 67 57 51 65 53 70 50 70 67 53 70 57 47 49 48]
    Tx:[118 97 108 58 48 49 51 53 66 53 67 53 65 70 55 48 65 48 57 54 50 69 55 56 67 56 48 68 65 48 56 48 51 49 55 50 48 55 48 50 57 68 57 68 49 65 70 57 51 66 49 51 56 48 68 56 55 69 49 48 51 65 69 52 53 53 53 49 54 66 47 49 48]
  }#36721760CD4AA23A7B6B5F7C5515026379272DD2
  Commit{
    BlockID:    B52A7701AAFAB980B44D3C7415972FEEC8F7D942:1:E647A8FA90EA
    Precommits: Vote{0:2E957CF919E5 10/00/2(Precommit) B52A7701AAFA /41960BB76AFD.../}
    Vote{1:4F6BE1A4BB35 10/00/2(Precommit) B52A7701AAFA /4D2CAD15F4F1.../}
    Vote{2:531D483CB987 10/00/2(Precommit) B52A7701AAFA /F96C0ACD5514.../}
    Vote{3:C25E810EEBF0 10/00/2(Precommit) B52A7701AAFA /E88B7FCC6533.../}
    Vote{4:DFD0788E654F 10/00/2(Precommit) B52A7701AAFA /E651F413BF54.../}
  }#83F202126FBA458507F7E200DCCEE7E62E4474DD
}#75860B411898B6A27AA40C726DE119A070F40B5B module=consensus
INFO[12-23|13:02:46] Added to precommit                       module=consensus vote="Vote{1:4F6BE1A4BB35 11/00/2(Precommit) 75860B411898 /C78B5D6BAC4A.../}" precommits="VoteSet{H:11 R:0 T:2 +2/3:75860B411898B6A27AA40C726DE119A070F40B5B:1:F3BA2DCA105E BA{5:_X_XX} map[]}"
INFO[12-23|13:02:46] enterCommit(11/0). Current: 11/0/RoundStepPrecommit module=consensus
NOTE[12-23|13:02:46] Finalizing commit of block with 2 txs    module=consensus height=11 hash=75860B411898B6A27AA40C726DE119A070F40B5B root=65B64A51FF9F58D823C23CF034E24291FCEDD2BA
INFO[12-23|13:02:46] Block{
  Header{
    ChainID:        tendermint_test
    Height:         11
    Time:           2016-12-23 13:02:46.052 +0000 UTC
    NumTxs:         2
    LastBlockID:    B52A7701AAFAB980B44D3C7415972FEEC8F7D942:1:E647A8FA90EA
    LastCommit:     83F202126FBA458507F7E200DCCEE7E62E4474DD
    Data:           36721760CD4AA23A7B6B5F7C5515026379272DD2
    Validators:     281D550ECD5DA99E4ADD9FE411299F6EB46B523B
    App:            65B64A51FF9F58D823C23CF034E24291FCEDD2BA
  }#75860B411898B6A27AA40C726DE119A070F40B5B
  Data{
    Tx:[118 97 108 58 48 49 51 51 68 68 55 66 48 51 54 49 70 50 69 53 65 70 65 53 52 53 52 65 50 52 56 51 55 52 68 56 57 69 53 51 49 70 53 67 54 68 52 53 70 67 66 70 65 66 52 68 67 50 67 57 51 65 53 70 50 70 67 53 70 57 47 49 48]
    Tx:[118 97 108 58 48 49 51 53 66 53 67 53 65 70 55 48 65 48 57 54 50 69 55 56 67 56 48 68 65 48 56 48 51 49 55 50 48 55 48 50 57 68 57 68 49 65 70 57 51 66 49 51 56 48 68 56 55 69 49 48 51 65 69 52 53 53 53 49 54 66 47 49 48]
  }#36721760CD4AA23A7B6B5F7C5515026379272DD2
  Commit{
    BlockID:    B52A7701AAFAB980B44D3C7415972FEEC8F7D942:1:E647A8FA90EA
    Precommits: Vote{0:2E957CF919E5 10/00/2(Precommit) B52A7701AAFA /41960BB76AFD.../}
    Vote{1:4F6BE1A4BB35 10/00/2(Precommit) B52A7701AAFA /4D2CAD15F4F1.../}
    Vote{2:531D483CB987 10/00/2(Precommit) B52A7701AAFA /F96C0ACD5514.../}
    Vote{3:C25E810EEBF0 10/00/2(Precommit) B52A7701AAFA /E88B7FCC6533.../}
    Vote{4:DFD0788E654F 10/00/2(Precommit) B52A7701AAFA /E651F413BF54.../}
  }#83F202126FBA458507F7E200DCCEE7E62E4474DD
}#75860B411898B6A27AA40C726DE119A070F40B5B module=consensus
INFO[12-23|13:02:46] Executed block                           module=stateheight=11 valid txs=2 invalid txs=0
INFO[12-23|13:02:46] Update to validator set                  module=stateupdates="[{\"pub_key\":\"0133DD7B0361F2E5AFA5454A248374D89E531F5C6D45FCBFAB4DC2C93A5F2FC5F9\",\"power\":10},{\"pub_key\":\"0135B5C5AF70A0962E78C80DA080317207029D9D1AF93B1380D87E103AE455516B\",\"power\":10}]"
INFO[12-23|13:02:46] Saved state                              module=dummyroot=2719616B7C2585E000F5DFF1E2549061C5ED8AF1
NOTE[12-23|13:02:46] Saving block                             module=dummyheight=11 root=2719616B7C2585E000F5DFF1E2549061C5ED8AF1
INFO[12-23|13:02:46] Recheck txs                              module=mempool numtxs=0
INFO[12-23|13:02:46] Got block                                module=consensus height=11 validator=5
INFO[12-23|13:02:46] Added to precommit                       module=consensus vote="Vote{1:4F6BE1A4BB35 11/00/2(Precommit) 75860B411898 /C78B5D6BAC4A.../}" precommits="VoteSet{H:11 R:0 T:2 +2/3:75860B411898B6A27AA40C726DE119A070F40B5B:1:F3BA2DCA105E BA{5:_X_XX} map[]}"
INFO[12-23|13:02:46] enterCommit(11/0). Current: 11/0/RoundStepPrecommit module=consensus
NOTE[12-23|13:02:46] Finalizing commit of block with 2 txs    module=consensus height=11 hash=75860B411898B6A27AA40C726DE119A070F40B5B root=65B64A51FF9F58D823C23CF034E24291FCEDD2BA
INFO[12-23|13:02:46] Block{
  Header{
    ChainID:        tendermint_test
    Height:         11
    Time:           2016-12-23 13:02:46.052 +0000 UTC
    NumTxs:         2
    LastBlockID:    B52A7701AAFAB980B44D3C7415972FEEC8F7D942:1:E647A8FA90EA
    LastCommit:     83F202126FBA458507F7E200DCCEE7E62E4474DD
    Data:           36721760CD4AA23A7B6B5F7C5515026379272DD2
    Validators:     281D550ECD5DA99E4ADD9FE411299F6EB46B523B
    App:            65B64A51FF9F58D823C23CF034E24291FCEDD2BA
  }#75860B411898B6A27AA40C726DE119A070F40B5B
  Data{
    Tx:[118 97 108 58 48 49 51 51 68 68 55 66 48 51 54 49 70 50 69 53 65 70 65 53 52 53 52 65 50 52 56 51 55 52 68 56 57 69 53 51 49 70 53 67 54 68 52 53 70 67 66 70 65 66 52 68 67 50 67 57 51 65 53 70 50 70 67 53 70 57 47 49 48]
    Tx:[118 97 108 58 48 49 51 53 66 53 67 53 65 70 55 48 65 48 57 54 50 69 55 56 67 56 48 68 65 48 56 48 51 49 55 50 48 55 48 50 57 68 57 68 49 65 70 57 51 66 49 51 56 48 68 56 55 69 49 48 51 65 69 52 53 53 53 49 54 66 47 49 48]
  }#36721760CD4AA23A7B6B5F7C5515026379272DD2
  Commit{
    BlockID:    B52A7701AAFAB980B44D3C7415972FEEC8F7D942:1:E647A8FA90EA
    Precommits: Vote{0:2E957CF919E5 10/00/2(Precommit) B52A7701AAFA /41960BB76AFD.../}
    Vote{1:4F6BE1A4BB35 10/00/2(Precommit) B52A7701AAFA /4D2CAD15F4F1.../}
    Vote{2:531D483CB987 10/00/2(Precommit) B52A7701AAFA /F96C0ACD5514.../}
    Vote{3:C25E810EEBF0 10/00/2(Precommit) B52A7701AAFA /E88B7FCC6533.../}
    Vote{4:DFD0788E654F 10/00/2(Precommit) B52A7701AAFA /E651F413BF54.../}
  }#83F202126FBA458507F7E200DCCEE7E62E4474DD
}#75860B411898B6A27AA40C726DE119A070F40B5B module=consensus
INFO[12-23|13:02:46] Executed block                           module=stateheight=11 valid txs=2 invalid txs=0
INFO[12-23|13:02:46] Update to validator set                  module=stateupdates="[{\"pub_key\":\"0133DD7B0361F2E5AFA5454A248374D89E531F5C6D45FCBFAB4DC2C93A5F2FC5F9\",\"power\":10},{\"pub_key\":\"0135B5C5AF70A0962E78C80DA080317207029D9D1AF93B1380D87E103AE455516B\",\"power\":10}]"
INFO[12-23|13:02:46] Saved state                              module=dummyroot=2719616B7C2585E000F5DFF1E2549061C5ED8AF1
NOTE[12-23|13:02:46] Saving block                             module=dummyheight=11 root=2719616B7C2585E000F5DFF1E2549061C5ED8AF1
INFO[12-23|13:02:46] Recheck txs                              module=mempool numtxs=0
INFO[12-23|13:02:46] Got block                                module=consensus height=11 validator=6
INFO[12-23|13:02:46] Executed block                           module=stateheight=11 valid txs=2 invalid txs=0
INFO[12-23|13:02:46] Update to validator set                  module=stateupdates="[{\"pub_key\":\"0133DD7B0361F2E5AFA5454A248374D89E531F5C6D45FCBFAB4DC2C93A5F2FC5F9\",\"power\":10},{\"pub_key\":\"0135B5C5AF70A0962E78C80DA080317207029D9D1AF93B1380D87E103AE455516B\",\"power\":10}]"
INFO[12-23|13:02:46] Saved state                              module=dummyroot=2719616B7C2585E000F5DFF1E2549061C5ED8AF1
NOTE[12-23|13:02:46] Saving block                             module=dummyheight=11 root=2719616B7C2585E000F5DFF1E2549061C5ED8AF1
INFO[12-23|13:02:46] Recheck txs                              module=mempool numtxs=0
INFO[12-23|13:02:46] Got block                                module=consensus height=11 validator=3
INFO[12-23|13:02:46] Added to precommit                       module=consensus vote="Vote{3:C25E810EEBF0 11/00/2(Precommit) 75860B411898 /EA98401DCAF6.../}" precommits="VoteSet{H:11 R:0 T:2 +2/3:<nil> BA{5:__XXX} map[]}"
INFO[12-23|13:02:46] Added to precommit                       module=consensus vote="Vote{1:4F6BE1A4BB35 11/00/2(Precommit) 75860B411898 /C78B5D6BAC4A.../}" precommits="VoteSet{H:11 R:0 T:2 +2/3:75860B411898B6A27AA40C726DE119A070F40B5B:1:F3BA2DCA105E BA{5:_XXXX} map[]}"
INFO[12-23|13:02:46] enterCommit(11/0). Current: 11/0/RoundStepPrecommit module=consensus
NOTE[12-23|13:02:46] Finalizing commit of block with 2 txs    module=consensus height=11 hash=75860B411898B6A27AA40C726DE119A070F40B5B root=65B64A51FF9F58D823C23CF034E24291FCEDD2BA
INFO[12-23|13:02:46] Block{
  Header{
    ChainID:        tendermint_test
    Height:         11
    Time:           2016-12-23 13:02:46.052 +0000 UTC
    NumTxs:         2
    LastBlockID:    B52A7701AAFAB980B44D3C7415972FEEC8F7D942:1:E647A8FA90EA
    LastCommit:     83F202126FBA458507F7E200DCCEE7E62E4474DD
    Data:           36721760CD4AA23A7B6B5F7C5515026379272DD2
    Validators:     281D550ECD5DA99E4ADD9FE411299F6EB46B523B
    App:            65B64A51FF9F58D823C23CF034E24291FCEDD2BA
  }#75860B411898B6A27AA40C726DE119A070F40B5B
  Data{
    Tx:[118 97 108 58 48 49 51 51 68 68 55 66 48 51 54 49 70 50 69 53 65 70 65 53 52 53 52 65 50 52 56 51 55 52 68 56 57 69 53 51 49 70 53 67 54 68 52 53 70 67 66 70 65 66 52 68 67 50 67 57 51 65 53 70 50 70 67 53 70 57 47 49 48]
    Tx:[118 97 108 58 48 49 51 53 66 53 67 53 65 70 55 48 65 48 57 54 50 69 55 56 67 56 48 68 65 48 56 48 51 49 55 50 48 55 48 50 57 68 57 68 49 65 70 57 51 66 49 51 56 48 68 56 55 69 49 48 51 65 69 52 53 53 53 49 54 66 47 49 48]
  }#36721760CD4AA23A7B6B5F7C5515026379272DD2
  Commit{
    BlockID:    B52A7701AAFAB980B44D3C7415972FEEC8F7D942:1:E647A8FA90EA
    Precommits: Vote{0:2E957CF919E5 10/00/2(Precommit) B52A7701AAFA /41960BB76AFD.../}
    Vote{1:4F6BE1A4BB35 10/00/2(Precommit) B52A7701AAFA /4D2CAD15F4F1.../}
    Vote{2:531D483CB987 10/00/2(Precommit) B52A7701AAFA /F96C0ACD5514.../}
    Vote{3:C25E810EEBF0 10/00/2(Precommit) B52A7701AAFA /E88B7FCC6533.../}
    Vote{4:DFD0788E654F 10/00/2(Precommit) B52A7701AAFA /E651F413BF54.../}
  }#83F202126FBA458507F7E200DCCEE7E62E4474DD
}#75860B411898B6A27AA40C726DE119A070F40B5B module=consensus
INFO[12-23|13:02:46] Executed block                           module=stateheight=11 valid txs=2 invalid txs=0
INFO[12-23|13:02:46] Update to validator set                  module=stateupdates="[{\"pub_key\":\"0133DD7B0361F2E5AFA5454A248374D89E531F5C6D45FCBFAB4DC2C93A5F2FC5F9\",\"power\":10},{\"pub_key\":\"0135B5C5AF70A0962E78C80DA080317207029D9D1AF93B1380D87E103AE455516B\",\"power\":10}]"
INFO[12-23|13:02:46] Saved state                              module=dummyroot=2719616B7C2585E000F5DFF1E2549061C5ED8AF1
NOTE[12-23|13:02:46] Saving block                             module=dummyheight=11 root=2719616B7C2585E000F5DFF1E2549061C5ED8AF1
INFO[12-23|13:02:46] Recheck txs                              module=mempool numtxs=0
INFO[12-23|13:02:46] Got block                                module=consensus height=11 validator=1
INFO[12-23|13:02:46] Added to precommit                       module=consensus vote="Vote{0:2E957CF919E5 11/00/2(Precommit) 75860B411898 /B1D715AFA354.../}" precommits="VoteSet{H:11 R:0 T:2 +2/3:<nil> BA{5:X_XXX} map[]}"
INFO[12-23|13:02:46] Added to precommit                       module=consensus vote="Vote{1:4F6BE1A4BB35 11/00/2(Precommit) 75860B411898 /C78B5D6BAC4A.../}" precommits="VoteSet{H:11 R:0 T:2 +2/3:75860B411898B6A27AA40C726DE119A070F40B5B:1:F3BA2DCA105E BA{5:XXXXX} map[]}"
INFO[12-23|13:02:46] enterCommit(11/0). Current: 11/0/RoundStepPrecommit module=consensus
NOTE[12-23|13:02:46] Finalizing commit of block with 2 txs    module=consensus height=11 hash=75860B411898B6A27AA40C726DE119A070F40B5B root=65B64A51FF9F58D823C23CF034E24291FCEDD2BA
INFO[12-23|13:02:46] Block{
  Header{
    ChainID:        tendermint_test
    Height:         11
    Time:           2016-12-23 13:02:46.052 +0000 UTC
    NumTxs:         2
    LastBlockID:    B52A7701AAFAB980B44D3C7415972FEEC8F7D942:1:E647A8FA90EA
    LastCommit:     83F202126FBA458507F7E200DCCEE7E62E4474DD
    Data:           36721760CD4AA23A7B6B5F7C5515026379272DD2
    Validators:     281D550ECD5DA99E4ADD9FE411299F6EB46B523B
    App:            65B64A51FF9F58D823C23CF034E24291FCEDD2BA
  }#75860B411898B6A27AA40C726DE119A070F40B5B
  Data{
    Tx:[118 97 108 58 48 49 51 51 68 68 55 66 48 51 54 49 70 50 69 53 65 70 65 53 52 53 52 65 50 52 56 51 55 52 68 56 57 69 53 51 49 70 53 67 54 68 52 53 70 67 66 70 65 66 52 68 67 50 67 57 51 65 53 70 50 70 67 53 70 57 47 49 48]
    Tx:[118 97 108 58 48 49 51 53 66 53 67 53 65 70 55 48 65 48 57 54 50 69 55 56 67 56 48 68 65 48 56 48 51 49 55 50 48 55 48 50 57 68 57 68 49 65 70 57 51 66 49 51 56 48 68 56 55 69 49 48 51 65 69 52 53 53 53 49 54 66 47 49 48]
  }#36721760CD4AA23A7B6B5F7C5515026379272DD2
  Commit{
    BlockID:    B52A7701AAFAB980B44D3C7415972FEEC8F7D942:1:E647A8FA90EA
    Precommits: Vote{0:2E957CF919E5 10/00/2(Precommit) B52A7701AAFA /41960BB76AFD.../}
    Vote{1:4F6BE1A4BB35 10/00/2(Precommit) B52A7701AAFA /4D2CAD15F4F1.../}
    Vote{2:531D483CB987 10/00/2(Precommit) B52A7701AAFA /F96C0ACD5514.../}
    Vote{3:C25E810EEBF0 10/00/2(Precommit) B52A7701AAFA /E88B7FCC6533.../}
    Vote{4:DFD0788E654F 10/00/2(Precommit) B52A7701AAFA /E651F413BF54.../}
  }#83F202126FBA458507F7E200DCCEE7E62E4474DD
}#75860B411898B6A27AA40C726DE119A070F40B5B module=consensus
INFO[12-23|13:02:46] Executed block                           module=stateheight=11 valid txs=2 invalid txs=0
INFO[12-23|13:02:46] Update to validator set                  module=stateupdates="[{\"pub_key\":\"0133DD7B0361F2E5AFA5454A248374D89E531F5C6D45FCBFAB4DC2C93A5F2FC5F9\",\"power\":10},{\"pub_key\":\"0135B5C5AF70A0962E78C80DA080317207029D9D1AF93B1380D87E103AE455516B\",\"power\":10}]"
INFO[12-23|13:02:46] Saved state                              module=dummyroot=2719616B7C2585E000F5DFF1E2549061C5ED8AF1
NOTE[12-23|13:02:46] Saving block                             module=dummyheight=11 root=2719616B7C2585E000F5DFF1E2549061C5ED8AF1
INFO[12-23|13:02:46] Recheck txs                              module=mempool numtxs=0
INFO[12-23|13:02:46] Got block                                module=consensus height=11 validator=2
INFO[12-23|13:02:46] Added to lastPrecommits: VoteSet{H:11 R:0 T:2 +2/3:75860B411898B6A27AA40C726DE119A070F40B5B:1:F3BA2DCA105E BA{5:XX_XX} map[]} module=consensus
INFO[12-23|13:02:46] Added to lastPrecommits: VoteSet{H:11 R:0 T:2 +2/3:75860B411898B6A27AA40C726DE119A070F40B5B:1:F3BA2DCA105E BA{5:XXXXX} map[]} module=consensus
NOTE[12-23|13:02:46] enterNewRound(12/0). Current: 12/0/RoundStepNewHeightmodule=consensus
INFO[12-23|13:02:46] enterPropose(12/0). Current: 12/0/RoundStepNewRound module=consensus
INFO[12-23|13:02:46] enterPropose: Not our turn to propose    module=consensus proposer=2E957CF919E5BAFFB9CFCABE470BFD85A03531F4 privValidator="PrivValidator{19D27C755AE07DE3851E6F8076E42C2E812BAEB7 LH:0, LR:0, LS:0}"
INFO[12-23|13:02:46] Added to lastPrecommits: VoteSet{H:11 R:0 T:2 +2/3:75860B411898B6A27AA40C726DE119A070F40B5B:1:F3BA2DCA105E BA{5:XX_XX} map[]} module=consensus
INFO[12-23|13:02:46] Added to lastPrecommits: VoteSet{H:11 R:0 T:2 +2/3:75860B411898B6A27AA40C726DE119A070F40B5B:1:F3BA2DCA105E BA{5:XXXXX} map[]} module=consensus
NOTE[12-23|13:02:46] enterNewRound(12/0). Current: 12/0/RoundStepNewHeightmodule=consensus
INFO[12-23|13:02:46] enterPropose(12/0). Current: 12/0/RoundStepNewRound module=consensus
INFO[12-23|13:02:46] enterPropose: Not our turn to propose    module=consensus proposer=2E957CF919E5BAFFB9CFCABE470BFD85A03531F4 privValidator="PrivValidator{E3461FF43B6634012FBFF95DF897BF0F16FF7AD1 LH:0, LR:0, LS:0}"
INFO[12-23|13:02:46] Added to precommit                       module=consensus vote="Vote{0:2E957CF919E5 11/00/2(Precommit) 75860B411898 /B1D715AFA354.../}" precommits="VoteSet{H:11 R:0 T:2 +2/3:<nil> BA{5:X_XXX} map[]}"
INFO[12-23|13:02:46] Added to precommit                       module=consensus vote="Vote{1:4F6BE1A4BB35 11/00/2(Precommit) 75860B411898 /C78B5D6BAC4A.../}" precommits="VoteSet{H:11 R:0 T:2 +2/3:75860B411898B6A27AA40C726DE119A070F40B5B:1:F3BA2DCA105E BA{5:XXXXX} map[]}"
INFO[12-23|13:02:46] enterCommit(11/0). Current: 11/0/RoundStepPrecommit module=consensus
NOTE[12-23|13:02:46] Finalizing commit of block with 2 txs    module=consensus height=11 hash=75860B411898B6A27AA40C726DE119A070F40B5B root=65B64A51FF9F58D823C23CF034E24291FCEDD2BA
INFO[12-23|13:02:46] Block{
  Header{
    ChainID:        tendermint_test
    Height:         11
    Time:           2016-12-23 13:02:46.052 +0000 UTC
    NumTxs:         2
    LastBlockID:    B52A7701AAFAB980B44D3C7415972FEEC8F7D942:1:E647A8FA90EA
    LastCommit:     83F202126FBA458507F7E200DCCEE7E62E4474DD
    Data:           36721760CD4AA23A7B6B5F7C5515026379272DD2
    Validators:     281D550ECD5DA99E4ADD9FE411299F6EB46B523B
    App:            65B64A51FF9F58D823C23CF034E24291FCEDD2BA
  }#75860B411898B6A27AA40C726DE119A070F40B5B
  Data{
    Tx:[118 97 108 58 48 49 51 51 68 68 55 66 48 51 54 49 70 50 69 53 65 70 65 53 52 53 52 65 50 52 56 51 55 52 68 56 57 69 53 51 49 70 53 67 54 68 52 53 70 67 66 70 65 66 52 68 67 50 67 57 51 65 53 70 50 70 67 53 70 57 47 49 48]
    Tx:[118 97 108 58 48 49 51 53 66 53 67 53 65 70 55 48 65 48 57 54 50 69 55 56 67 56 48 68 65 48 56 48 51 49 55 50 48 55 48 50 57 68 57 68 49 65 70 57 51 66 49 51 56 48 68 56 55 69 49 48 51 65 69 52 53 53 53 49 54 66 47 49 48]
  }#36721760CD4AA23A7B6B5F7C5515026379272DD2
  Commit{
    BlockID:    B52A7701AAFAB980B44D3C7415972FEEC8F7D942:1:E647A8FA90EA
    Precommits: Vote{0:2E957CF919E5 10/00/2(Precommit) B52A7701AAFA /41960BB76AFD.../}
    Vote{1:4F6BE1A4BB35 10/00/2(Precommit) B52A7701AAFA /4D2CAD15F4F1.../}
    Vote{2:531D483CB987 10/00/2(Precommit) B52A7701AAFA /F96C0ACD5514.../}
    Vote{3:C25E810EEBF0 10/00/2(Precommit) B52A7701AAFA /E88B7FCC6533.../}
    Vote{4:DFD0788E654F 10/00/2(Precommit) B52A7701AAFA /E651F413BF54.../}
  }#83F202126FBA458507F7E200DCCEE7E62E4474DD
}#75860B411898B6A27AA40C726DE119A070F40B5B module=consensus
INFO[12-23|13:02:46] Executed block                           module=stateheight=11 valid txs=2 invalid txs=0
INFO[12-23|13:02:46] Update to validator set                  module=stateupdates="[{\"pub_key\":\"0133DD7B0361F2E5AFA5454A248374D89E531F5C6D45FCBFAB4DC2C93A5F2FC5F9\",\"power\":10},{\"pub_key\":\"0135B5C5AF70A0962E78C80DA080317207029D9D1AF93B1380D87E103AE455516B\",\"power\":10}]"
INFO[12-23|13:02:46] Saved state                              module=dummyroot=2719616B7C2585E000F5DFF1E2549061C5ED8AF1
NOTE[12-23|13:02:46] Saving block                             module=dummyheight=11 root=2719616B7C2585E000F5DFF1E2549061C5ED8AF1
INFO[12-23|13:02:46] Recheck txs                              module=mempool numtxs=0
INFO[12-23|13:02:46] Got block                                module=consensus height=11 validator=7
INFO[12-23|13:02:46] Added to precommit                       module=consensus vote="Vote{1:4F6BE1A4BB35 11/00/2(Precommit) 75860B411898 /C78B5D6BAC4A.../}" precommits="VoteSet{H:11 R:0 T:2 +2/3:75860B411898B6A27AA40C726DE119A070F40B5B:1:F3BA2DCA105E BA{5:XXXXX} map[]}"
INFO[12-23|13:02:46] enterCommit(11/0). Current: 11/0/RoundStepPrecommit module=consensus
NOTE[12-23|13:02:46] Finalizing commit of block with 2 txs    module=consensus height=11 hash=75860B411898B6A27AA40C726DE119A070F40B5B root=65B64A51FF9F58D823C23CF034E24291FCEDD2BA
INFO[12-23|13:02:46] Block{
  Header{
    ChainID:        tendermint_test
    Height:         11
    Time:           2016-12-23 13:02:46.052 +0000 UTC
    NumTxs:         2
    LastBlockID:    B52A7701AAFAB980B44D3C7415972FEEC8F7D942:1:E647A8FA90EA
    LastCommit:     83F202126FBA458507F7E200DCCEE7E62E4474DD
    Data:           36721760CD4AA23A7B6B5F7C5515026379272DD2
    Validators:     281D550ECD5DA99E4ADD9FE411299F6EB46B523B
    App:            65B64A51FF9F58D823C23CF034E24291FCEDD2BA
  }#75860B411898B6A27AA40C726DE119A070F40B5B
  Data{
    Tx:[118 97 108 58 48 49 51 51 68 68 55 66 48 51 54 49 70 50 69 53 65 70 65 53 52 53 52 65 50 52 56 51 55 52 68 56 57 69 53 51 49 70 53 67 54 68 52 53 70 67 66 70 65 66 52 68 67 50 67 57 51 65 53 70 50 70 67 53 70 57 47 49 48]
    Tx:[118 97 108 58 48 49 51 53 66 53 67 53 65 70 55 48 65 48 57 54 50 69 55 56 67 56 48 68 65 48 56 48 51 49 55 50 48 55 48 50 57 68 57 68 49 65 70 57 51 66 49 51 56 48 68 56 55 69 49 48 51 65 69 52 53 53 53 49 54 66 47 49 48]
  }#36721760CD4AA23A7B6B5F7C5515026379272DD2
  Commit{
    BlockID:    B52A7701AAFAB980B44D3C7415972FEEC8F7D942:1:E647A8FA90EA
    Precommits: Vote{0:2E957CF919E5 10/00/2(Precommit) B52A7701AAFA /41960BB76AFD.../}
    Vote{1:4F6BE1A4BB35 10/00/2(Precommit) B52A7701AAFA /4D2CAD15F4F1.../}
    Vote{2:531D483CB987 10/00/2(Precommit) B52A7701AAFA /F96C0ACD5514.../}
    Vote{3:C25E810EEBF0 10/00/2(Precommit) B52A7701AAFA /E88B7FCC6533.../}
    Vote{4:DFD0788E654F 10/00/2(Precommit) B52A7701AAFA /E651F413BF54.../}
  }#83F202126FBA458507F7E200DCCEE7E62E4474DD
}#75860B411898B6A27AA40C726DE119A070F40B5B module=consensus
INFO[12-23|13:02:46] Executed block                           module=stateheight=11 valid txs=2 invalid txs=0
INFO[12-23|13:02:46] Update to validator set                  module=stateupdates="[{\"pub_key\":\"0133DD7B0361F2E5AFA5454A248374D89E531F5C6D45FCBFAB4DC2C93A5F2FC5F9\",\"power\":10},{\"pub_key\":\"0135B5C5AF70A0962E78C80DA080317207029D9D1AF93B1380D87E103AE455516B\",\"power\":10}]"
INFO[12-23|13:02:46] Saved state                              module=dummyroot=2719616B7C2585E000F5DFF1E2549061C5ED8AF1
NOTE[12-23|13:02:46] Saving block                             module=dummyheight=11 root=2719616B7C2585E000F5DFF1E2549061C5ED8AF1
INFO[12-23|13:02:46] Recheck txs                              module=mempool numtxs=0
INFO[12-23|13:02:46] Got block                                module=consensus height=11 validator=0
INFO[12-23|13:02:46] Added to lastPrecommits: VoteSet{H:11 R:0 T:2 +2/3:75860B411898B6A27AA40C726DE119A070F40B5B:1:F3BA2DCA105E BA{5:XXXXX} map[]} module=consensus
NOTE[12-23|13:02:46] enterNewRound(12/0). Current: 12/0/RoundStepNewHeightmodule=consensus
INFO[12-23|13:02:46] enterPropose(12/0). Current: 12/0/RoundStepNewRound module=consensus
INFO[12-23|13:02:46] enterPropose: Not our turn to propose    module=consensus proposer=2E957CF919E5BAFFB9CFCABE470BFD85A03531F4 privValidator="PrivValidator{531D483CB9879AE41D8A8DE7E1F7AA4DED2E3AE2 LH:11, LR:0, LS:3}"
INFO[12-23|13:02:46] Added to lastPrecommits: VoteSet{H:11 R:0 T:2 +2/3:75860B411898B6A27AA40C726DE119A070F40B5B:1:F3BA2DCA105E BA{5:XXXXX} map[]} module=consensus
NOTE[12-23|13:02:46] enterNewRound(12/0). Current: 12/0/RoundStepNewHeightmodule=consensus
INFO[12-23|13:02:46] enterPropose(12/0). Current: 12/0/RoundStepNewRound module=consensus
INFO[12-23|13:02:46] enterPropose: Not our turn to propose    module=consensus proposer=2E957CF919E5BAFFB9CFCABE470BFD85A03531F4 privValidator="PrivValidator{4F6BE1A4BB35859287F01F9021E1C699C5245866 LH:11, LR:0, LS:3}"
INFO[12-23|13:02:46] Added to lastPrecommits: VoteSet{H:11 R:0 T:2 +2/3:75860B411898B6A27AA40C726DE119A070F40B5B:1:F3BA2DCA105E BA{5:XXXXX} map[]} module=consensus
NOTE[12-23|13:02:46] enterNewRound(12/0). Current: 12/0/RoundStepNewHeightmodule=consensus
INFO[12-23|13:02:46] enterPropose(12/0). Current: 12/0/RoundStepNewRound module=consensus
INFO[12-23|13:02:46] enterPropose: Not our turn to propose    module=consensus proposer=2E957CF919E5BAFFB9CFCABE470BFD85A03531F4 privValidator="PrivValidator{DFD0788E654F8234A89DBA7539F75CEE1E9CA10A LH:11, LR:0, LS:3}"
--- FAIL: TestValidatorSetChanges (22.76s)
        reactor_test.go:229: Timed out waiting for all validators to commit a block
```

### CODE REVIEW

**Comment by akalyaev** [comment]
Interesting observation: if you comment out "changing the voting power" subtest, all other tests will pass.

**Comment by ebuchman** [comment]
Negative voting power! Oh boy. Don't think that should ever happen

**Comment by ebuchman** [comment]
Should have clued in earlier - the apparent negative voting power is a formatting issues (note the MISSING). See the mismatch here: https://github.com/tendermint/tendermint/blob/develop/types/validator.go#L64

That's my bad, I changed the validator struct and neglected to update the format string. I think that makes https://github.com/tendermint/tendermint/pull/354 unnecessary. This line should prevent negative voting powers: https://github.com/tendermint/tendermint/blob/develop/state/execution.go#L150

That said, I do like using types to enforce possible states whenever possible, so I'm not opposed to this. Will need @jaekwon to be final arbitrer on whether or not we should change the voting power to uint64

**Comment by ebuchman** [comment]
rebased and fixed halting issue here: https://github.com/tendermint/tendermint/pull/359

**Pull request closed without merging**
