### PR TITLE
Switch away from ephemeral ports

### PR DESCRIPTION
**Pull request by ValarDragon**
This moves all ports of the form 466xx to 266xx. This is done to address cosmos/cosmos-sdk#932. Essentially the problem was the default ports used by tendermint are in the ephemeral port range. 

This requires tendermint/abci#253

### CODE REVIEW

**Comment by xla** [comment]
@ValarDragon We want this to be part of `0.21.0` if I got it right, could you bring it up to par with `develop`? :>

**Comment by ValarDragon** [comment]
Will do!

**Comment by ValarDragon** [comment]
Synced with develop. I accidentally merged abci's port change into develop, so I changed the abci referrence to develop

**Comment by ValarDragon** [comment]
Closed in favor of #1735

**Pull request closed without merging**
