### PR TITLE
optimize State.receiveRoutine

### PR DESCRIPTION
**Pull request by zhiqiangxu**
`mi` is always updated with the value received from channel, no need to allocate a new variable for each loop.

`rs` variable is not needed.

### CODE REVIEW

**Comment by creachadair** [comment]
Does this make any observable difference in performance?

**Comment by zhiqiangxu** [comment]
> Does this make any observable difference in performance?

Not necessarily, just some eye catcher

**Comment by tychoish** [comment]
I found myself in this file today for a related reason, and made a very similar change. I would avoid declaring the `mi` variable and just assign in the switch statement. If you make that change I'll definitely be inclined to merge this.

**Comment by tychoish** [comment]
This commit was merged into #8071, and that was merged, so I'm going to go ahead and close this PR!

Thanks so much for this contribution!

**Pull request closed without merging**
