### PR TITLE
light: Fix absence proof verification by light client

### LINKED ISSUE #7640: Light Client: Absence proof verification doesn't work
**Tendermint version:** v0.34.14 and master(`233f40963f5e26ea34a8d546d83714dc96600d7f`)
**ABCI app:** Cosmos-sdk and https://github.com/zigbee-alliance/distributed-compliance-ledger

**What happened**:
- LightClient proxy is started
- An ABCI query request is sent via light client proxy where there is no value for the given key in the store
- Absence proof verification fails with the error: `verify absence proof: key path string must start with a forward slash '/'`

**What you expected to happen**:
- No error. Absence proof is successfully verified.

**Have you tried the latest version**: yes

I believe the reason is that not a full path (without a store prefix) is passed to `VerifyAbsence` function in https://github.com/tendermint/tendermint/blob/master/light/rpc/client.go.

### PR DESCRIPTION
**Pull request by ashcherbakov**
Use the full key path to pass to the `VerifyAbsence` function to avoid the error `verify absence proof: key path string must start with a forward slash '/'`.

Closes #7640.

### CODE REVIEW

**Review by cmwaters — APPROVED** [review]
Thanks!! It's kind of unfortunate we don't have a test for that. We should probably backport this as well

**Comment by ashcherbakov** [comment]
@cmwaters 
As I can see, some tests are failing. Is it some intermittent failure? It doesn't seem to be connected to the changes in this PR...

**Comment by cmwaters** [comment]
Yes our tests are a little flaky at the moment so you might need to rerun it. Do you mind also adding an entry to the changelog_pending document.

**Comment by ashcherbakov** [comment]
Sure, just updated changelog_pending document.

**Pull request merged**
