### PR TITLE
Backport v0.34.0-rc7: #5661

### PR DESCRIPTION
**Pull request by alexanderbez**
## Description

Backport #5661 to v0.34.0-rc7.

/cc @tessr

### CODE REVIEW

**Review by marbar3778 — APPROVED** [review]

**Comment by erikgrinaker** [comment]
Looks like we forgot to clear out `CHANGELOG_PENDING.md` when making the rc6 release. I'd submit a separate PR that just clears out everything that's been moved to `CHANGELOG.md` and updates `_PENDING` to rc7.

**Comment by alexanderbez** [comment]
@erikgrinaker mind if I just do that in this PR? Or does `CHANGELOG` updates for rc6 need to happen on `master`?

**Comment by erikgrinaker** [comment]
Personally I'd prefer a separate PR, but I don't think it matters in this case since we're never going to be cherry-picking any of these changes anywhere else.

**Comment by alexanderbez** [comment]
Updated @erikgrinaker

**Review by erikgrinaker — APPROVED** [review]

**Pull request merged**
