### PR TITLE
proto: rebuild the proto files from the spec repository

### PR DESCRIPTION
**Pull request by williambanfield**

### CODE REVIEW

**Review by creachadair — APPROVED** [review]
LGTM, modulo whatever lint wildness is going on.

**Comment by williambanfield** [comment]
> LGTM, modulo whatever lint wildness is going on.

Ah, these are lint rules that don't quite make sense anymore since the protos are in the spec repo. I'll need to give those a once over.

**Comment by creachadair** [comment]
> Ah, these are lint rules that don't quite make sense anymore since the protos are in the spec repo. I'll need to give those a once over.

Yeah, I'm fine with turning them off (either temporarily or permanently, as appropriate). But at least one of the errors appears to be about a missing file, so I wasn't sure what to recommend.

**Comment by williambanfield** [comment]
> Yeah, I'm fine with turning them off (either temporarily or permanently, as appropriate). But at least one of the errors appears to be about a missing file, so I wasn't sure what to recommend.

The issues occur because we no longer have the build tooling present for the protos. I'm going to disable and write up an issue on how to fix.

**Pull request merged**
