### PR TITLE
Add Tendermint Official Discord to main README

### PR DESCRIPTION
**Pull request by jaekwon**
Adding the new Tendermint official discord

### CODE REVIEW

**Comment by tessr** [comment]
I'm a little worried about introducing too many communication channels. Before merging this, I'd like to know:

1. What are the concrete issues and concerns with the other Discord? I know I personally haven't been super active over there (and my apologies for that!) but I'm not sure that adding another channel will get people to use it any more.
2. I'm wary of giving the community whiplash with so many changes to the chat platform (first Tendermint friends, then Riot, then Discord 1, and now Discord 2?). I'd like to invite the community to weigh in on this before making any more changes. What do you think?

**Comment by cwgoes** [comment]
Maybe we could create a poll on the community Discord, to see if they would prefer discussing Tendermint-related topics there or in a different channel? I don't think it's possible to bridge Discords, unfortunately (although I could be wrong about that).

**Comment by alexanderbez** [comment]
@jaekwon, can you at the very least describe why you're proposing this? This will not go over well with the community as @tessr already laid out and I see nothing wrong with the current Discord. What are your concerns? Is it a power struggle?

**Comment by melekes** [comment]
Can we close this?

**Comment by tessr** [comment]
Will close for now, especially as there are merge conflicts and this is a small PR.

**Pull request closed without merging**
