### PR TITLE
attempt to repair the WAL file on data corruption

### PR DESCRIPTION
**Pull request by alessio**
Automatically try to repair the WAL file in case of corruption
if the `wal2json` and `json2wal` repair tools are installed:

```
 $ go install github.com/tendermint/tendermint/scripts/{wal2json,json2wal}
```

Closes: #4578

______

For contributor use:

- [ ] Wrote tests
- [ ] Updated CHANGELOG_PENDING.md
- [ ] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [ ] Updated relevant documentation (`docs/`) and code comments
- [ ] Re-reviewed `Files changed` in the Github PR explorer

### CODE REVIEW

**Comment by alessio** [comment]
This requires the `wal2json` and `json2wal` binaries to be available in user's `$PATH`

**Comment by erikgrinaker** [comment]
I think this is a bit of a kludge, but it may be fine as a stopgap solution. A proper WAL should be designed in such a way that it is resistant to corruption and will recover automatically - the whole point of a WAL is to recover from unexpected crashes, after all.

In any case, for something as important as this it would be great to have integration tests that run recovery on a range of WAL corruption scenarios.

**Comment by alessio** [comment]
@erikgrinaker I totally agree. I had issues in trying to reproduce a WAL data corruption, I've managed to test this by injecting a `return DataCorruptionError{}` in `catchupReplay()`. It'd be great to have some test data to start with, and I welcome any help :)

**Comment by erikgrinaker** [comment]
> It'd be great to have some test data to start with 

From the issue it appears like it can be reproduced quite reliably by stress-testing a network and killing nodes.

**Comment by alessio** [comment]
@erikgrinaker 

> A proper WAL should be designed in such a way that it is resistant to corruption and will recover automatically

I've been thinking about this, there are a couple of solutions I thought of:
* transaction writing of WAL file entries (2-step write, 1st you write the message without the crc, then you write it again with the crc). This could improve error detection
* increased data redundancy should help with the data recovery

Wdyt?

**Comment by erikgrinaker** [comment]
I agree with @melekes, let's have a separate process on improving the WAL overall. Would be nice to have binaries integrated.

>transaction writing of WAL file entries (2-step write, 1st you write the message without the crc, then you write it again with the crc). This could improve error detection

I am not familiar with the current WAL yet, so it's hard for me to have an informed opinion. Storing data twice is likely to have a performance impact - if the problem is incorrect data being written then something like Reed-Solomon error correction is possibly better than duplication.

However, my impression is that the primary failure mode is simply truncated or otherwise incomplete writes due to abrupt process termination. Something like calling `fsync` and discarding incomplete entries (e.g. by length-prefixing) would possibly go a long way.

In general, writing a reliable WAL is hard (gold standard is [Aries paper](https://cs.stanford.edu/people/chrismre/cs345/rl/aries.pdf) at 70 pages), so we may want to use an existing battle-tested solution.

**Comment by melekes** [comment]
> However, my impression is that the primary failure mode is simply truncated or otherwise incomplete writes due to abrupt process termination

correct

**Comment by alessio** [comment]
@melekes is there any other issue here you want me to address?

**Comment by melekes** [comment]
> @melekes is there any other issue here you want me to address?

"Instead of executing binaries, can't we copy the logic and simply call the function? I think it will be more robust and testable then calling outside processes."

**Comment by melekes** [comment]
Your copy function does not work @alessio 

```
--- FAIL: TestCopyFile (0.01s)
    os_test.go:34: copy file content differs: expected [104 101 108 108 111 32 119 111 114 108 100], got []
```

**Comment by alessio** [comment]
Yeah  thanks very much for taking care of this :pray: - bit swamped here

**Comment by melekes** [comment]
I won't lie it's a bit hard to cover all of the cases in your head and we should test all of them ideally. Looking at https://github.com/tendermint/tendermint/pull/3246#issuecomment-460295900 and https://github.com/tendermint/tendermint/issues/3089#issuecomment-460115857, it should be safe no matter what entries are truncated.

- if corrupted entries are in past heights, we proceed to start consensus state anyway and may get `Error signing vote: Conflicting data` error (https://github.com/tendermint/tendermint/issues/3089) (due to _file system error_)
- if corrupted entries are in last height, we may get `Error signing vote: Conflicting data` error (https://github.com/tendermint/tendermint/issues/3089) (due to _file system error_)
- if corrupted entry! is last message, we will repair the wal and restart normally (due to _validator crashing; happens most often_)

**Pull request merged**
