### PR TITLE
consensus: fix tracking for MarkGood

### PR DESCRIPTION
**Pull request by melekes**
Refs #1317

### CODE REVIEW

**Comment by melekes** [comment]
Should we mark peer as good only once https://github.com/tendermint/tendermint/pull/1333/commits/31f3dd42e7c420ae6a018c7b9a965f22c5736186 or say every 10000 blocks?

**Comment by ebuchman** [comment]
> Should we mark peer as good only once 31f3dd4 or say every 10000 blocks?

I think we need to keep doing it. If enough peers are marked good eventually some will become unmarked, so good to have a force that will continue to cycle them back into good territory!

**Comment by ebuchman** [comment]
Awesome thanks for the quick turn around. I'll open a new issue for the "repeated MarkGood" but let's punt it to the next iteration :)

**Comment by ebuchman** [comment]
lol darn it @melekes that was fast :P 

I was about to merge but I can wait for the new CI run 💃

**Comment by ebuchman** [comment]
Np. PersistentPeer test failed but @xla is working on it now. 

Will merge this. Thanks!

**Pull request merged**
