### PR TITLE
libs/clist: fix flaky tests

### LINKED ISSUE #6452: libs/clist: fix flaky tests
## Summary

Make two`libs/clist` tests that depend on `runtime.SetFinalizer` work:

 - https://github.com/tendermint/tendermint/blob/c320eb14079e0091ebef56458ceee4ead9a75b61/libs/clist/clist_test.go#L71
 -https://github.com/tendermint/tendermint/blob/c320eb14079e0091ebef56458ceee4ead9a75b61/libs/clist/clist_test.go#L120

## Problem Definition

The reason those tests are disabled because they depend on `runtime.SetFinalizer`, which is documented as not guaranteed to run. It's not quite true, as for those tests, the problem is that `runtime.GC()` does not guarantee that the associated finalizer of objects will run.

## Proposal

We just need to add a synchronization primitive, to make sure the finalizers will run, using a channel.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

### PR DESCRIPTION
**Pull request by cuonglm**
To make sure finalizers run, we use channel for synchronization, and a
separate goroutine for trigger runtime.GC every 1 second. In practice,
just two consecutive runtime.GC calls can make all finalizers will run,
but using a separate goroutine make the code more robust and not depend
on garbage collector internal implementation.

Fixes #6452

### CODE REVIEW

**Comment by cuonglm** [comment]
cc @odeke-em

**Review by alexanderbez — APPROVED** [review]

**Review by tychoish — APPROVED** [review]

**Comment by tychoish** [comment]
I think we're willing to merge this PR, but it needs to be rebased before we can. Are you still interested in this change?

**Comment by cuonglm** [comment]
> I think we're willing to merge this PR, but it needs to be rebased before we can. Are you still interested in this change?

Done.

**Comment by marbar3778** [comment]
@cuonglm could you enable maintainers to edit the PR, this way the bot can take care of merging

**Comment by cuonglm** [comment]
> @cuonglm could you enable maintainers to edit the PR, this way the bot can take care of merging

Sure, could you please tell me how to enable that?

**Comment by marbar3778** [comment]
I believe when you edit the description there is a checkbox.

**Pull request merged**
