### PR TITLE
go.mod: upgrade iavl and deps

### PR DESCRIPTION
**Pull request by erikgrinaker**
Bumps IAVL, which pulled in some other upgrades as well. I think they should be fine though.

### CODE REVIEW

**Review by tessr — APPROVED** [review]
Awesome. Do we want to get this in for the 0.34 line as well?

**Comment by erikgrinaker** [comment]
Yes, I'm backporting this along with the tm-db bump once it's merged.

**Comment by marbar3778** [comment]
Woah, why is iavl imported in tendermint? It shouldn't be.

**Comment by erikgrinaker** [comment]
It's used by some tests.

**Comment by marbar3778** [comment]
oh wow, didn't see that.

**Pull request merged**
