### PR TITLE
ci: only run when applicable

### PR DESCRIPTION
**Pull request by marbar3778**
## Description

- only run tests when `.go, .mod, .sum` files have been touched
- only run proto checks when `.proto` files have been touched

Signed-off-by: Marko Baricevic <marbar3778@yahoo.com>

### CODE REVIEW

**Comment by erikgrinaker** [comment]
Should probably run when `go.mod` or `go.sum` changes as well.

**Comment by marbar3778** [comment]
There is no clean way of doing this so I opted to exit 1 on the diff job if no go files were changed and have other jobs depend on diff passing

**Comment by erikgrinaker** [comment]
> There is no clean way of canceling different jobs then the one that has the git diff step is in so I opted to exit 1 on the diff job if no go files were changed and have other jobs depend on diff passing

That's too bad. This won't cause the entire run to fail, I hope?

**Comment by marbar3778** [comment]
it will just skip the jobs that depend on it wont effect other runners. It will just have a red x for the on the ci since a job force failed. The proto checks are one job so it skips but gives a green check.

**Comment by marbar3778** [comment]
@tessr is there a way to make it required only if its run? otherwise, we will need to remove the required from test_app

**Comment by tessr** [comment]
Good question. I'll look into that. 

Btw, I think this is `.github` not `ci` in the commit message

**Comment by tessr** [comment]
There doesn't seem to be a way to mark these checks as "required if run," only "required." I'm a little wary of lifting all CI requirements. Is there a way to modify the jobs themselves to automatically pass if the relevant files haven't been changed, rather than changing whether or not the jobs run?

**Comment by marbar3778** [comment]
>. Is there a way to modify the jobs themselves to automatically pass if the relevant files haven't been changed, rather than changing whether or not the jobs run?

made this change now test_apps will pass when no diff

**Pull request merged**
