### PR TITLE
doc: update go tutorials

### PR DESCRIPTION
**Pull request by stevenferrer**
- Updated Go tutorials for the latest version of Tendermint, which is `v.0.35.8`

### CODE REVIEW

**Comment by sergio-mena** [comment]
Thanks for this, @stevenferrer
Would you mind applying these changes to `docs/tutorials/go.md` (those that make sense there)?

**Comment by stevenferrer** [comment]
Hi @sergio-mena, yes sure, I'll update the PR to include the changes you requested.

**Comment by stevenferrer** [comment]
Hi @sergio-mena, sorry I accidentally deleted my branch. I'll create another PR.

**Comment by stevenferrer** [comment]
Here's the new PR https://github.com/tendermint/tendermint/pull/9048

**Pull request closed without merging**
