### PR TITLE
ci: migrate test_cover

### PR DESCRIPTION
**Pull request by marbar3778**
## Description

This pr aims to migrate the test_cover ci job from circle to github actions. There are a few issues that it is running into. 

Closes: #XXX

### CODE REVIEW

**Comment by marbar3778** [comment]
So the test_coverage is passing consistently. There is a weird occurrence where now the coverage is full while before there were missing files in the coverage report, I don't know if this was due to parallelism or the gnourmous script to ulaod the report.

I would prefer to wait till some more test fixes are in and then merge this just to run it a few more times.

**Comment by erikgrinaker** [comment]
> now the coverage is full while before there were missing files in the coverage report, I don't know if this was due to parallelism or the gnourmous script to ulaod the report

👍 My guess would be parallelism.

**Comment by marbar3778** [comment]
marking this as unblocked as the ci speed has picked up and it is passing consistently. I'm not sure which PR made it speed up and pass or if it was a github action thing.

 If we want to reduce the time more I can test splitting across 5 or greater machines. Just let me know what you preference is.

**Comment by marbar3778** [comment]
to be able to merge this we have to make the job `upload_coverage` not required.

**Comment by marbar3778** [comment]
the failure of `Test Coverage / test-coverage-part-1 (pull_request)` is not due to tests but code coverage post timeout. This shouldnt block the merge tho

**Comment by marbar3778** [comment]
this is as flaky as the current ci system. To merge it we need to make test_cover not required, then once this is merged we can enable required on all `test-coverage-parts`

**Pull request merged**
