### PR TITLE
ci: reenable contract tests

### PR DESCRIPTION
**Pull request by marbar3778**
## Description

test enabling contract tests

Closes: #XXX

### CODE REVIEW

**Comment by marbar3778** [comment]
Im not sure the best path forward here. Looking at other tools they all involve writing js or python. While I am willing to do this it will increase the maintance load for when working on the RPC. I dont know if we are willing to accept this?

**Comment by melekes** [comment]
> Im not sure the best path forward here. Looking at other tools they all involve writing js or python. While I am willing to do this it will increase the maintance load for when working on the RPC. I dont know if we are willing to accept this?

could you explain the need for python scripts? is it because dredd does not support openapi3?

**Comment by marbar3778** [comment]
> could you explain the need for python scripts? is it because dredd does not support openapi3?

Yes, dredd does not support openAPI3.0. They are still missing support of keys things. Dredd was a cmd that would test your openapi doc against an endpoint, while with other tools you would have to write a bit of code to test against an endpoint.

**Comment by marbar3778** [comment]
closing this for now. Will pick it up but dont want it to sit around

**Pull request closed without merging**
