### PR TITLE
backport: performance improvements for the event query API (#7319)

### PR DESCRIPTION
**Pull request by mmsqe**
---

#### PR checklist

- [ ] Tests written/updated, or no tests needed
- [ ] `CHANGELOG_PENDING.md` updated, or no changelog entry needed
- [ ] Updated relevant documentation (`docs/`) and code comments, or no
      documentation updates needed

### CODE REVIEW

**Review by cmwaters — APPROVED** [review]
This looks good to me. Just needs a changelog (I realise it shouldn't change user behaviour but I think it's appropriate to still advertise the change)

**Comment by sergio-mena** [comment]
Please do not merge it to `main` for the moment.
We need to decide when this should be merged to `main`. We also need to review the process followed to backport Michael PR's, to make sure there are no loose ends.
I'm more than willing to discuss details over Slack.

**Comment by mmsqe** [comment]
I just follow the steps in https://github.com/tendermint/tendermint/pull/7801 and test rest adr075 [backports](https://github.com/mmsqe/tendermint/pulls) in [ethermint](https://github.com/evmos/ethermint/pull/1321) with more websocket e2e tests in [cronos](https://github.com/crypto-org-chain/cronos/pull/688), free to ping me when need change.

**Comment by cmwaters** [comment]
I just want to clarify that this PR isn't actually a reimplementation of adr075. It's just the performance improvements that Michael did in https://github.com/tendermint/tendermint/pull/7319. The ADR actually involves adding a new API

**Comment by mmsqe** [comment]
> I just want to clarify that this PR isn't actually a reimplementation of adr075. It's just the performance improvements that Michael did in #7319 which AFAIK wasn't part of the ADR which actually involved adding a new API.

yes, since this is prerequisites of the rest backports.

**Comment by cmwaters** [comment]
> yes, since this is prerequisites of the rest backports.

Do you plan to do the rest of the commits in this PR or as a separate PR? (I think I would prefer them separated)

**Comment by mmsqe** [comment]
> Do you plan to do the rest of the commits in this PR or as a separate PR? (I think I would prefer them separated)

yes, to keep as minimal as possible.

**Comment by sergio-mena** [comment]
Let me clarify my comment. This effort (i.e. porting ADR075) looks like a good candidate for a feature branch. Hence I was saying to hold on this PR. If this PR is the first of a series of backports that are needed to get ADR075 on`main`, I would prefer to:

* First create a feature branch
* Rebase this PR against it, and merge as its first commit
* Reach agreement (probably synchronously) how we are going to review, and/or follow up, the backport work taking place in that branch.

I don't think it's a good idea to backport the whole set of PRs for ADR075 directly on `main`, it's a long shot IMO.

**Comment by sergio-mena** [comment]
> That would work, but which feature branch I should based on?

I'll come back to you shortly on that

**Comment by JayT106** [comment]
> I just want to clarify that this PR isn't actually a reimplementation of adr075. It's just the performance improvements that Michael did in #7319 which AFAIK wasn't part of the ADR which actually involved adding a new API.

That's correct, I chatted this to @thanethomson last weekend. It might be good to merge it into v37 and v34 if possible.

**Review by thanethomson — APPROVED** [review]

**Review by cmwaters — COMMENTED** [review]
add changelog entry to v0.38

**Comment by cmwaters** [comment]
Thanks for contributing @mmsqe!

**Comment by mmsqe** [comment]
> Thanks for contributing @mmsqe!

I take a free ride, thanks @creachadair

**Comment by mmsqe** [comment]
> I'll come back to you shortly on that

@sergio-mena May I ask any update on feature branch of backport adr075?

**Comment by sergio-mena** [comment]
> @sergio-mena May I ask any update on feature branch of backport adr075?

Sorry, @mmsqe, for my late reply (had to deal with personal issues).

We have created branch `feature/adr075-backport`. This branch (which forks from `main`) is to act as base branch for all PRs related to the backport of adr075-related commits.

We will be reviewing all those PRs and merging them into `feature/adr075-backport`. Please backport PRs on a one-to-one basis, for better traceability. Also, please make use of `git cherry-pick` whenever possible (thus leveraging git's 3-way merge to reduce conflicts).

Once the backport is complete, and all CI tests pass, we will proceed to merge `feature/adr075-backport` back to `main`. Note this is the process we are following to backport other features such as ABCI++.

If you have any questions/comments/concerns don't hesitate to contact me over Slack, or email (sergio@informal.systems).

**Pull request merged**
