### PR TITLE
state: wait for async DeliverTx responses in execBlockOnProxyApp()

### LINKED ISSUE #2965: consensus failure while benchmarking kvstore app (gRPC, no empty blocks)
no empty blocks, skip_timeout_commit, cleveldb, gRPC server/client
tendermint 0.27.0-d9a1aad5

E[4126-12-04|14:14:41.953] CONSENSUS FAILURE!!!                         module=consensus err="runtime error: invalid memory address or nil pointer dereference" stack="goroutine 68 [running]:\nruntime/debug.Stack(0xc0034283c0, 0xd363c0, 0x19284d0)\n\t/usr/local/go/src/runtime/debug/stack.go:24 +0xa7\ngithub.com/tendermint/tendermint/consensus.(*ConsensusState).receiveRoutine.func2(0xc000888380, 0xfab6d0)\n\t/root/go/src/github.com/tendermint/tendermint/consensus/state.go:576 +0x57\npanic(0xd363c0, 0x19284d0)\n\t/usr/local/go/src/runtime/panic.go:513 +0x1b9\ngithub.com/tendermint/tendermint/types.NewResultFromResponse(...)\n\t/root/go/src/github.com/tendermint/tendermint/types/results.go:44\ngithub.com/tendermint/tendermint/types.NewResults(0xc002da0000, 0x183a, 0x183a, 0xc003918dc0, 0xc001d6c2b8, 0xc0027dc2d0)\n\t/root/go/src/github.com/tendermint/tendermint/types/results.go:36 +0x6b\ngithub.com/tendermint/tendermint/state.(*ABCIResponses).ResultsHash(0xc004013710, 0xc0027dc5a0, 0xb602ec, 0xc0034285c8)\n\t/root/go/src/github.com/tendermint/tendermint/state/store.go:133 +0x40\ngithub.com/tendermint/tendermint/state.updateState(0x8, 0x1, 0xc00095286a, 0x6, 0xc000877640, 0x11, 0xd, 0x5a57, 0xc0026f3840, 0x20, ...)\n\t/root/go/src/github.com/tendermint/tendermint/state/execution.go:469 +0x3c6\ngithub.com/tendermint/tendermint/state.(*BlockExecutor).ApplyBlock(0xc000954380, 0x8, 0x1, 0xc00095286a, 0x6, 0xc000877640, 0x11, 0xd, 0x5a57, 0xc0026f3840, ...)\n\t/root/go/src/github.com/tendermint/tendermint/state/execution.go:125 +0x50b\ngithub.com/tendermint/tendermint/consensus.(*ConsensusState).finalizeCommit(0xc000888380, 0xe)\n\t/root/go/src/github.com/tendermint/tendermint/consensus/state.go:1290 +0xa8c\ngithub.com/tendermint/tendermint/consensus.(*ConsensusState).tryFinalizeCommit(0xc000888380, 0xe)\n\t/root/go/src/github.com/tendermint/tendermint/consensus/state.go:1221 +0x451\ngithub.com/tendermint/tendermint/consensus.(*ConsensusState).enterCommit.func1(0xc000888380, 0x0, 0xe)\n\t/root/go/src/github.com/tendermint/tendermint/consensus/state.go:1167 +0x90\ngithub.com/tendermint/tendermint/consensus.(*ConsensusState).enterCommit(0xc000888380, 0xe, 0x0)\n\t/root/go/src/github.com/tendermint/tendermint/consensus/state.go:1198 +0x6b8\ngithub.com/tendermint/tendermint/consensus.(*ConsensusState).addVote(0xc000888380, 0xc0022117c0, 0x0, 0x0, 0x488edd, 0xc0014e7bc0, 0xc000a64100)\n\t/root/go/src/github.com/tendermint/tendermint/consensus/state.go:1622 +0xc03\ngithub.com/tendermint/tendermint/consensus.(*ConsensusState).tryAddVote(0xc000888380, 0xc0022117c0, 0x0, 0x0, 0x42f272, 0xc000000008, 0xc003429b80)\n\t/root/go/src/github.com/tendermint/tendermint/consensus/state.go:1469 +0x59\ngithub.com/tendermint/tendermint/consensus.(*ConsensusState).handleMsg(0xc000888380, 0x10673a0, 0xc001d6c0d0, 0x0, 0x0)\n\t/root/go/src/github.com/tendermint/tendermint/consensus/state.go:650 +0x696\ngithub.com/tendermint/tendermint/consensus.(*ConsensusState).receiveRoutine(0xc000888380, 0x0)\n\t/root/go/src/github.com/tendermint/tendermint/consensus/state.go:611 +0x555\ncreated by github.com/tendermint/tendermint/consensus.(*ConsensusState).OnStart\n\t/root/go/src/github.com/tendermint/tendermint/consensus/state.go:300 +0x132\n"

### LINKED ISSUE #5540: abci/grpc: index out of range panic
E2E tests report:

```
validator05    | I[2020-10-21|02:15:38.356] Executed block                               module=state height=51 validTxs=6 invalidTxs=0
validator05    | panic: runtime error: index out of range [6] with length 6
validator05    | 
validator05    | goroutine 47 [running]:
validator05    | github.com/tendermint/tendermint/state.execBlockOnProxyApp.func1(0xc000452160, 0xc000452270)
validator05    | 	github.com/tendermint/tendermint/state/execution.go:287 +0x22a
validator05    | github.com/tendermint/tendermint/abci/client.(*grpcClient).OnStart.func1.1(0xc001d85080)
validator05    | 	github.com/tendermint/tendermint/abci/client/grpc_client.go:70 +0xd2
validator05    | github.com/tendermint/tendermint/abci/client.(*grpcClient).OnStart.func1(0xc000032e60)
validator05    | 	github.com/tendermint/tendermint/abci/client/grpc_client.go:80 +0x95
validator05    | created by github.com/tendermint/tendermint/abci/client.(*grpcClient).OnStart
validator05    | 	github.com/tendermint/tendermint/abci/client/grpc_client.go:62 +0x59
```

### PR DESCRIPTION
**Pull request by erikgrinaker**
Fixes #5540, fixes #2965.

`execBlockOnProxyApp()` assumes that `EndBlockSync()` will block until all pending `DeliverTxAsync` calls have returned, but this is not true for the gRPC client - and I don't think it's necessarily guaranteed by ABCI async call semantics either. Async calls will return "sometime". This change causes `execBlockOnProxyApp()` to wait for the async callbacks to be processed.

The alternative is to modify the gRPC ABCI client to guarantee ordering of both sync and async responses, such that sync calls will block until all previous async calls have completed.

### CODE REVIEW

**Comment by melekes** [comment]
> and I don't think it's necessarily guaranteed by ABCI async call semantics either

it's guaranteed by socket client - https://github.com/tendermint/tendermint/blob/14b14548ebb3b68926f53035138ded75daa358eb/abci/client/socket_client.go#L365. It executes Flush and waits for result. Flush will force the server to flush the write buffer https://github.com/tendermint/tendermint/blob/14b14548ebb3b68926f53035138ded75daa358eb/abci/server/socket_server.go#L253.

**Comment by melekes** [comment]
We should probably go with the easiest approach here because [`DeliverBlock`](https://github.com/tendermint/tendermint/issues/2901) will remove the need for both `WaitGroup` and the aformentioned flushing requirement.

**Comment by melekes** [comment]
We should probably go with the easiest approach here because [`DeliverBlock`](https://github.com/tendermint/tendermint/issues/2901) will remove the need for both `WaitGroup` and the aformentioned flushing requirement. But I would love to hear from @ebuchman on this.

**Comment by erikgrinaker** [comment]
Yeah, this doesn't even seem to work properly, I think there's some crosstalk (i.e. buffered messages from previous blocks or other actions) that cause interference. I'll change the gRPC client to guarantee ordering of sync calls as well.

**Comment by erikgrinaker** [comment]
Went with the other option, see #5556.

**Pull request closed without merging**
