### PR TITLE
backport block size fixes

### PR DESCRIPTION
**Pull request by marbar3778**
## Description

In protobuf `[]byte` is varint encoded. When adding txs to the block we were not taking this into account.

Closes: #XXX

### CODE REVIEW

**Comment by erikgrinaker** [comment]
Did you originally branch this off of `master`? Cherry-pick branches must be branched off of the target branch (`0.34.0-rc5`), not the source branch, so that you can resolve conflicts and such.

**Comment by erikgrinaker** [comment]
Hm, or maybe it's just the LGTM analysis that's broken. 🤷‍♀️

**Review by erikgrinaker — APPROVED** [review]

**Comment by cmwaters** [comment]
Don't I have to get my evidence bytes PR in first as this branched of it?

**Comment by marbar3778** [comment]
> Don't I have to get my evidence bytes PR in first as this branched of it?

Either way. I can leave this here and then you can cherry-pick your commit from master?

**Comment by marbar3778** [comment]
> Can I just roll them all in one PR (there's 4 in total including this one)?

Yes, should we use this PR or open a new one?

**Review by marbar3778 — COMMENTED** [review]
lgtm

**Comment by erikgrinaker** [comment]
This should've really been rebase-merged, not squash-merged, to keep the commit history. It makes it much easier to compare the branches and see which changes have been backported and which haven't.

**Comment by erikgrinaker** [comment]
It's kind of too late, unless you want to rewrite the branch history or submit a PR that reverts this. We can probably let it slide, just keep it in mind for later.

**Pull request merged**
