### PR TITLE
linter: remove nolintlint

### PR DESCRIPTION
**Pull request by cmwaters**
## Description

We're starting to stack up on nolintlint messages (for no lint comments on gosec and gocritic). Either we remove golintlint or the comments that ignore certain linting aspects. 

Closes: #XXX

### CODE REVIEW

**Comment by erikgrinaker** [comment]
Remove the `nolint` comments that shouldn't be there. That's the whole purpose of `nolintlint`. :)

**Comment by erikgrinaker** [comment]
Ah, maybe this isn't clear: the purpose of `nolintlint` is to warn about `//nolint:` comments that have no effect. For example, if there is a `//nolint:gosec` comment in a file, but that file doesn't trigger any `gosec` linter warnings, then `nolintlint` will warn us to remove the unused comment.

**Comment by erikgrinaker** [comment]
This is now failing the linter in CI. Please make sure you have the same version of the linter locally as in CI.

**Comment by cmwaters** [comment]
Is there a way with `make lint` to ensure that the linter versions are the same?

**Comment by erikgrinaker** [comment]
> Is there a way with make lint to ensure that the linter versions are the same?

Using a Docker image would be the most reliable way, I think. Alternatively force-installing the correct versions of linters on the local machine, but that's pretty rude.

**Comment by erikgrinaker** [comment]
Hm, and there's also the problem with editors (e.g. VSCode) using its own versions of linters, regardless of what `make lint` does.

**Comment by cmwaters** [comment]
really? okay then I will just leave it

**Pull request closed without merging**
