### PR TITLE
Add adr-049

### PR DESCRIPTION
**Pull request by b00f**
* [ ] Referenced an issue explaining the need for the change
* [X] Updated all relevant documentation in docs
* [ ] Updated all code comments where relevant
* [ ] Wrote tests
* [ ] Updated CHANGELOG_PENDING.md

### CODE REVIEW

**Comment by marbar3778** [comment]
Sorry for the delay in our response, this isnt an interest of Tendermint at the current time. There is a team working on extending vulcanizeDB to cosmos and tendermint based chains and they do support this. I do believe this is a better option for now. Will close this for now, but if you want to open an issue to hold some discussions, it may be better.

**Comment by melekes** [comment]
This could be implemented as IPFS indexer, which saves transactions to IPFS (https://github.com/tendermint/tendermint/tree/master/state/txindex). I don't see any reason to switch to IPFS standard though. Are there any other benefits except that it would be easier to fetch blocks/transactions from IPFs?

**Comment by b00f** [comment]
>  but if you want to open an issue to hold some discussions, it may be better.

Why not discussing here?

> Are there any other benefits except that it would be easier to fetch blocks/transactions from IPFs?

Yes. Not only txs, blocks also can be indexed in IPFS. Hash is just a raw dara, however CID has better format and since it has version and type it's more unique. CID is a better way to point any piece of information compare to hash.

**Comment by melekes** [comment]
> Yes. Not only txs, blocks also can be indexed in IPFS. 

They can be indexed right now too, don't they? You just need to wrap the hash into CID (i.e. add version, etc.)

> Hash is just a raw dara, however CID has better format and since it has version and type it's more unique.

Hash is unique too.

> CID is a better way to point any piece of information compare to hash.

for multiple kinds of information - agree, but if you only have one type (blocks), then I still don't see a strong enough reason to use CID.

**Comment by b00f** [comment]
Using CID might help to work with IPFS easier. (i.e. libp2p integration). I checked FileCoin project, They preferred using CID to [refer a block](https://github.com/filecoin-project/go-filecoin/blob/c266d961029599d090926f7c90490e9b7dcf5fd2/internal/pkg/block/block.go#L65)

**Comment by melekes** [comment]
> i.e. libp2p integration

The only place where cid is being used in go-libp2p is https://github.com/libp2p/go-libp2p/blob/c73d2b9c8ee65326fe6c1b76a05a6b6cdcf223b9/p2p/host/relay/autorelay_test.go#L65, which is a mock object used for testing. So not sure how it helps.

> I checked FileCoin project, They preferred using CID to refer a block

Interesting. I guess for them the major reason was that files (blocks) are usually stored on IPFS

**Comment by melekes** [comment]
https://github.com/tendermint/tendermint/pull/3981#issuecomment-537149969

**Pull request closed without merging**
