### PR TITLE
docs: P2P Documentation

### PR DESCRIPTION
**Pull request by adrianbrink**

### CODE REVIEW

**Comment by adrianbrink** [comment]
Crap I just realised that this won't allow us to comment on the files.

**Comment by milosevic** [comment]
Could you touch files and push a new commit? I have few comments, so it would be nice doing it in the context of this PR.

**Comment by ebuchman** [comment]
ill open a new one

**Comment by ebuchman** [comment]
https://github.com/tendermint/tendermint/pull/1057

**Comment by adrianbrink** [comment]
#1058 @ethanfrey

**Pull request merged**
