### PR TITLE
release/0.32.12

### PR DESCRIPTION
**Pull request by tessr**
Prepares release 0.32.12.

### CODE REVIEW

**Comment by tessr** [comment]
I think some of this is related to the problem you fixed in https://github.com/tendermint/tendermint/pull/4816 

I'm going to try cherry picking that too, and then will push again

**Comment by tessr** [comment]
Regarding the contract tests, it looks like @marbar3778 commented them out on master. Marko, can you get Erik and I up to speed on what's going on with the contract tests?

**Comment by marbar3778** [comment]
since we upgraded from openAPI 2.0 to 3.0 it fails because teh tool dredd does not have full support for openAPI 3.0. I tested last week and this is still the case. 

https://github.com/tendermint/tendermint/issues/4229

**Comment by tessr** [comment]
Cool, thanks for the explanation. I'm going to just ignore it for this backport bug fix release, but maybe on master we can just delete the test and add it back once dredd is updated?

**Comment by marbar3778** [comment]
oh this is not the case in 0.32 sorry. I just looked at the ci job in circle and it is failing because the json outputted from RPC is different than what is documented in the swagger file

**Comment by tessr** [comment]
do you know if there's a commit I can cherry pick for that or is that going to be a new PR?

**Comment by marbar3778** [comment]
I think we can leave for this release and we can go back later, if it's fine with others? We don't do versioned docs and don't display the swagger docs at "/" so it's not that big of a deal.

**Pull request merged**
