### PR TITLE
Update Makefile

### PR DESCRIPTION
**Pull request by marbar3778**
- these two files were taken from the sdk with adjustments for usage in TM

Signed-off-by: Marko Baricevic <marbar3778@yahoo.com>

* [ ] Referenced an issue explaining the need for the change
* [ ] Updated all relevant documentation in docs
* [ ] Updated all code comments where relevant
* [ ] Wrote tests
* [ ] Updated CHANGELOG_PENDING.md

### CODE REVIEW

**Comment by marbar3778** [comment]
@jackzampolin can you `configuration version 2.1 requires the "Enable Pipelines" project setting. Enable pipelines under Project Settings -> Advanced Settings. In order to retrigger pipelines, you must push a new commit.`

**Comment by mircea-c** [comment]
@marbar3778 I've enabled pipelines on the project

**Comment by marbar3778** [comment]
Thank you, I can work on this later, could you enable ci cancellation when you push before the previous one is over as well?

**Comment by mircea-c** [comment]
Already did :smile:

**Pull request merged**
