### PR TITLE
p2p: do not log err if peer is private

### PR DESCRIPTION
**Pull request by melekes**
Should replace https://github.com/tendermint/tendermint/pull/3463

### CODE REVIEW

**Comment by guagualvcha** [comment]
Ebarrassing scene: I get a sentry node which would be public in p2p network, it will connect to validators as its persistent peers, and validators are served as private peers.
If I set `addr_book_strict ` to be true, sentry keep report error log. If I set `addr_book_strict ` to be false, validator address will pexed by sentry node.

**Comment by melekes** [comment]
Right! What if we reorder checks in `addrbook#addAddress()` to return `ErrAddrBookPrivate` if the address is private and we do not log it as error? Note you'll need to add validators ids to `private_peer_ids` in config.toml.

**Comment by melekes** [comment]
@guagualvcha see https://github.com/tendermint/tendermint/pull/3474/commits/a92e4347a6f93b688389646ed05dc3e545770886

**Comment by guagualvcha** [comment]
> @guagualvcha see [a92e434](https://github.com/tendermint/tendermint/commit/a92e4347a6f93b688389646ed05dc3e545770886)

thks, That will be good

**Comment by melekes** [comment]
TODO:

- [ ] verify output manually

**Comment by melekes** [comment]
@guagualvcha have you tried applying this patch?

**Pull request merged**
