### PR TITLE
Revert "rpc: re-index missing events"

### PR DESCRIPTION
**Pull request by JayT106**
Reverts tendermint/tendermint#6535
reason: 
https://github.com/tendermint/tendermint/pull/6535#pullrequestreview-693315894
Will introduce a new Tendermint command to execute the re-index as a backend process instead of the rpc call.

### CODE REVIEW

**Comment by JayT106** [comment]
ref:
https://github.com/tendermint/tendermint/pull/6535#pullrequestreview-693315894

**Review by alexanderbez — APPROVED** [review]

**Review by alexanderbez — COMMENTED** [review]
Do we have a changelog entry we need to revert too?

**Comment by JayT106** [comment]
> Do we have a changelog entry we need to revert too?

Didn't update the changelog in the original PR.

**Comment by marbar3778** [comment]
do we have a new design in mind? This is a useful feature

**Comment by alexanderbez** [comment]
@JayT106 is working on a non-RPC CLI-based approach. We can't have this as part of the RFC interface unless we make it stateful which will require more thought and probably an ADR.

**Pull request merged**
