### PR TITLE
Fix and clarify breaks from case clauses.

### PR DESCRIPTION
**Pull request by creachadair**
The beginnings of a fix for #6780.

File list:

    % staticcheck -checks SA4011 ./... | cut -d: -f-2

This change is intended to be semantics-preserving, at least for the intended
semantics of the code. It is NOT strictly behaviour-preserving, however.
Specifically: On some inputs, these loops may have run longer than they were
intended to, prior to this change.

There is one case where I was not sure how to resolve the ambiguity.
This is flagged as FIXME in the commit.

### CODE REVIEW

**Comment by creachadair** [comment]
For reviewers: Although these changes are small and local, please look carefully at each, since they go to control flow.

I suspect the codecov failure is spurious, but I'm not able to view the logs from that run, so I'm not certain.

**Review by tychoish — APPROVED** [review]
I've always found all caps for loop labels to be easier to read/scan/find, but I don't feel super strongly about this?

**Comment by creachadair** [comment]
> I've always found all caps for loop labels to be easier to read/scan/find, but I don't feel super strongly about this?

Effective Go and https://github.com/golang/go/wiki/CodeReviewComments generally recommend following the same naming for labels as for other identifiers. I named them this way on that basis, but I don't feel very strongly about it. I _do_ think that we should eschew C-style CAPITAL_SNAKE_CASE, though.

**Comment by tychoish** [comment]
> Effective Go and https://github.com/golang/go/wiki/CodeReviewComments (cf. e.g., https://github.com/golang/go/wiki/CodeReviewComments#mixed-caps) generally recommend following the same capitalization for labels as for other identifiers. I named them this way on that basis, but I don't feel very strongly about it. I do think that we should eschew C-style CAPITAL_SNAKE_CASE, though.

Agreed about snake case. I _really_ don't feel strongly, and I think having different capitalization schemes for different kinds of labels can be the first step towards insanity, so this is probably better, but there was definitely a part of me that enjoyed the other way. All is well.

**Comment by creachadair** [comment]
> Agreed about snake case. I _really_ don't feel strongly, and I think having different capitalization schemes for different kinds of labels can be the first step towards insanity, so this is probably better, but there was definitely a part of me that enjoyed the other way. All is well.

Would you find it more comfortable to read if, say, we use a leading capital on labels? E.g., `IterExists` instead of `iterExists`?

**Comment by tychoish** [comment]
> Would you find it more comfortable to read if, say, we use a leading capital on labels? E.g., IterExists instead of iterExists?

I don't think it matters much. I think how you have it is totally fine.

**Pull request merged**
