### PR TITLE
backport ci migration

### PR DESCRIPTION
**Pull request by marbar3778**
## Description

_Please add a description of the changes that this PR introduces and the files that
are the most critical to review._ 

ref: #5757

### CODE REVIEW

**Comment by marbar3778** [comment]
Linting is failing, do we want to fix these as well? I would open a new pull request for it. They are failing because golangci got stricter on items in the new versions.

**Review by erikgrinaker — APPROVED** [review]
We may not want to bump golangci-lint here, since it's got a bunch of failures. Alternatively, backport or fix the lint complaints.

**Comment by marbar3778** [comment]
> We may not want to bump golangci-lint here, since it's got a bunch of failures. Alternatively, backport or fix the lint complaints.

I am up for a backport of fixes. If we bump the version we can get more errors.

**Comment by marbar3778** [comment]
Reverting to 1.26 golangci forces me to use v1 of the action. The action is using deprecated commands of github actions, this causes the action to show failure but the linting passes.

**Comment by marbar3778** [comment]
Test Coverage / tests (02) is non deterministic, locally I'm not able to reproduce this.

**Review by melekes — APPROVED** [review]

**Pull request merged**
