### PR TITLE
backport light client changes

### PR DESCRIPTION
**Pull request by erikgrinaker**
As discussed in https://github.com/tendermint/tendermint/pull/5534#issuecomment-712936604, this backports #5375 and the related light client PRs #5392, #5429, #5393 in order to avoid tons of merge conflicts.

**Remember to rebase-merge**

@melekes @cmwaters Can you confirm that these PRs are good to backport, and that they're not too breaking and don't have much potential to introduce serious bugs?

Alternatively, we can postpone these changes for 0.35, and I'll do the necessary lint fixes in #5534 by hand.

### CODE REVIEW

**Comment by cmwaters** [comment]
I don't think any of these changes are breaking, perhaps only to the light client cli. And as far as potential bugs go I'm not sure how thorough the abci query has been tested but if there is a problem it will just break that call (abci_query) - same with the validators and commit.

**Comment by erikgrinaker** [comment]
> Would we want to wait till the light client model based testing is merged or is that not really necessary? 

I think we can follow up with them once they land - if there are any bugs, we can fix and backport them then.

**Review by cmwaters — APPROVED** [review]
Okay then we should be good to merge ( & rebase)

**Comment by erikgrinaker** [comment]
Great! I'd like to hear from @melekes first as well, just in case, but seems like it should be fine.

**Comment by melekes** [comment]
> the abci query has been tested but if there is a problem it will just break that call (abci_query) - same with the validators and commit.

it's was not working before, so I wouldn't consider fixing something a breaking change

**Comment by melekes** [comment]
> @melekes @cmwaters Can you confirm that these PRs are good to backport, and that they're not too breaking and don't have much potential to introduce serious bugs?

fine by me

**Pull request merged**
