### PR TITLE
rpc: fix content-type header

### PR DESCRIPTION
**Pull request by alexanderbez**
## Description

Fix the `Content-Type` header in RPC responses.

Closes: #5660

### CODE REVIEW

**Comment by tessr** [comment]
Can you add a changelog entry for this? If any applications are paying attention to this, they probably would like to know

**Review by tessr — APPROVED** [review]

**Comment by alexanderbez** [comment]
@tessr yes, of course. How could that have slipped my mind!

**Review by marbar3778 — APPROVED** [review]

**Comment by tessr** [comment]
And can you also backport for 0.34? We have a branch: RC7/v0.34.0 😀

**Comment by alexanderbez** [comment]
Cherrypick this into the rc7 branch?

**Comment by tessr** [comment]
@alexanderbez yes, exactly!

**Comment by alexanderbez** [comment]
done => https://github.com/tendermint/tendermint/pull/5669

:)

**Pull request merged**
