### PR TITLE
light: convert validation panics to errors

### PR DESCRIPTION
**Pull request by tychoish**
These functions already handled errors, and did some input validation
without panicing, so this seems safe.

### CODE REVIEW

**Comment by cmwaters** [comment]
Some context on this: So we require that the caller passes in the entire header although for verification we only need a few of the fields. IBC don't want to have to store entire headers so they create a partially filled header when verifying. We wanted to check that those minimum amounts of fields had been filled. My idea originally was to just add the fields we need as explicit arguments in the function however someone else wanted to keep passing through the header and but add these panics so that's what we did.

**Review by creachadair — APPROVED** [review]

**Comment by tychoish** [comment]
> Some context on this: So we require that the caller passes in the entire header although for verification we only need a few of the fields. IBC don't want to have to store entire headers so they create a partially filled header when verifying. We wanted to check that those minimum amounts of fields had been filled. My idea originally was to just add the fields we need as explicit arguments in the function however someone else wanted to keep passing through the header and but add these panics so that's what we did.

This makes sense, I think, but having two ways of error handling is more confusing from the API and changing the panics to errors doesn't change the results of any of the functions or your responsibility as a caller. Does that make sense @cmwaters

**Comment by cmwaters** [comment]
> This makes sense, I think, but having two ways of error handling is more confusing from the API and changing the panics to errors doesn't change the results of any of the functions or your responsibility as a caller. Does that make sense @cmwaters

What do you mean by two ways of error handling?

**Comment by cmwaters** [comment]
My original suggestion was just that you change the function signature from:
```
func VerifyNonAdjacent(
	trustedHeader *types.SignedHeader, // height=X
	trustedVals *types.ValidatorSet, // height=X or height=X+1
	untrustedHeader *types.SignedHeader, // height=Y
	untrustedVals *types.ValidatorSet, // height=Y
	trustingPeriod time.Duration,
	now time.Time,
	maxClockDrift time.Duration,
	trustLevel tmmath.Fraction) error {
```
to
```
func VerifyNonAdjacent(
	trustedHeight int64,
        trustedTime time.Time,
        trustedChainID string,
	trustedVals *types.ValidatorSet, // height=X or height=X+1
	untrustedHeader *types.SignedHeader, // height=Y
	untrustedVals *types.ValidatorSet, // height=Y
	trustingPeriod time.Duration,
	now time.Time,
	maxClockDrift time.Duration,
	trustLevel tmmath.Fraction) error {
```
That way you don't need panics at all

**Review by cmwaters — APPROVED** [review]
:)

**Pull request merged**
