### PR TITLE
types: nuke types directory

### PR DESCRIPTION
**Pull request by alexanderbez**
I tried to initially only move "block" related types from `types/` to `pkg/block`. However, I quickly found out the types are so intertwined, that nearly half of the `types/` package had to be carried over.

Thus we now have:

- removed `types/`
- added `pkg/block/`
- added `pkg/block`
- added `pkg/consensus`
- added `pkg/events`
- added `pkg/evidence`
- added `pkg/mempool`
- added `pkg/meta` - for Commit, Header, and BlockID
- added `pkg/p2p`
- move `abci/types` to `pkg/types`

### CODE REVIEW

**Comment by cmwaters** [comment]
I've split `types` across the following subdomains:
- pkg/block
- pkg/consensus
- pkg/events
- pkg/evidence
- pkg/mempool
- pkg/meta- for Commit, Header, and `BlockID
- pkg/p2p

**Comment by creachadair** [comment]
The new organization seems reasonable to me. My only nit-pick is that all the names are spelled out (not abbreviated) except `meta`, which I think would read better as `metadata`.

**Comment by tychoish** [comment]
I guess looking at this from the top down, without looking at the code, it sort of seems hard for me to see how "meta" which seems like it has a lot of "block-adjacent" things shouldn't just be part of block? 

Also, while "consensus" is a domain that we use internally, is it a domain that makes sense to people who aren't steeped in tendermint core? I'm convinced that evidence and events and block make sense externally, but less so for consensus and maybe even mempool.

**Comment by cmwaters** [comment]
> My only nit-pick is that all the names are spelled out (not abbreviated)

are you meaning p2p in particular? I don't see how the others are abbreviated (I guess mempool perhaps). 

> I guess looking at this from the top down, without looking at the code, it sort of seems hard for me to see how "meta" which seems like it has a lot of "block-adjacent" things shouldn't just be part of block?

I originally wanted it to be in block but it causes import cycles so I decided to break up block to import its parts: `meta` which contains `Header` and `Commit`; `mempool` which contains `Txs` and `evidence` which contains `Evidence`.  Thus `block` is the struct that almagamates these parts.

> Also, while "consensus" is a domain that we use internally, is it a domain that makes sense to people who aren't steeped in tendermint core?

Valid point. Although I would think the notion of consensus to be widely associated with Tendermint. Are we not just a consensus engine with a few extra add ons? 

If you have alternatives. I would be happy to hear them out.

**Comment by creachadair** [comment]
> > My only nit-pick is that all the names are spelled out (not abbreviated)
> 
> are you meaning p2p in particular? I don't see how the others are abbreviated (I guess mempool perhaps).

I think of `mempool` as a term of art, rather than an abbreviation (although arguably it is that also). Similarly `p2p`. The one I was nitpicking about is `meta` which I think should be spelled out `metadata`. It reads better (IMO) at the usage site to see, e.g., `metadata.BlockID` than `meta.BlockID`. Acknowledged, however, that this is a purely cosmetic opinion.

**Comment by cmwaters** [comment]
Sure. 

If we didn't have `meta`:

`block` imports `evidence` imports `consensus` imports `block`

If we merge this all together then we kind of go back to a all in one `types`-like package

**Comment by cmwaters** [comment]
I think (hope) this is almost ready - just trying to clean up the last bits.

Aside from updating all the dependency paths to make sure everything compiles and passes the only additional change I made was to move the contents of `abci/types` into `pkg/abci`.

**Comment by cmwaters** [comment]
UPDATE: Following on from a call yesterday, the team agreed to hold out on making any refactor to the types package till after the release of 0.35. The decision is predominantly motivated because we feel the design of the structure of the repo requires more thought and time and there is a desire to just focus on the upcoming release. I'm going to close this PR but it is expected we will return to the issue sometime in the future.

**Pull request closed without merging**
