### PR TITLE
[WIP] Specifying endpoints query parameters everywhere

### PR DESCRIPTION
**Pull request by nanspro**
* [x] Updated CHANGELOG_PENDING.md

Relates to #3618

### CODE REVIEW

**Comment by nanspro** [comment]
@ebuchman i didn't get any response to this https://github.com/tendermint/tendermint/issues/3618#issuecomment-503451865 and i was not sure what the scope of this issue was, differentiating between endpoints having no parameters and endpoints having some can be done in many ways so i choose to specify query parameters for all the api calls.
One more differentiation can be seen [here](https://tendermint.com/rpc/?shell#get-the-list), in the shell you can see which calls require parameters or not.

**Comment by marbar3778** [comment]
`bump` any update with this PR?

**Comment by ebuchman** [comment]
Thanks for this. The extra documentation is certainly super helpful.

The idea was really to indicate the distinction on the main page (ie. `<url>:26657/`). It used to look like what's in the documentation you linked to, but in the current build the section `Available endpoints:` is empty and all endpoints are listed under `Endpoints that require arguments:`.  This is what we're looking to fix!

**Comment by marbar3778** [comment]
`Ping` is there an update on this PR?

**Comment by melekes** [comment]
Closing this since no updates have been made.

**Pull request closed without merging**
