### PR TITLE
remove deprecated TM_HOME

### PR DESCRIPTION
**Pull request by zramsay**

### CODE REVIEW

**Comment by melekes** [comment]
Didn't we want to get rid of TMHOME because TM_XXX is how viper does env?

**Comment by zramsay** [comment]
hmm, we use `TMHOME` everywhere. can be broken if we want to...

**Comment by melekes** [comment]
```
--- FAIL: TestRootConfig (0.01s)
        <autogenerated>:1: ^M                          ^M       Error Trace:    root_test.go:98
                ^M      Error:          Not equal:
                ^M                      expected: "/root/.some/test/dir"
                ^M                      actual: "/tmp/test-cli215393040"
                ^M      Messages:       3
        <autogenerated>:1: ^M                          ^M       Error Trace:    root_test.go:99
                ^M      Error:          Not equal:
                ^M                      expected: "/root/.some/test/dir"
                ^M                      actual: "/tmp/test-cli215393040"
                ^M      Messages:       3
        <autogenerated>:1: ^M                          ^M       Error Trace:    root_test.go:100
                ^M      Error:          Not equal:
                ^M                      expected: "/root/.some/test/dir"
                ^M                      actual: "/tmp/test-cli215393040"
                ^M      Messages:       3
        <autogenerated>:1: ^M                          ^M       Error Trace:    root_test.go:101
                ^M      Error:          Not equal:
                ^M                      expected: "/root/.some/test/dir"
                ^M                      actual: "/tmp/test-cli215393040"
                ^M      Messages:       3
        <autogenerated>:1: ^M                          ^M       Error Trace:    root_test.go:102
                ^M      Error:          Not equal:
                ^M                      expected: "9879aebb3f84"
                ^M                      actual: "monkey"
                ^M      Messages:       3
        <autogenerated>:1: ^M                          ^M       Error Trace:    root_test.go:103
                ^M      Error:          Not equal:
                ^M                      expected: true
                ^M                      actual: false
                ^M      Messages:       3
        <autogenerated>:1: ^M                          ^M       Error Trace:    root_test.go:98
                ^M      Error:          Not equal:
                ^M                      expected: "/root/.some/test/dir"
                ^M                      actual: "/tmp/test-cli215393040"
                ^M      Messages:       4
        <autogenerated>:1: ^M                          ^M       Error Trace:    root_test.go:99
                ^M      Error:          Not equal:
                ^M                      expected: "/root/.some/test/dir"
                ^M                      actual: "/tmp/test-cli215393040"
                ^M      Messages:       4
        <autogenerated>:1: ^M                          ^M       Error Trace:    root_test.go:100
                ^M      Error:          Not equal:
                ^M                      expected: "/root/.some/test/dir"
                ^M                      actual: "/tmp/test-cli215393040"
                ^M      Messages:       4
:
```

**Comment by melekes** [comment]
Please fix the tests and reopen 🐱

**Comment by ethanfrey** [comment]
TMHOME is what bucky wanted.
TM_HOME is the standard from viper, which gives it to us.

I worked so that TMHOME is translated to TM_HOME, and viper is happy.
Disabling the alternate spelling seems like an anti-feature to me.

**Pull request closed without merging**
