### PR TITLE
Moves the PBTS ADR to Accepted list

### PR DESCRIPTION
**Pull request by lasarojc**
ditto
---

#### PR checklist

- [x] Tests written/updated, or no tests needed
- [x] `CHANGELOG_PENDING.md` updated, or no changelog entry needed
- [x] Updated relevant documentation (`docs/`) and code comments, or no
      documentation updates needed

### CODE REVIEW

**Comment by jmalicevic** [comment]
Is it still accepted with regards to 0.37?

**Comment by thanethomson** [comment]
I suspect we should only mark this as "Accepted" once we've planned it into a specific release. Right now that seems to be v0.39 or later?

**Comment by lasarojc** [comment]
Ok. I proposed the change because the status on the ADR itself says
Proposed. Maybe that should be reverted then?

**Review by thanethomson — APPROVED** [review]
As per discussion in our team meeting today, let's move this to the accepted section. Just because it's accepted doesn't mean it's been implemented, nor does it give any indication about when it's going to be scheduled for implementation and release.

We can add the tracking issue to the ADR once I've created that issue.

**Pull request merged**
