### PR TITLE
Backport priority mempool fixes from v0.35.x to v0.34.x.

### PR DESCRIPTION
**Pull request by creachadair**
This is a manual backport of the changes from these commits:

- bc49f66 Add more unit tests for the priority mempool. (#8961)
- 9b02094 Fix unbounded heap growth in the priority mempool. (#8944)

Imports and type signatures have been updated to match the v0.34 usage.

### CODE REVIEW

**Review by tychoish — APPROVED** [review]
This is amazing.

**Comment by creachadair** [comment]
> This is amazing.

All the groundwork was laid by @jmalicevic and @cmwaters.  Otherwise, mainly a vindication of the value of `git worktree`.

**Comment by williambanfield** [comment]
# Experimental Results
To verify that this backport fixed the issue and was correct, the mempool with and without the fix was run in a large testnet.

## Testnet Setup
Software Version: 9b0209482736bf012df08ea9633fd542d7e52ceb
124 Total Nodes:
100 Validator Nodes
4 Seed Nodes
20 Full Nodes
Machine: Debian 11 with 4 virtual CPUs and 8 GB of ram.  

## Experimental Runs

2 Experiments were run comparing performance of the mempool presenting the issue and the mempool with the fixes. 

For load generation the [runner](https://github.com/tendermint/tendermint/blob/51685158fe36869ab600527b852437ca0939d0cc/test/e2e/runner/load.go) load generation command from version 51685158fe36869ab600527b852437ca0939d0cc
 was run on 10 out of the 100 validator nodes, generating a steady transaction load to the validator running on the same machine. The transactions were randomly generated up to a size of 1024 bytes using 32 worker go routines to send the load.

### Title: Buggy Mempool
Duration: 4h

Memory Usage
memory

CPU Utilization
cpu

Mempool Size
size

Tx Rate
txrate

### Title: Updated Mempool
Duration: 10m
Mempool version: v1
Load: None

memory

CPU Utilization
cpu

Mempool Size
size


Tx Rate
txrate


### Summary
v1 Mempool reaches steady memory usage and does not appear to exhibit unbounded growth. The buggy mempool, on not a very large timescale, exhibits the unbounded growth. 
For both, tx are consistently reaped for consensus.

**Comment by Princeobinna** [comment]
Approve all assets

**Pull request merged**
