### PR TITLE
[ADR][DRAFT] 024: SignBytes and validator types in privval

### PR DESCRIPTION
**Pull request by Liamsi**
Work in progress: Quick fledged draft summarizing https://github.com/tendermint/tendermint/issues/1622

If time allows, please review for overall sanity (not typos/nitpicks):
https://github.com/tendermint/tendermint/blob/5d46a2d49dba4da726463ba43058c6b230e3d24a/docs/architecture/adr-02x-sign-bytes.md

* [ ] Updated all relevant documentation in docs
* [ ] Updated all code comments where relevant
* [ ] Wrote tests
* [ ] Updated CHANGELOG_PENDING.md

### CODE REVIEW

**Comment by Liamsi** [comment]
@tarcieri also suggested as while ago to include the public-key / fingerprint thereof into each "SignRequest" sent by tendermint. E.g. the KMS holds a bunch of key-pairs and needs to know which priv-key of those to use to sign Votes, Proposals, or Hearbeats. This is probably quite important. I still left it away here as I assume the implied changes to be quite involved already.

**Comment by zmanian** [comment]
IMO there is a lot of scope for improving the validator socket protocol lets focus on getting the MVP working with KMS before we add important features like key ids and and error handling.

**Comment by Liamsi** [comment]
@zmanian: OK, I'll open an issue and a PR that just moves `SignBytes(chainId string)` to be amino encoded and leave everything else as it is now (including leaving the fields variable sized). We can change this incrementally instead. It is still worthwhile to have this discussion earlier than later. As I assume we will change the structs before launch (and the kms needs to catch up with these changes then).

**Comment by xla** [comment]
Error handling should be considered part of an MVP.

**Pull request merged**
