### PR TITLE
[WIP] [ADR] ADR-36: Giving the app control over proposer selection

### PR DESCRIPTION
**Pull request by b00f**
Adr-036 Initial commit

### CODE REVIEW

**Comment by b00f** [comment]
In favor of #3285 and #3325

**Comment by b00f** [comment]
Tendermints wants to do everything by itself and the Application just check the transaction validity. I believe Tendermint should give more responsibility to the app!

**Comment by melekes** [comment]
Thank you for writing this 👍 Do you also want to expand on the interface allowing application to supply another proposer selection algorithm?

**Comment by b00f** [comment]
> Do you also want to expand on the interface allowing application to supply another proposer selection algorithm?

Yes, Tendermint can give this option to the application to select the proposer for next round.

**Comment by ebuchman** [comment]
This needs more work but it's fine to merge as is as a starting point. But it should be changed to ADR-041 (see https://github.com/tendermint/tendermint/issues/2313).

@b00f can you give us permission to commit to this repo?

**Comment by ebuchman** [comment]
I'll just deal with it thanks.

**Pull request merged**
