### PR TITLE
light: ensure required fields are present for verification

### PR DESCRIPTION
**Pull request by cmwaters**
## Description

A little bit of coding a day keeps the doctor away :apple: 

Earlier Approach:

Verification for the light client requires an entire trusted header but most of these fields aren't necessary hence I've streamlined the go API a little more by removing them. 

Later Implementation:

Instead of changing the function signature, Verification introduces panics as a mechanism to ensure that developers have the correct fields.

Closes: #5300

### CODE REVIEW

**Comment by melekes** [comment]
Instead of removing the `trustedHeader` and making functions with too many parameters, we can make sure all required fields are present, which should solve the issue. Of course, I would instead prefer for language to handle this for me, similarly to how Clojure does https://clojure.org/guides/spec, but since Go is Go, we don't have a luxury.

```clj
(s/def ::header (s/keys :req [::chain-id ::height ::next-validator-hash]
                        :opt [::validator-hash]))
```

**Comment by cmwaters** [comment]
Would the Verify functions just panic if the header had zero values for one of the required fields? 

Is too many parameters a problem? We already had 8 before hand and this PR just jumps it up to 11.

**Comment by melekes** [comment]
> Would the Verify functions just panic if the header had zero values for one of the required fields?

yep

> Is too many parameters a problem? We already had 8 before hand and this PR just jumps it up to 11.

kinda, yes. but the bigger problem is that you're deconstructing the aggregate - i.e. breaking logical connection between fields. chainID and next_validator_set_hash are not two  nrelated things. they are part of header. I hope you see what I mean. Of course, no one forbids us from breaking Verify func even further and, say, breaking untrustedHeader into individual fields (+3 or 4 params), but it's just not a good way to go from what I can see.

**Comment by cmwaters** [comment]
I guess I was accommodating for the case of IBC where they have these variables but need to construct partial headers to run the Verify function. Also by having these parameters in the function signature it's clearer as to what is required for verification. But yeah I understand your point that these variables should, in the logical sense, be grouped together

**Comment by melekes** [comment]
> Also by having these parameters in the function signature it's clearer as to what is required for verification. 

there are pros and cons, sure. But it's a dangerous road. If we're deconstructing objects, why not break untrustedHeader and only require fields we're using from it instead of the whole object?

**Review by melekes — APPROVED** [review]

**Review by alexanderbez — APPROVED** [review]

**Pull request merged**
