### PR TITLE
privval: avoid re-signing vote when RHS and signbytes are equal

### PR DESCRIPTION
**Pull request by maxkaneco**
It seems sign procedure is always performed when RHS and signbytes are equal

### CODE REVIEW

**Review by cmwaters — APPROVED** [review]
Makes sense to me. Thanks for the contribution.

@williambanfield do you mind double checking that the PBTS work doesn't require any change of behaviour with the Privval (specifically when signing the same block with a different timestamp)

**Comment by tychoish** [comment]
Is there a way to write a test for this?

**Comment by williambanfield** [comment]
@cmwaters, thanks for the ping. I just checked this over. The case of re-using the proposal signature if the timestamps differ should be removed.

**Review by williambanfield — APPROVED** [review]

**Comment by williambanfield** [comment]
Thanks for the contribution @maxkaneco !

**Pull request merged**
