### PR TITLE
Adding appData to the block header

### PR DESCRIPTION
**Pull request by b00f**
Update blockhedaer to add application custom data related to #1855 

* [X] Updated all relevant documentation in docs
* [X] Updated all code comments where relevant
* [X] Wrote tests
* [ ] Updated CHANGELOG.md

### CODE REVIEW

**Comment by b00f** [comment]
@melekes , Thanks for your response.  I absolutely understand your concern. I tried to not make any big change in the state machine. I know you guys are so busy and might not have time to check this change, In case you need any question let me know.

**Comment by melekes** [comment]
> In case you need any question let me know.

check out https://github.com/tendermint/tendermint/issues/1855#issuecomment-405216689

**Comment by b00f** [comment]
> check out #1855 (comment)
If I am not mistaken the `ProposerTx` is an special internal tx to make tendermint more compatible with Plasma architecture. Still I need to reed more about it. 
However during committing a block, the application maybe need to store some information related to delivered txs. I don't think we can do it with `ProposerTx`. Please let me know if you have better idea....

**Comment by melekes** [comment]
Closing for discussion in https://github.com/tendermint/tendermint/issues/1855.

**Comment by b00f** [comment]
Could you please reopen this PR due to this issue #1855

**Comment by melekes** [comment]
Could you submit a new PR? Did you write an ADR?

**Comment by b00f** [comment]
I added a new ADR related to this request, please review it #2752 
I will send a PR after this ADR get approve.

**Pull request closed without merging**
