### PR TITLE
Feature/devdoc

### PR DESCRIPTION
**Pull request by jaekwon**
* Deterministic builds using tendermint/devdoc

### CODE REVIEW

**Comment by adrianbrink** [comment]
Tested at length yesterday with Jae. Works on my machine ;-)

**Comment by adrianbrink** [comment]
Is this also deterministic for other platforms besides `darwin_amd64`?

**Comment by melekes** [comment]
I don't like some parts of this PR (like `build_darwin_amd64` target or `gox` removal without removing it from scripts/dist_build.sh).

**Comment by ebuchman** [comment]
Closing for future discussion

**Pull request closed without merging**
