### PR TITLE
if some process locks a block in round 0, then 0 is valid proposal.PO…

### PR DESCRIPTION
**Pull request by melekes**
…LRound in rounds > 0

This condition is really hard to get. Initially, lockedRound and
validRound are set to -1 as we start with round 0.

Refs #2702

* [ ] Updated all relevant documentation in docs
* [x] Updated all code comments where relevant
* [ ] Wrote tests
* [ ] Updated CHANGELOG_PENDING.md

### CODE REVIEW

**Comment by ebuchman** [comment]
Closing for https://github.com/tendermint/tendermint/pull/2735/

@milosevic please confirm

**Comment by melekes** [comment]
I think changes here make the code better&more readable (NOTE they do not fix/change anything)

**Comment by ebuchman** [comment]
Ah right, happy to bring that in, but it  looks like it changes the logic to allow POLRound to equal the current round which I don't think we want.

**Comment by melekes** [comment]
No, it will return err if `proposal.POLRound >= proposal.Round`

**Pull request merged**
