### PR TITLE
e2e: add evidence tests

### PR DESCRIPTION
**Pull request by cmwaters**
Closes: #9237

### CODE REVIEW

**Comment by sergio-mena** [comment]
Are these changes coming from a merged PR, or are the brand new code?

**Comment by cmwaters** [comment]
It's predominantly coming from https://github.com/tendermint/tendermint/pull/6276 but it seems there were also changes made in other commits that need to be there to make it work

**Comment by sergio-mena** [comment]
#9254 was merged into `feature/abci++ppp`. Shouldn't we merge this PR also into the branch, to resolve possible conflicts upfront?

**Comment by sergio-mena** [comment]
I went through this PR and I'm now more convinced this should be merged into `feature/abci++ppp`, because this PR is bringing back testing infra into `internal/test` which has also been modified in the feature branch. So we should solve any inconsistencies in the branch, and not wait for the bigger merge of the branch into `main`.

**Comment by cmwaters** [comment]
Sure, I can change the base to `feature/abci++ppp`

**Comment by cmwaters** [comment]
Hmm that was more difficult than I thought. Anyway closing this in favour of #9292

**Pull request closed without merging**
