### PR TITLE
test/fuzz: add current fuzzing to oss-fuzz-build script

### PR DESCRIPTION
**Pull request by cuonglm**
So oss-fuzz can start building and continuous fuzzing these packages.

Updates #6557

### CODE REVIEW

**Comment by cuonglm** [comment]
cc @odeke-em

**Review by alexanderbez — COMMENTED** [review]
How and where is this executed?

**Comment by odeke-em** [comment]
>How and where is this executed?

@alexanderbez, oss-fuzz will examine the script that @cuonglm has put up, and run the fuzzers continously in parallel, after we get https://github.com/google/oss-fuzz/pull/5907 merged, but that'll run after this change has been merged :-)

**Review by alexanderbez — APPROVED** [review]

**Comment by odeke-em** [comment]
@cuonglm please update this branch. Kindly cc-ing @marbar3778 to help with a merge :-)

**Pull request merged**
