### PR TITLE
help peer that is stuck at waiting for commit block

### LINKED ISSUE #3721: The sequence of gossipCatchup for votes and blockparts
Now, gossipVotesRoutine and gossipDataRoutine are two seperate routines and execute independently. Func gossipDataForCatchup will send the peer with historical block parts, but we should wait for gossipVotesRoutine send all the required 2/3+ precommits to it before sending the block parts, we'd better have a mechanism to control these two processes.
Otherwise what if all the peers have sent a part they assumed the recipient has received, but in fact  the recipient kept rejecting this part because it lacks the required 2/3+ precommits, but when it collected the votes, all the peers assumed it has that part and never send to it again.

### PR DESCRIPTION
**Pull request by james-ray**
fix #3721

### CODE REVIEW

**Comment by james-ray** [comment]
how to make this bug appear:

1. let the proposal block be as small as possible: empty block or only containing 1 tx.
2. Let the number of validators be relatively bigger, for example, we deploy 11 nodes, or 21 nodes, to let the number of votes be relatively bigger,  thus the process of collecting catchup votes takes longer time than collecting block parts. So the recipient discards the block parts when it does not collect 2/3+ precommit.
3. We isolate the network of one of the nodes to let its height lag behind to others' heights. We can simply kill -19 the process.

**Comment by williambanfield** [comment]
Hey @james-ray, I'm not completely sure I understand this change. From what I can tell, this is trying to guard against the case that a lagging peer may have discarded a block in the round that it's in. I'm not yet sure I know why that would happen, do you have a clear case in the code where this occurs?

**Comment by james-ray** [comment]
> Hey @james-ray, I'm not completely sure I understand this change. From what I can tell, this is trying to guard against the case that a lagging peer may have discarded a block in the round that it's in. I'm not yet sure I know why that would happen, do you have a clear case in the code where this occurs?

The err log is like
first in addProposalBlockpart:
```
// We're not expecting a block part.
	if cs.ProposalBlockParts == nil {
		cs.metrics.BlockGossipPartsReceived.With("matches_current", "false").Add(1)
		// NOTE: this can happen when we've gone to a higher round and
		// then receive parts from the previous round - not necessarily a bad peer.
		cs.logger.Debug(
			"received a block part when we are not expecting any",
			"height", height,
			"round", round,
			"index", part.Index,
			"peer", peerID,
		)
		return false, nil
	}
```
this log occurs
```
received a block part when we are not expecting any"
```
then in enterCommit
```
{"log":"I[07-04|02:41:28.761] Attempt to finalize failed. We don't have the commit block. module=consensus height=122 proposal-block= commit-block=054237363232575CE06150B2C93D78E4B405A6251ACEFFB2DF
```

To test this case, we need to kill -19 to hang a node process, to make its height lag behind the others, then kill -18 to recover, during the catchup phase, this error would occur in a very high probability.

**Comment by james-ray** [comment]
We cannot stop the node, because when the node restarts, it catchup using the Reactor in blocksync, then enter consensus phase, its height already catch up with the others.
We have to deliberately  to let the peer lag behind many heights in consensus phase, either through network isolation, or simply kill -19 to hang the process.

**Comment by james-ray** [comment]
> Hey @james-ray, I'm not completely sure I understand this change. From what I can tell, this is trying to guard against the case that a lagging peer may have discarded a block in the round that it's in. I'm not yet sure I know why that would happen, do you have a clear case in the code where this occurs?

The reason this would happen is:
If in the same height, gossipDataRouting would firstly send proposal then send blockparts, the struct cs.ProposalBlockParts would not be nil.
But in catchup logic, gossipDataRouting would not send proposal, instead, the gossipVoteRouting send 2/3+ precommits to help the peer set up the struct cs.ProposalBlockParts.  But the sequence is not always 2/3+ precommits received first and block parts received second.   So "received a block part when we are not expecting any" this happens.

**Comment by williambanfield** [comment]
Got it, then this is related to https://github.com/tendermint/tendermint/issues/129. It's a topic that we have on our radar and I think deserves slightly more design work. At the moment, lagging nodes should be able to be restarted to trigger blocksync to begin again as a workaround.

**Comment by james-ray** [comment]
> Got it, then this is related to #129. It's a topic that we have on our radar and I think deserves slightly more design work. At the moment, lagging nodes should be able to be restarted to trigger blocksync to begin again as a workaround.

But we cannot depend on human operation to fix the stuck if it happens, we should write code to automatically recover.
This fix is an easy way, maybe there would be more elegant way.

**Comment by williambanfield** [comment]
Thanks for the response. I definitely think that more elegant solutions are possible and will be unlocked both as we work on integrating LibP2P for gossiping messages as well as add more specification of the gossip protocol, both of which are planned for the next quarter. For now, operators that need to detect stuck nodes can use alerting tools to with the [consensus_height](https://github.com/tendermint/tendermint/blob/9ec30ecc0c28b263cc4305d08dda7c3204dbc8f1/docs/nodes/metrics.md#L24) metric to determine that a node is no longer making progress and should be considered for a restart.

**Pull request closed without merging**
