### PR TITLE
[ADR-045] add HotSync Refactor

### PR DESCRIPTION
**Pull request by guagualvcha**
proposed a new block sync protocol.

implement in https://github.com/tendermint/tendermint/pull/3816/files

* [ ] Referenced an issue explaining the need for the change
* [ ] Updated all relevant documentation in docs
* [ ] Updated all code comments where relevant
* [ ] Wrote tests
* [ ] Updated CHANGELOG_PENDING.md

### CODE REVIEW

**Comment by guagualvcha** [comment]
@marbar3778   Would get people to review the ADR?

**Comment by melekes** [comment]
As far as I understood, the main idea here is:

- **for sentry/non-validator nodes**: to run a mixed version of the existing fast-sync & stripped consensus protocol (without WAL and replay) & no p2p network
- **for seed nodes:** to run a mixed version of the existing fast-sync & pex reactor

Correct?

**Comment by marbar3778** [comment]
@guagualvcha, thank you for your patience, we had a short discussion about this in our previous team call, is there a way for us to hop on a call to discuss this?

**Comment by melekes** [comment]
If I am right, then https://github.com/tendermint/tendermint/issues/2237 issue needs to be linked here.

**Comment by guagualvcha** [comment]
> As far as I understood, the main idea here is:
> 
> * **for sentry/non-validator nodes**: to run a mixed version of the existing fast-sync & stripped consensus protocol (_without WAL and replay_) // no gossip, pubsub model for fast-sync
> * **for seed nodes:** to run a mixed version of the existing fast-sync & PEX reactor (_minimal p2p network_) // no consensus, no gossip, pubsub model for fast-sync
> 
> Correct?
exactly.

**Comment by guagualvcha** [comment]
> @guagualvcha, thank you for your patience, we had a short discussion about this in our previous team call, is there a way for us to hop on a call to discuss this?

Sorry, we are not permitted to reveal ourselves. But I can answer any question about this ADR.

**Comment by marbar3778** [comment]
We discussed `hotsync` on our Tendermint call yesterday and came to the conclusion that we won't be able to accept this into the Tendermint repo. 

We are currently working to categorize each `mode` Tendermint can possibly offer here: https://github.com/tendermint/tendermint/issues/2237

I saw your comment here: https://github.com/tendermint/tendermint/issues/1148#issuecomment-439792235 and believe this is something that can be offered as a mode, but it would need to be discussed first. 

if you have any type of modes that you would like please leave a comment in the issue #2237 and the discussions from the team will also be kept there. 

For this reason, I will close this PR and will close the PR containing the code. I hope you understand, but if you would like me to expand on why we can not accept it into this repo, just ask I will do my best.

**Comment by guagualvcha** [comment]
> We discussed `hotsync` on our Tendermint call yesterday and came to the conclusion that we won't be able to accept this into the Tendermint repo.
> 
> We are currently working to categorize each `mode` Tendermint can possibly offer here: #2237
> 
> I saw your comment here: [#1148 (comment)](https://github.com/tendermint/tendermint/issues/1148#issuecomment-439792235) and believe this is something that can be offered as a mode, but it would need to be discussed first.
> 
> if you have any type of modes that you would like please leave a comment in the issue #2237 and the discussions from the team will also be kept there.
> 
> For this reason, I will close this PR and will close the PR containing the code. I hope you understand, but if you would like me to expand on why we can not accept it into this repo, just ask I will do my best.

I can understand. thks for reply

**Pull request closed without merging**
