### PR TITLE
build with go1.16

### PR DESCRIPTION
**Pull request by alessio**

### CODE REVIEW

**Review by alexanderbez — COMMENTED** [review]
Do we need to update `go.mod`?

**Comment by marbar3778** [comment]
> Do we need to update `go.mod`?

Let's wait on this change for another couple weeks. I don't think there is anything special from 1.16 other than some linker performance improvements.

**Review by marbar3778 — APPROVED** [review]

**Comment by alessio** [comment]
> Do we need to update `go.mod`?

If the code doesn't use any feature introduced in go1.16, then no, go.mod can stay the same

**Comment by tessr** [comment]
Do we actually want to backport this, since it will require users to upgrade their go versions presumably?

**Comment by marbar3778** [comment]
> Do we actually want to backport this, since it will require users to upgrade their go versions presumably?

The title is a bit confusing. This only touches CI, will not affect users.

**Comment by alessio** [comment]
@marbar3778 `automerge` does not work when a PR includes changes in `.github/workflows/`

**Pull request merged**
