### PR TITLE
feat: Support Google Cloud PubSub Indexer Sink

### PR DESCRIPTION
**Pull request by alexanderbez**
This PR introduces support for an additional tx and block indexer sink --  Google Cloud's [`PubSub`](https://pkg.go.dev/cloud.google.com/go/pubsub).

This PR is first being introduces in the 0.34 release for quicker community adoption and usage, and then will be introduced in `main`. If preferred, I can introduce this feature to `main` first.

### CODE REVIEW

**Comment by alexanderbez** [comment]
Can we just leave this as a draft until we get 0.34.20 out? I know of a few teams that really want support for this sink.

**Comment by creachadair** [comment]
The feature is fine, but should not target v0.34. The right way to get users newer features is to do the work to get users upgraded to newer versions of the software. Users also want other features such as ABCI++, and the best path to getting them what they want is to make that our collective priority.

**Comment by alexanderbez** [comment]
> The feature is fine, but should not target v0.34. The right way to get users newer features is to do the work to get users upgraded to newer versions of the software.

You mean v0.35.x? I'm sorry, but users aren't going to use that, at least not anytime soon. As I mentioned in this PR body, this is being introduced into 0.34.x AND `main`, which will be backported in 0.36.x. Users are very comfortable with 0.34.x and will be sticking with that version for quite some time as updating Tendermint versions is not a trivial decision. But just my two cents.

**Comment by cmwaters** [comment]
I guess this points to a larger picture which is that Tendermint needs to move to a place where it can be a relatively trivial decision to upgrade.

v0.35 is a good example of something that failed to be appealing for users to upgrade to because:
1. It didn't include many features. There was a bunch of small stuff but the only big draw was prioritised mempool.
2. It was painful for users to upgrade due to the database migration and changes to the config
3. It wasn't as thoroughly tested and vetted as it should be. This allowed bugs to seep through and resulted in a loss of confidence around the overall quality. 

If we want to make this an easy decision for users, we should look to put the features users want in the new releases. We also of course need to focus on points 2 and 3

**Comment by xla** [comment]
Fixing tm's release policy and adoption confidence is orthogonal to this change.

What are the actual drawbacks of this change being applied on top of `0.34.x` besides the core teams preference to continue to bet on a shaky `0.35.x`?

**Comment by williambanfield** [comment]
>What are the actual drawbacks of this change being applied on top of 0.34.x besides the core teams preference to continue to bet on a shaky 0.35.x?

To the second point, we have a number of users on v0.35 at the moment and some looking to aggressively move to v0.36 for ABCI++ support. The TM core team's commitment is to make those releases be very stable. We've identified and fixed a lot of the existing issues but if you know of more that we haven't spotted or fixed, it'd be very helpful if you could open a bug report/issue or request that users facing issues do the same.

**Comment by 08d2** [comment]
> What are the actual drawbacks of this change being applied . . .

```diff
 require (
+	cloud.google.com/go/iam v0.3.0 // indirect
+	cloud.google.com/go/kms v1.4.0 // indirect
+	cloud.google.com/go/pubsub v1.3.1
	github.com/BurntSushi/toml v1.1.0
```

Tendermint should not depend on Google Cloud PubSub. This integration may be valuable, but it should live in a separate module/repo, which consumers can opt-in to if they want to.

**Comment by xla** [comment]
> Tendermint should not depend on Google Cloud PubSub. This integration may be valuable, but it should live in a separate module/repo, which consumers can opt-in to if they want to.

@08d2 In practice how would that setup look like for a user who wants to enable this specific sink for tendermint?

**Comment by xla** [comment]
@williambanfield Unfortunately your response doesn't seem to address my question, instead just restating generally some implicit priorities from the core team. Is there a possibility to get a direct answer?

**Comment by 08d2** [comment]
> > Tendermint should not depend on Google Cloud PubSub. This integration may be valuable, but it should live in a separate module/repo, which consumers can opt-in to if they want to.
> 
> @08d2 In practice how would that setup look like for a user who wants to enable this specific sink for tendermint?

<soapbox>

Tendermint is "a . . . Byzantine Fault Tolerant (BFT) [protocol and implementation] that takes a state transition machine . . . and securely replicates it on many machines." That's a hard problem to solve, and it's actually great that Tendermint solves it. But solving that problem is an enormous task in itself. It's not feasible to expect Tendermint's maintainers to maintain the code that does that _and_ and arbitrary set of value-add features on top.

</soapbox>

Tendermint isn't, shouldn't be, concerned with indexing anything. That's not part of its mandate. If an indexable stream of events is actually an appropriate capability for `github.com/tendermint/tendermint` to offer to consumers — it's not obvious to me that this is true, but let's assume it is for now — then the only sustainable way that can work is for those events to be made available directly, and for consumers to consume them however they see fit.

The general-purpose implementation would look something like this.

```go
func (t *Tendermint) Subscribe(c chan<- IndexableEvent) error
func (t *Tendermint) Unsubscribe(c chan<- IndexableEvent) error

when an indexable event occurs,
    for every subscriber
        select {
        case c <- event:
            they got it, great
        default:
             too slow, dropped
        }
```

Then it would be pretty straightforward to write some code — importantly, outside of Tendermint's repo, and thus outside of Tendermint's maintainers' responsibility — which consumed IndexableEvents and emitted them anywhere you liked.

**Comment by williambanfield** [comment]
@xla The answer is one of priorities of the Tendermint team. A change like this requires migration paths and bug fixes, and ongoing support. Applying changes to old versions means adding a support burden to a branch of Tendermint that we are trying to migrate projects beyond. We have users on v0.35 and prepping to move to v0.36. Having more users on a smaller set of more recent branches with more maintainable code bases frees the team up to add features and fixes to those actively used branches and avoid splitting maintainers time to thin to be able to actually support applications as they begin to use things like ABCi++.

**Comment by 08d2** [comment]
> > Then it would be pretty straightforward to write some code — importantly, outside of Tendermint's repo, and thus outside of Tendermint's maintainers' responsibility — which consumed IndexableEvents and emitted them wherever.
> 
> This is the part I'd be curious about. From the perspective of an operator who wants to run tendermint or a specific app chain based on tendermint with events indexed by PubSub, how would they go about the composition of these concerns?

There are lots of possible answers to this question. That operator could always write the code that integrated Tendermint core with PubSub, and maintain it themselves. They could maybe find a third party who did this work, and rely on them for the feature. Probably many more options, too. But Tendermint core itself can't be expected to support integrations at this level. The unit economics don't work out.

**Pull request closed without merging**
