### PR TITLE
Add Tendermint development videos to Github

### PR DESCRIPTION
**Pull request by Michelle-L**
# Tendermint Core Development Sessions

The Tendermint Core developer call is comprised of both [Interchain Foundation](http://interchain.io/) and [All in Bits](https://tendermint.com/) team members discussing the development of [Tendermint BFT](https://github.com/tendermint/tendermint) and related research. 

# Previous Tendermint Core Development Sessions

August 2019 | Part Three: Tendermint Lite Client | [video](https://www.youtube.com/watch?v=whyL6UrKe7I&list=PLdQIb0qr3pnBbG5ZG-0gr3zM86_s8Rpqv&index=5) |

August 2019 | Fork Accountability | [video](https://www.youtube.com/watch?v=Jph-4PGtdPo&list=PLdQIb0qr3pnBbG5ZG-0gr3zM86_s8Rpqv&index=4) |

July 2019 | Part Two: Tendermint Lite Client | [video](https://www.youtube.com/watch?v=gTjG7jNNdKQ&list=PLdQIb0qr3pnBbG5ZG-0gr3zM86_s8Rpqv&index=6) |

July 2019 | Part One: Tendermint Lite Client | [video](https://www.youtube.com/watch?v=C6fH_sgPJzA&list=PLdQIb0qr3pnBbG5ZG-0gr3zM86_s8Rpqv&index=7) |

June 2019 | Testnet Deployments | [video](https://www.youtube.com/watch?v=gYA6no7tRlM&list=PLdQIb0qr3pnBbG5ZG-0gr3zM86_s8Rpqv&index=10) |

June 2019 | Blockchain Reactor Refactor | [video](https://www.youtube.com/watch?v=JLBGH8yxABk&list=PLdQIb0qr3pnBbG5ZG-0gr3zM86_s8Rpqv&index=11) |

June 2019 | Tendermint Rust Libraries | [video](https://www.youtube.com/watch?v=-WXKdyoGHwA&list=PLdQIb0qr3pnBbG5ZG-0gr3zM86_s8Rpqv&index=9) |

May 2019 | Merkle Tree Deep Dive | [video](https://www.youtube.com/watch?v=L3bt2Uw8ICg&list=PLdQIb0qr3pnBbG5ZG-0gr3zM86_s8Rpqv&index=8) |

May 2019 |Remote Signer Refactor | [video](https://www.youtube.com/watch?v=eUyXXEEuBzQ&list=PLdQIb0qr3pnBbG5ZG-0gr3zM86_s8Rpqv&index=12) |

May 2019 | Introduction to Ansible | [video](https://www.youtube.com/watch?v=72clQLjzPg4&list=PLdQIb0qr3pnBbG5ZG-0gr3zM86_s8Rpqv&index=14&t=0s) |

April 2019 | Tendermint State Sync Design Discussion | [video](https://www.youtube.com/watch?v=4k23j2QHwrM&list=PLdQIb0qr3pnBbG5ZG-0gr3zM86_s8Rpqv&index=11) |

April 2019 | ADR-036 - Blockchain Reactor Refactor | [video](https://www.youtube.com/watch?v=TW2xC1LwEkE&list=PLdQIb0qr3pnBbG5ZG-0gr3zM86_s8Rpqv&index=10)|

April 2019 | Verifying Distributed Algorithms | [video](https://www.youtube.com/watch?v=tMd4lgPVBxE&list=PLdQIb0qr3pnBbG5ZG-0gr3zM86_s8Rpqv&index=9) |

April 2019 | Byzantine Model Checker Presentation | [video](https://www.youtube.com/watch?v=rdXl4VCQyow&list=PLdQIb0qr3pnBbG5ZG-0gr3zM86_s8Rpqv&index=8)|

January 2019 | Proposer Selection in Idris | [video](https://www.youtube.com/watch?v=hWZdc9c1aH8&list=PLdQIb0qr3pnBbG5ZG-0gr3zM86_s8Rpqv&index=7)|

January 2019 | Current Mempool Design | [video](https://www.youtube.com/watch?v=--iGIYYiLu4&list=PLdQIb0qr3pnBbG5ZG-0gr3zM86_s8Rpqv&index=6)|

December 2018 | ABCI Proxy App | [video](https://www.youtube.com/watch?v=s6sQ2HOVHdo&list=PLdQIb0qr3pnBbG5ZG-0gr3zM86_s8Rpqv&index=5)|

October 2018| DB Performance | [video](https://www.youtube.com/watch?v=jVSNHi4l0fQ&list=PLdQIb0qr3pnBbG5ZG-0gr3zM86_s8Rpqv&index=4)|

October 2018| Alternative Mempool Algorithms| [video](https://www.youtube.com/watch?v=XxH5ZtM4vMM&list=PLdQIb0qr3pnBbG5ZG-0gr3zM86_s8Rpqv&index=2)|

October 2018| Tendermint Termination | [video](https://www.youtube.com/watch?v=YBZjecfjeIk&list=PLdQIb0qr3pnBbG5ZG-0gr3zM86_s8Rpqv) |

### CODE REVIEW

**Comment by ebuchman** [comment]
This is awesome thanks michelle! Could we just change the name of the file to `DEV_SESSIONS.md` or something - it just shouldn't have any spaces. Also we can link to it from the root README.md under `Contributing`

**Comment by melekes** [comment]
Maybe we should put these somewhere under `docs/`, so they are visible in https://tendermint.com/docs/?

**Comment by Michelle-L** [comment]
I agree having it in the docs folder makes sense. I can keep it update there when new videos are published.

**Comment by melekes** [comment]
Alternatively, we can list them [here](https://github.com/tendermint/awesome)

**Comment by marbar3778** [comment]
lets put in docs with file title `DEV_SESSIONS.md` and then we can link in awesome. think this makes the most sense for now.

**Comment by Michelle-L** [comment]
I also agree with Marko, I wouldn't actually think to look in awesome section

**Pull request merged**
