### PR TITLE
Fix code style

### PR DESCRIPTION
**Pull request by zaq1tomo**
- Unification of local variable names
- Unification of method argument names
- Unification of function and method position

### CODE REVIEW

**Comment by melekes** [comment]
@zaq1tomo thanks! please make PRs against develop next time :)

**Comment by zaq1tomo** [comment]
I see. Thanks for your review!

**Comment by melekes** [comment]
codecov did not work, duh. we will have to ask @ebuchman to merge

**Comment by ebuchman** [comment]
Thanks for this! Would you mind squashing the commits? 

Thanks.

**Comment by ebuchman** [comment]
Oh wow Github let's me do that. Amazing!

**Pull request merged**
