### PR TITLE
consensus: tests should use ephemeral app for testing

### PR DESCRIPTION
**Pull request by tychoish**

### CODE REVIEW

**Review by creachadair — APPROVED** [review]
Mechanically I like this, but how does this interact with the nodes restarting? Won't the ephemeral app lose all its state?

**Comment by tychoish** [comment]
> Mechanically I like this, but how does this interact with the nodes restarting? Won't the ephemeral app lose all its state?

It was my belief/hope that this was only used in cases where we weren't restarting, or the way that we were restarting didn't involve destructing the relevant objects in question. Having looked through the code it *might* be possible that this is true, though I will be appropriately sad if it is not.

**Comment by creachadair** [comment]
> It was my belief/hope that this was only used in cases where we weren't restarting, or the way that we were restarting didn't involve destructing the relevant objects in question. Having looked through the code it _might_ be possible that this is true, though I will be appropriately sad if it is not.

It's quite possible the tests only exercise the consensus objects and not the app state.

**Review by williambanfield — APPROVED** [review]

**Comment by tychoish** [comment]
This is pretty reliably deadlocking/hitting the timeout, and I think the root cause of this failure is "using the memdb makes the test run faster exacerbating a timing expectation and causing the test to fail." 

The solution to this problem is to refactor the tests (and probably the consensus reactor code as well) so that it can be tested without relying on the event system (e.g. we should have some kind of "event hook" that tests can use to inject a function to observe events. This would be a major undertaking but would definitely improve the code. There are other potential solutions (like mocked eventbus, etc.) but the basic idea is the same. 

For the moment I think it makes sense to abandon this PR because there's no reliable way to get the minimal version of this merged, and it's easy to revive if a new path opens up. The more intensive solution is also well enough understood and tracked elsewhere that we don't need hang on to this in the mean time.

**Pull request closed without merging**
