### PR TITLE
types: implement Header#ValidateBasic

### PR DESCRIPTION
**Pull request by alexanderbez**
## Description

- Move core stateless validation of the `Header` type to a `ValidateBasic` method.
- Call `header.ValidateBasic` during a `SignedHeader` validation.
- Call `header.ValidateBasic` during a `PhantomValidatorEvidence` validation.
- Call `header.ValidateBasic` during a `LunaticValidatorEvidence` validation.

_lite tests are skipped since the package is deprecated, no need to waste time on it_

closes: #4572

______

For contributor use:

- [x] Wrote tests
- [x] Updated CHANGELOG_PENDING.md
- [x] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [ ] Updated relevant documentation (`docs/`) and code comments
- [x] Re-reviewed `Files changed` in the Github PR explorer

### CODE REVIEW

**Comment by alexanderbez** [comment]
@melekes I've added the `Header#ValidateBasic` call to the validation of `SignedHeader`. However, I noticed in the `lite` package, the proposer address is never provided when creating a `Header` and thus validation fails in the unit test.

What is the correct model here? Should we remove checking for the proposer address in `Header#ValidateBasic` and only check that in `Block#ValidateBasic`?

**Comment by melekes** [comment]
> However, I noticed in the lite package, the proposer address is never provided when creating a Header and thus validation fails in the unit test.

lite package is deprecated. you can comment the failing test out.

I think it's correct to always require proposer to exist in Header.

**Comment by alexanderbez** [comment]
This affects lite2 as well. Should `GenSignedHeader` take in a proposer address?

**Comment by melekes** [comment]
> This affects lite2 as well. Should GenSignedHeader take in a proposer address?

for now, we can set Proposer to `valSet.Validators[0].Address()`.

**Comment by alexanderbez** [comment]
@melekes I tried this, but `GenSignedHeader` sets the `Commit` which calls `signHeader` which further gets the hash of the header _before_ we set the proposer. So if I set the proposer after it's made, the hashes won't line up.

**Comment by melekes** [comment]
> Was there a reason we dont accept a proposer address in any of these APIs?

No real reason except it was not needed at the time.

**Comment by melekes** [comment]
heads up: I'm going to finish this now. Thanks!

**Pull request merged**
