### PR TITLE
RC1 for v0.33.5

### PR DESCRIPTION
**Pull request by tessr**
This includes all changes tagged `R:minor` since 0.33.4. I did have to resolve quite a few conflicts manually, would appreciate a quick check over the evidence changes in particular from @cmwaters and @melekes.

### CODE REVIEW

**Comment by tessr** [comment]
Hmm, looks like I didn't resolve the something with `EvidenceParams` correctly. Looking into this now.

**Comment by tessr** [comment]
OK, I figured out what the merge issue is:

[This commit](https://github.com/tendermint/tendermint/commit/1e5f00c2dd9db6fe39bd076e97d6a28a554e042a), which is included in the release, makes some changes to code which mentions the `MaxNum` field in `EvidenceParams`. This is because it landed on master after [this PR, #4780](https://github.com/tendermint/tendermint/pull/4780), which introduces `MaxNum`, but requires a major release.

To fix this for this branch, I can just delete the code that includes `MaxNum`. But just to check: the next major release _won't_ build on this branch and its history in any way, right? It just takes master, right? 

Also not sure if merge conflicts like this are an indicator that we're doing something wrong with this process, or if its just unavoidable.

**Comment by marbar3778** [comment]
>To fix this for this branch, I can just delete the code that includes MaxNum. But just to check: the next major release won't build on this branch and its history in any way, right? It just takes master, right?

correct these two git histories will never meet

**Comment by erikgrinaker** [comment]
> Also not sure if merge conflicts like this are an indicator that we're doing something wrong with this process, or if its just unavoidable.

I think we should be conservative about what we cherry-pick into patch releases, and generally only include significant bug fixes and security fixes. As the branches drift apart, the amount of work needed to backport changes can become a significant burden - as far as I know, this is unavoidable. It can to some extent be mitigated by maintaining good commit discipline on `master`, such that fixes that should be backported are in a single commit without any unrelated or unnecessary changes.

Mergify also has support for [automatically backporting PRs](https://mergify.io/features/backports). This may or may not be helpful.

**Comment by marbar3778** [comment]
>I think we should be conservative about what we cherry-pick into patch releases, and generally only include significant bug fixes and security fixes

I agree I think we went with the notion that if it's not breaking we can add it into a minor release, but there may be a second question of does it have to be in a minor release that may need asking

**Comment by erikgrinaker** [comment]
> > I think we should be conservative about what we cherry-pick into patch releases, and generally only include significant bug fixes and security fixes
> 
> I agree I think we went with the notion that if it's not breaking we can add it into a minor release, but there may be a second question of does it have to be in a minor release that may need asking

That's true in principle, but more than anything it's a question of how much resources we want to spend on backporting changes, and whether it's worth it.

**Comment by tessr** [comment]
WHEW BOY. This has been a journey! Worth noting also that this is the first time we've tried doing this point release process. We used to hold back breaking changes (for "major" releases) and not merge to them to master. We recently switched to a new process where we merge everything in, and then do point* releases with things explicitly tagged for the point release. 

In the old world, putting all non-breaking changes in on point releases made sense. ("Is this breaking?" we might ask. "No? Throw it in the release!") We also didn't consider that "backporting" in any way. But in the new world, where all changes for point releases have to be cherry-picked, it might not.

So what should we do?

I think it's clear that what I've been doing yesterday and today is not a sustainable way to do these releases. For one thing, it's taken me the better part of two full work days! For another, there are a few big gotchas and risks.

1. I have to resolve all the merge conflicts myself. I don't always have the domain expertise that the commit author might have, so although I can guess what's safe, I will definitely need the commit authors to review the changes.
2. Sometimes changes that are included in the point release rely on other changes that are not included in the point release. The problem that I mentioned in an earlier comment, about `MaxNum` on `EvidenceParams`, is a pretty good example. This creates a particularly tricky form of merge conflict. 
3. The changes-to-be-included are denoted by pull requests which are tagged. But we're not cherry-picking PRs, we're cherry-picking _commits_. Sometimes one PR can end up being referenced by multiple commits, if either the person merging it forgets to squash, or if the original commit-on-master gets replayed somewhere else. Yesterday I made the mistake of picking a copy of a commit, which referenced a tagged PR, rather than PR itself.  

I'm saying "I" here, but really it could be whoever happens to be doing the release. (Perhaps also worth nothing that this amount of work is the kind of thing that leads to teams getting dedicated release engineers.)

All of these issues mean that it's pretty easy to make a mistake, and pretty easy to inadvertently make a broken release. 

Moving forward, I have an easy-enough solution: **All point release changes should be merged into a release candidate branch at the same time that they are merged to master.** In other words, any PR tagged `r:Minor` should have a sister PR, onto some long-lived branch accumulating point changes. That branch can then form the basis of the next point release. What do you all think? 

However, I'm not totally sure what to do about _this_ release. It's currently broken, because something is wrong with the evidence module. (I have a hunch that this may be because @melekes marked a lot of evidence changes as `R:minor` and @cmwaters didn't mark any--which were both valid strategies in the absence of more detailed guidance on what goes in a point release--and I blindly took only the minor-marked changes.) Do we want to fix this branch? Or should we reassess which changes should be included, and start over? 

\* Trying to use "point" release rather than "minor" release, for more clarity with semver naming.

**Comment by erikgrinaker** [comment]
> All point release changes should be merged into a release candidate branch at the same time that they are merged to master.

I agree. We should have one branch for each maintained minor version (so if we support 0.33 and 0.32 we should have branches `0.33` and `0.32` or whatever). When we merge a fix to `master` which should also be back ported to older release lines, the merger or author should backport those into the relevant historical branches at the same time - this may or may not be trivial depending on branch histories. We then cut releases from the `0.33` and `0.32` branches when appropriate.

Again, I would advocate being conservative about what we backport - this can become a real time sink.

**Comment by marbar3778** [comment]
>All point release changes should be merged into a release candidate branch at the same time that they are merged to master

I don't think this solves the issue because the changes will look different and cause teh engineer to possibly double the work. I don't believe this was the best release to start this process because there were some major changes and refactors. This release process was taken from the sdk and they have been doing it for over a year I think we should have them weigh in.

**Comment by erikgrinaker** [comment]
>>All point release changes should be merged into a release candidate branch at the same time that they are merged to master
>I don't think this solves the issue because the changes will look different and cause teh engineer to possibly double the work.

This is sort of the nature of maintaining historical versions and backporting fixes, and is the common way for software projects to do this for as long as I can remember.

**Comment by cmwaters** [comment]
> All point release changes should be merged into a release candidate branch at the same time that they are merged to master

I agree that this makes sense. @Marko, I think you might be right in terms of doing extra work, but I don't think it will be much more

**Comment by marbar3778** [comment]
we do currently maintain release branches for every release. this is not something that would change.

**Comment by alexanderbez** [comment]
Being that I've been doing virtually the entire release process for the SDK -- both major and minor/point releases, I'd like to chime in with a few points of things I've learned and would do differently had I known what I know now. I'll try to keep the points concise. Here's the gist:

1. Only support _one_ major version (i.e you're only backporting to a single release).
2. Keep the total number of backporting  PRs minimal. Limit them to just bug fixes and core features that you deem would be greatly appreciated by the community at large. This has the side effect that you might be doing minor release more often -- which is probably OK.
3. As @tessr pointed, cherry-picking is hard and comes with many issues. Being that I have a great deal of domain exp on the SDK, I know how to resolve _most_ conflicts. However, this is not sustainable for many reasons. This leads to really the only piece I'd change in the process that we've been using and Tendermint seems to now also use:
  3a. After each minor/point release, we create a new (next) point release. i.e. v0.33.4 was already released, so we immediately created a living (WIP) `rc0/v0.33.5` (naming can change -- doesn't matter really).
  3b. Now, during any PR review, it will be the _teams_ responsibility to determine if something should be backported. If so, it is the _authors_ responsibility to create a subsequent (2nd) PR that takes the original PR and merges it against the living (next release) branch.

Everything still goes to `master` and the next major release is cut from `master`.

**Comment by cmwaters** [comment]
As for now, I can try look into the evidence part of this branch and try fix anything that may be breaking it

**Comment by marbar3778** [comment]
> As for now, I can try look into the evidence part of this branch and try fix anything that may be breaking it

Before you do this, I propose we scrap this PR, then make a new rc branch then each of us goes through the minor label and pick one item and then make a PR with that one item to the rc branch. 

I am mainly proposing this as it may be hard to go through things and try and find where the bug lies instead of starting from scratch. thoughts?

**Comment by cmwaters** [comment]
Won't it be annoying trying to merge and update and coordinate a whole bunch of PR's though

**Comment by marbar3778** [comment]
> Won't it be annoying trying to merge and update and coordinate a whole bunch of PR's though

not necessarily, but was thinking of a way to do this release in a safe way so we dont introduce any bugs

**Comment by tessr** [comment]
Thank you so much, @alexanderbez! Your advice resonates with what I had been thinking, and I think that process is basically what we should adopt moving forward. I particularly like this part: 

> during any PR review, it will be the teams responsibility to determine if something should be backported. If so, it is the authors responsibility to create a subsequent (2nd) PR that takes the original PR and merges it against the living (next release) branch.

To address a couple more comments... 

From @marbar3778:

> I don't think this solves the issue because the changes will look different and cause the engineer to possibly double the work. 

Unfortunately, if the change is going to be _that_ different, then someone is going to be doing that reconciliation work. And it's safer to have the author do it, when they have the context in their head and they know the domain well, than to have the releaser do it, who may not have the context or domain expertise.

And if it's really such an enormous change, maybe it's not a good candidate for point releases anyways. 

> I don't believe this was the best release to start this process because there were some major changes and refactors. I think if we are more strict with what makes it into a release then this wont happen again. Many of these changes are in the lite client and evidence which are having major refactors so this would naturally cause issues 

This may all be true. But a huge part of our roadmap is refactors. A lot of our work is going to look like this, and we should figure out a strategy that works for big refactors. 

And finally, to address the next steps for this release specifically, I think @marbar3778 has the right idea: We'll create a new release candidate branch, and we can merge individual PRs into it.  @cmwaters is also right: It will be very annoying if the branch is constantly changing as people try to merge PRs and likely end up with merge conflicts. 

So I propose we collect the set of changes we want to see (just links to the original PRs against master), and then once that's all collected, we can go through and _apply them in order_, getting any review or feedback on each one, as necessary. How does that sound?

**Comment by melekes** [comment]
> So I propose we collect the set of changes we want to see (just links to the original PRs against master), and then once that's all collected, we can go through and apply them in order, getting any review or feedback on each one, as necessary. How does that sound?

sounds good 👍

**Pull request closed without merging**
