### PR TITLE
crypto/ed25519: migrate filippo.io/edwards25519 for signing

### PR DESCRIPTION
**Pull request by marbar3778**
## Description

- Use filippo.io/edwards25519 for signing. This means we have our own signing function until it is merged into the golang standard library.

- The motivation for having our own till its merged is performance:

```sh
BenchmarkSigning-8           57080         35315         -38.13%
```

If there is consensus to avoid this we can close and ignore this PR. 

cc @ValarDragon 

Closes: #1792

### CODE REVIEW

**Comment by ValarDragon** [comment]
Does `filippo.io/edwards25519` not implement signing, but does implement verification?

**Comment by marbar3778** [comment]
> Does `filippo.io/edwards25519` not implement signing, but does implement verification?

It implements neither. https://github.com/hdevalence/ed25519consensus implements the verification we use. That lib replaces https://github.com/golang/crypto/tree/master/ed25519/internal/edwards25519 with  `filippo.io/edwards25519`. I can see about implementing this in  https://github.com/hdevalence/ed25519consensus if preferred?

**Comment by ValarDragon** [comment]
That makes sense. I think getting it implemented in https://github.com/hdevalence/ed25519consensus would be preferrable

**Comment by marbar3778** [comment]
migrated this to: https://github.com/hdevalence/ed25519consensus/pull/8

**Pull request closed without merging**
