### PR TITLE
libs/clist: remove all sync.WaitGroup fields

### LINKED ISSUE #6450: libs/clist: unnecessary usage of sync.WaitGroup
## Summary

We can avoid using `sync.WaitGroup` and use channel instead.

## Problem Definition

Looking through `libs/clist` code, the documentation state why we use `sync.WaitGroup`:

https://github.com/tendermint/tendermint/blob/fdd506a12666e8b86b1cadda6151a1945bf07c3e/libs/clist/clist.go#L33

Though, that same job can be archived by using corresponding channels. That said:

 - `wg.Wait()` can be replaced by a receive operation on channel
 - `wg.Done()` can be replaced by closing channel operation

## Proposal

Removing all sync.WaitGroup fields, and use only channel primitives for synchronization. That should cleanup the code, make it more readable, easier to maintain and slightly more efficient.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

### PR DESCRIPTION
**Pull request by cuonglm**
There're corresponding channels, which can be used to do the same job
of all sync.WaitGroup fields. So, it's not necessary to use them
anymore.

Benchmark result for runtime speed can be noisy, but the improvement in
memory is clearly visible:

```
name         old time/op    new time/op    delta
Detaching-8    48.9ns ±13%    57.8ns ±17%     ~     (p=0.095 n=5+5)
Removed-8       118ns ±39%      59ns ±27%  -50.19%  (p=0.008 n=5+5)
PushBack-8      224ns ±22%     167ns ±22%  -25.17%  (p=0.032 n=5+5)

name         old alloc/op   new alloc/op   delta
Detaching-8     0.00B          0.00B          ~     (all equal)
Removed-8       0.00B          0.00B          ~     (all equal)
PushBack-8       327B ± 0%      279B ± 0%  -14.68%  (p=0.000 n=5+4)

name         old allocs/op  new allocs/op  delta
Detaching-8      0.00           0.00          ~     (all equal)
Removed-8        0.00           0.00          ~     (all equal)
PushBack-8       5.00 ± 0%      3.00 ± 0%  -40.00%  (p=0.008 n=5+5)
```

Fixes #6450

### CODE REVIEW

**Comment by cuonglm** [comment]
cc @odeke-em

**Comment by tychoish** [comment]
I just ran the mempool's benchmarks which are one level higher in the stack, and may provide a better idea of what the impact of this change is in context of the code that actually uses the linked list implementation: 

I used the following command: 

```
go test -cpu=8 -benchmem -bench=. -run="Bench.*" ./mempool
```

(Changing the number of CPUs didn't change things too much)

First on master as of today: 

```
go test -cpu=8 -benchmem -bench=. -run="Bench.*" ./mempool
goos: linux
goarch: amd64
pkg: github.com/tendermint/tendermint/mempool
cpu: AMD Ryzen 9 3950X 16-Core Processor            
BenchmarkReap-8                     1274            892478 ns/op          485780 B/op      10001 allocs/op
BenchmarkCheckTx-8                362602              3051 ns/op            1521 B/op         32 allocs/op
BenchmarkParallelCheckTx-8        220724              5407 ns/op            1574 B/op         32 allocs/op
BenchmarkCheckDuplicateTx-8       317997              3862 ns/op            1547 B/op         33 allocs/op
BenchmarkCacheInsertTime-8       2636832               421.1 ns/op            80 B/op          2 allocs/op
BenchmarkCacheRemoveTime-8       3553003               324.1 ns/op             0 B/op          0 allocs/op
PASS
ok      github.com/tendermint/tendermint/mempool        12.244s
go test -cpu=8 -benchmem -bench=. -run="Bench.*" ./mempool  19.47s user 0.71s system 157% cpu 12.840 total
```

Then with this change: 

```
go test -cpu=8 -benchmem -bench=. -run="Bench.*" ./mempool
goos: linux
goarch: amd64
pkg: github.com/tendermint/tendermint/mempool
cpu: AMD Ryzen 9 3950X 16-Core Processor            
BenchmarkReap-8                     1180            903505 ns/op          485781 B/op      10001 allocs/op
BenchmarkCheckTx-8                342006              3048 ns/op            1477 B/op         30 allocs/op
BenchmarkParallelCheckTx-8        234578              5487 ns/op            1518 B/op         30 allocs/op
BenchmarkCheckDuplicateTx-8       308164              3725 ns/op            1503 B/op         31 allocs/op
BenchmarkCacheInsertTime-8       2632506               439.7 ns/op            80 B/op          2 allocs/op
BenchmarkCacheRemoveTime-8       3492236               337.7 ns/op             0 B/op          0 allocs/op
PASS
ok      github.com/tendermint/tendermint/mempool        12.471s
```

The impacts that I see: 
- this change omits a few mallocs likely because we're not allocating the wait group object any more. This is nice, but I wouldn't worry too much about a few mallocs. 
- the reaping benchmark, which is the slowest operation in the mempool, actually gets a bit slower (but without changing memory use.) Maybe about 1% I don't have a great explanation for this except maybe 'channels are slightly slower than waitgroups for raw performance?"
- CheckTX, ParalletCheckTX , and DuplicateCheckTX all all get about 1% faster, though these operations were always pretty fast, and 2 orders of magnittude faster than reaping to start with. Most of the speed of the CheckTx operation depends on the application, and the test application is very fast. The speed-up here is less likely to be noticed because the application's performance is the larger factor here in practice.

**Comment by tychoish** [comment]
Based on my hunch that "for pure performance, wait groups are likely a touch faster than channels," I tried the "opposite" approach, where I removed the channels, (see [this patch](https://gist.github.com/805b16eb8f6ea906b8f7779b0f2f97b2)) and left the wait group as the primary concurrency control.

Just for good measure, the current state of master: 

```
goos: linux
goarch: amd64
pkg: github.com/tendermint/tendermint/mempool
cpu: AMD Ryzen 9 3950X 16-Core Processor            
BenchmarkReap-8                     1326            890573 ns/op          485779 B/op      10001 allocs/op
BenchmarkCheckTx-8                344700              2985 ns/op            1525 B/op         32 allocs/op
BenchmarkParallelCheckTx-8        221882              5659 ns/op            1573 B/op         32 allocs/op
BenchmarkCheckDuplicateTx-8       301230              3808 ns/op            1553 B/op         33 allocs/op
BenchmarkCacheInsertTime-8       2787404               403.6 ns/op            81 B/op          2 allocs/op
BenchmarkCacheRemoveTime-8       3488594               327.5 ns/op             0 B/op          0 allocs/op
PASS
ok      github.com/tendermint/tendermint/mempool        12.266s
```


No stored channels, just the waitgroup: 

```
goos: linux
goarch: amd64
pkg: github.com/tendermint/tendermint/mempool
cpu: AMD Ryzen 9 3950X 16-Core Processor            
BenchmarkReap-8                     1191            892324 ns/op          485781 B/op      10001 allocs/op
BenchmarkCheckTx-8                398050              3170 ns/op            1307 B/op         30 allocs/op
BenchmarkParallelCheckTx-8        235194              5431 ns/op            1357 B/op         30 allocs/op
BenchmarkCheckDuplicateTx-8       285861              4000 ns/op            1351 B/op         31 allocs/op
BenchmarkCacheInsertTime-8       2613043               424.2 ns/op            80 B/op          2 allocs/op
BenchmarkCacheRemoveTime-8       3539300               343.7 ns/op             0 B/op          0 allocs/op
PASS
ok      github.com/tendermint/tendermint/mempool        11.670s
```

Again the results are mixed, but the performance on reaping doesn't have a particularly big degradation, so that's nice. It's a touch faster for the parallel checkTx (maybe 2%) but a touch slower for the other checktx (with fewer allocs). I think the parallel benchmark is perhaps the most important of the checktx operations. It's also the case that the entire suite finishes faster and the throughput of the operations goes up, so I'm heartened by this a bit. 

My change was also very quick, and I suspect that my hack to keep the API the same (e.g. where I start a go routine to close the signal channel that I create,) is slower than it should be, and if we can think of different ways to handle this API then we might be able to get more speed, again, if we want it. 

------ 

Benchmarks are only a part of this story though: having two different concurrency control mechanisms is definitely more confusing than it needs to be, so I think it does improve the code a bit to change this.

**Comment by cuonglm** [comment]
@tychoish running benchmark just 1 time makes no much sense, though. Can you retry with `-count=5` or `-count=10` then doing a `benchstat` on them?

Example, in the PR description, you can see a boost in running time if you only look at the percent comparison:

```
name         old time/op    new time/op    delta
Detaching-8    48.9ns ±13%    57.8ns ±17%     ~     (p=0.095 n=5+5)
Removed-8       118ns ±39%      59ns ±27%  -50.19%  (p=0.008 n=5+5)
PushBack-8      224ns ±22%     167ns ±22%  -25.17%  (p=0.032 n=5+5)
```

But they have too much noise (e.g: 39% and 27% for Removed-8), thay's why I don't state that the performance have a boost.

**Comment by tychoish** [comment]
I reran all three benchmarks from  the `mempool` package (which I think provide a better _in stiu_ view of the performance of the clist structure.) with both the "only waitgroup" and "only channels" approach (10 times each), and this is what I see: 

```
name \ time/op       baseline.txt  chans.txt    waitgroup.txt
Reap-32                936µs ± 4%   948µs ± 2%     949µs ± 1%
CheckTx-32            3.13µs ± 4%  3.16µs ± 5%    3.07µs ± 4%
ParallelCheckTx-32    5.89µs ± 2%  5.78µs ± 3%    5.73µs ± 2%
CheckDuplicateTx-32   3.86µs ± 4%  3.86µs ± 6%    3.89µs ± 2%
CacheInsertTime-32     411ns ± 2%   421ns ± 3%     410ns ± 3%
CacheRemoveTime-32     338ns ± 1%   333ns ± 2%     336ns ± 2%

name \ alloc/op      baseline.txt  chans.txt    waitgroup.txt
Reap-32                486kB ± 0%   486kB ± 0%     486kB ± 0%
CheckTx-32            1.52kB ± 0%  1.47kB ± 0%    1.31kB ± 0%
ParallelCheckTx-32    1.51kB ± 0%  1.48kB ± 3%    1.33kB ± 3%
CheckDuplicateTx-32   1.55kB ± 0%  1.51kB ± 0%    1.35kB ± 0%
CacheInsertTime-32     81.5B ± 2%   80.9B ± 1%     81.3B ± 2%
CacheRemoveTime-32     0.00B        0.00B          0.00B     

name \ allocs/op     baseline.txt  chans.txt    waitgroup.txt
Reap-32                10.0k ± 0%   10.0k ± 0%     10.0k ± 0%
CheckTx-32              32.0 ± 0%    30.0 ± 0%      30.0 ± 0%
ParallelCheckTx-32      32.0 ± 0%    30.0 ± 0%      30.0 ± 0%
CheckDuplicateTx-32     33.0 ± 0%    31.0 ± 0%      31.0 ± 0%
CacheInsertTime-32      2.00 ± 0%    2.00 ± 0%      2.00 ± 0%
CacheRemoveTime-32      0.00         0.00           0.00   
```

**Comment by tychoish** [comment]
Just for future reference, the waitgroup branch is here: https://github.com/tendermint/tendermint/tree/clist-waitgroup

My inclination based on the results is to make this PR retain the waitgroup and drop the channels.

**Pull request closed without merging**
