### PR TITLE
Added ARM64 in GOARCH for Linux/ARM64 binary release

### PR DESCRIPTION
**Pull request by odidev**
Added GOARCH: arm64 with GOOS: linux, for releasing Linux/ARM64 binary
release for tendermint.

Signed-off-by: odidev <odidev@puresoftware.com>

Closes: #5157

### CODE REVIEW

**Comment by odidev** [comment]
@marbar3778 
Thanks for merging. May I know, when are you planning on releasing ARM64 binary?

**Comment by marbar3778** [comment]
what version of Tendermint are you using? I believe the next release will be 0.34.

**Comment by odidev** [comment]
I am using v0.31.5 tendermint.

**Comment by marbar3778** [comment]
> I am using v0.31.5 tendermint.

we will not be able to create a release for this version. We do recommend upgrading to the 0.33 line and soon the 0.34 line. there have been multiple security indicdents since that release

**Comment by odidev** [comment]
Hi @marbar3778 

Tendermint is releasing docker images with the AMD64 tag <https://hub.docker.com/r/tendermint/tendermint/tags>. It will be really helpful if you can also release ARM64 Tendermint docker images along with releasing newer version 0.34 or 0.33 line.
Please share your opinion on this.

**Pull request merged**
