### PR TITLE
Make RPC endpoint handler URLs http/https-agnostic

### PR DESCRIPTION
**Pull request by nickray**
* [ ] Updated all relevant documentation in docs
* [ ] Updated all code comments where relevant
* [ ] Wrote tests
* [ ] Updated CHANGELOG.md

### CODE REVIEW

**Comment by melekes** [comment]
CircleCI did not start for some reason...

**Comment by melekes** [comment]
@nickray could you please try and push some minor change? like add a whitespace somewhere (say in `CHANGELOG.md`)

**Comment by melekes** [comment]
> circle doesn't run on forks :(

screen shot 2018-02-27 at 15 57 28

**Comment by melekes** [comment]
Example: https://github.com/tendermint/tendermint/pull/1218

**Comment by melekes** [comment]
😞 don't know what to do. @tendermint/tendermintdev any ideas?

**Comment by ebuchman** [comment]
Not sure whats going on here. The direct link https://circleci.com/gh/tendermint/tendermint/tree/pull%2F1245 is empty.

@nickray can you open a new pull request? maybe its just a bad fluke ?

**Pull request closed without merging**
