### PR TITLE
rpc: log update

### PR DESCRIPTION
**Pull request by alexanderbez**
We INFO log every `ABCIQuery`. This can output a tremendous amount of noise in the logs, can cause cosmovisor to completely crash and slows down the node due to I/O. This log is completely unnecessary.

Let's get this backported into v0.43 and get that into v0.43 and v0.42 releases of the SDK

/cc @marbar3778

### CODE REVIEW

**Review by tychoish — APPROVED** [review]
should this be debug?

**Comment by alexanderbez** [comment]
I don't think so tbh @tychoish

**Comment by ValarDragon** [comment]
Amazing, thanks for getting this in

**Comment by ValarDragon** [comment]
I think it would make sense to include it in debug, but not include the response FWIW

**Pull request merged**
