### PR TITLE
do not use ioutil

### PR DESCRIPTION
**Pull request by faddat**
Please let me know if I should update CHANGELONG_PENDING.md

This **only** removes ioutil, which has been deprecated since go 1.16 --

all other changes can be eliminated by merging:

* #9207 
* #9208 

The other changes were needed only to get ci to pass. 

By dropping the use of io/ioutil, it makes developers using go 1.19 and golangci-lint 1.48.0 not get many, many deprecation warnings.

Note: bet I can make tests pass for no reason by just doing golangci-lint run ./... --fix on this branch

that won't change anything other than formatting.

### note about these pr's

They're basically remote-diagnosis of the ci system, which is why there's many of them, they touch many files, and they're similar.  

Fairly sure at this point that we've got an intermittent test failure that we can just step aside by tossing in an additional commit. 

The suspect tests are:

TestBroadcastTxForPeerStopsWhenReactorStops
TestNodeNewNodeCustomReactors

Note that:

[d788043](https://github.com/tendermint/tendermint/pull/9206/commits/d7880430460f9be90df95172f6746b5ccafc01d6)

passes, except for the linter.  Its diff from the prior commit should be two additional lines in node/doc.go

I did this twice:

[fa8e382](https://github.com/tendermint/tendermint/pull/9206/commits/fa8e38230ea3cb6e8a66958bc9ca0514cdef1793)

passes, except for the linter.  Its diff from the prior commit is two lines added to node/doc.go

---

#### PR checklist

- [x] Tests written/updated, or no tests needed
- [ ] `CHANGELOG_PENDING.md` updated, or no changelog entry needed
- [x] Updated relevant documentation (`docs/`) and code comments, or no
      documentation updates needed

### CODE REVIEW

**Comment by faddat** [comment]
I added two lines to doc.go

test 03 fails intermittently, I think I can get it to pass without changing any code.

**Comment by faddat** [comment]
eventually, it will just get a green tick

**Comment by faddat** [comment]
and it passes

**Comment by thanethomson** [comment]
Please separate out the `ioutil` removal changes from the rest of the linting/tooling-related changes.

**Review by sergio-mena — APPROVED** [review]

**Review by thanethomson — APPROVED** [review]

**Pull request merged**
