### PR TITLE
version: add abci version to handshake

### PR DESCRIPTION
**Pull request by marbar3778**
## Description

- add `AbciVersion` RequestInfo

Closes: #2804

### CODE REVIEW

**Review by melekes — APPROVED** [review]
👍

**Comment by erikgrinaker** [comment]
Do we have a spec PR for this?

**Comment by marbar3778** [comment]
> Do we have a spec PR for this? I think we agreed with Informal that all protocol changes had to go through there first.

was working on pushing the change and got stuck helping a user with gaiacli issue.

**Review by erikgrinaker — APPROVED** [review]
(I'm pretty sure this is uncontroversial though, seems like an oversight really)

**Comment by marbar3778** [comment]
spec change: https://github.com/tendermint/spec/pull/223

**Pull request merged**
