### PR TITLE
lite: remove old lite package in favor of lite2

### PR DESCRIPTION
**Pull request by melekes**
* [ ] ~~Referenced an issue explaining the need for the change~~
* [ ] ~~Updated all relevant documentation in docs~~ already done
* [ ] ~~Updated all code comments where relevant~~
* [ ] ~~Wrote tests~~
* [x] Updated CHANGELOG_PENDING.md

### CODE REVIEW

**Comment by marbar3778** [comment]
ey ey ey 
<a href="https://gitme.me/image?url=https%3A%2F%2Fmedia1.giphy.com%2Fmedia%2FwAxlCmeX1ri1y%2Fgiphy.gif&token=party" data-gitmeme-token="party"></a>

**Comment by marbar3778** [comment]
should lite2 become lite when this is merged?

**Comment by melekes** [comment]
> should lite2 become lite when this is merged?

yeah

**Comment by marbar3778** [comment]
we should rename all instances of lite to light in the repo within this PR in order to adhere to the spec

**Comment by melekes** [comment]
I just thought that this could be done quickly at any moment. No need for this PR to sit here.

**Comment by marbar3778** [comment]
I don't think this is a beaking change as master does not rely on lite anywhere in the repo.

should we reopen this and merge it?

**Comment by melekes** [comment]
what about `tendermint lite` command?

**Comment by melekes** [comment]
> should we reopen this and merge it?

let's wait a little bit until all outstanding lite2 PRs merged

**Comment by marbar3778** [comment]
lite2 https://github.com/tendermint/tendermint/blob/master/cmd/tendermint/commands/lite.go#L17

**Pull request closed without merging**
