### PR TITLE
ADR-037: DeliverBlock

### PR DESCRIPTION
**Pull request by danil-lashin**
ADR for issue #2901

### CODE REVIEW

**Comment by danil-lashin** [comment]
Hi @melekes!

Sure, I will and details to this proposal and then change the label to R4R. 

I think that it is better to force all applications to implement `DeliverBlock` method because it will simplify the whole ABCI architecture of Tendermint, speed up communications and simplify crash recovery. It's worth the effort.

**Comment by danil-lashin** [comment]
Thank you for your patience!
@melekes @xla @ebuchman waiting for your comments.

**Comment by xla** [comment]
@danil-lashin Quick feedback, we merged another ADR in the meantime, so this would be adr038. Sorry for the inconvenience.

**Comment by danil-lashin** [comment]
Not a problem, I've changed the ID.

**Comment by xla** [comment]
@danil-lashin Made a mistake we have pre-assigned ADR numbers in #2313 and yours was indeed 37. sorry for the confusion and noise. :<

**Comment by danil-lashin** [comment]
@xla ok! 😅Just let me know the final decision, I will change PR.

**Comment by xla** [comment]
@danil-lashin 37 is final. :>

**Comment by melekes** [comment]
For people viewing this PR, we're still discussing whenever we actually need `DeliverBlock` functionality https://github.com/tendermint/tendermint/issues/2901#issuecomment-477732701

**Pull request merged**
