### PR TITLE
[WIP] fix non-determinism in consensus/state_test.go

### PR DESCRIPTION
**Pull request by kevlubkcm**
* [ ] Updated all relevant documentation in docs
* [ ] Updated all code comments where relevant
* [ ] Wrote tests
* [ ] Updated CHANGELOG_PENDING.md

Need to make sure all of the events are on the same channel so that they actually "queue" up and pause the consensus.

Note that the default eventBus buffer capacity is already 0. This seems like a potential attack vector

### CODE REVIEW

**Comment by kevlubkcm** [comment]
This is in relation to issue #846

**Comment by melekes** [comment]
Is this still a WIP? Can we get this rebased against the latest `develop`?

**Comment by kevlubkcm** [comment]
yes, this is still relevant. gimme a bit to rebase against develop

**Comment by kevlubkcm** [comment]
oops. i messed up the merge. lemme submit a new PR

**Pull request closed without merging**
