### PR TITLE
PrivValidatorAddr -> PrivValidatorListenAddr. Update ADR008

### PR DESCRIPTION
**Pull request by ebuchman**
PrivValidator follow up re https://github.com/tendermint/tendermint/issues/1255

### CODE REVIEW

**Comment by ebuchman** [comment]
I think maybe we can split the `socketClient` from a `listener` so that we can clarify that Tendermint is the process that actually listens on the socket, but once it has a connection, it functions as the client by sending requests. So maybe `NewSocketClient` is only called once we already have a connection and then it doesn't need to do anything in OnStart

**Comment by ebuchman** [comment]
Really great questions thank you!

> Is it halting any other operations?

Simplest thing to do is probably to halt everything else until we've received a connection. But in an ideal world, we would still boot everything up except maybe the Consensus. I'm not sure exactly how this should be handled, since it might be hard to distinguish between not having received the first connection and the connection failing later. So probably best to just keep it simple at first :). Interested in your thoughts on how we might do it right though.

> Does it expect the signer to connect in a certain timeframe?

I could go either way on this one. Let's flame out for now after a minute or something. Would be valuable to get feedback from validators/users on how they want this to work. It's really a UX question.

> Does it accept at most one connection?

I think we should accept more than 1. It can be a config option. We want folks to be able to set up multiple validators that Tendermint talks to in case one fails. That said, it will be critical that those validators stay synced, since if they don't, they might double signed. So maybe we default to 1 and let folks change it if they want more, but warn them that it means they have to take precaution to keep them synced by running a consensus protocol between the signers (eg. https://github.com/tendermint/tendermint/issues/1185)

> What is the behaviour in case the signer disconnects?

I think we start logging errors and wait a few minutes for it to reconnect. If the signer doesn't come back after a few minutes, perhaps we should panic. 

Maybe @zmanian @tarcieri @nickray want to weigh in on some of this behaviour

**Comment by tarcieri** [comment]
My personal inclination would be for it to continue to run until it receives connection, and perhaps log a warning that there are no signers connected. If it's offering the service, and panicking, it's just one more place for things to go wrong.

**Comment by xla** [comment]
Rebased on latest develop.

**Pull request merged**
