### PR TITLE
consensus: fix round number when handling RoundStepNewRound timeout

### LINKED ISSUE #9229: consensus: wrong round number when handling RoundStepNewRound timeout
**Tendermint version**: d0c345734342a49caea8dcc95f4a4382226708ea

**What happened**:
When handling timeout type `RoundStepNewRound` located at `internal/consensus/state.go`, the code calling `enterPropose` with round 0 all the time:
```go
func (cs *State) handleTimeout(
	ctx context.Context,
	ti timeoutInfo,
	rs cstypes.RoundState,
) {
    /// hiden code ......
	case cstypes.RoundStepNewRound:
		cs.enterPropose(ctx, ti.Height, 0)
}
```

And there are two places to setup this kind of timeout, one is located at `State.enterNewRound`:
```go
func (cs *State) enterNewRound(ctx context.Context, height int64, round int32) {
    /// hiden code ......
	if waitForTxs {
		if cs.config.CreateEmptyBlocksInterval > 0 {
			cs.scheduleTimeout(cs.config.CreateEmptyBlocksInterval, height, round,
				cstypes.RoundStepNewRound)
		}
		return
	}
}
```
and another is located at `State.enterPropose`:
```go
func (cs *State) enterPropose(ctx context.Context, height int64, round int32) {
    /// hiden code
		if proposerWaitTime > 0 {
			cs.scheduleTimeout(proposerWaitTime, height, round, cstypes.RoundStepNewRound)
			return
		}
}
}
```
which are all not necessary to be round 0 with `round` variable equal 0.

**What you expected to happen**:
`enterPropose` should be called with `ti.Round`:
```go
	case cstypes.RoundStepNewRound:
		cs.enterPropose(ctx, ti.Height, ti.Round)
```

### PR DESCRIPTION
**Pull request by fatcat22**
Closes #9229

---

#### PR checklist

- [ ] Tests written/updated, or no tests needed
- [x] `CHANGELOG_PENDING.md` updated, or no changelog entry needed
- [ ] Updated relevant documentation (`docs/`) and code comments, or no
      documentation updates needed

### CODE REVIEW

**Review by cmwaters — APPROVED** [review]
LGTM

@milosevic any idea why it was like this in the first place?

**Comment by cason** [comment]
Is there a test case that reveals this problem?

**Comment by cason** [comment]
I can double-check, but this timeout is scheduled when the node enters a height. This means that when it is triggered, the round to start is always 0.

**Comment by cason** [comment]
This timeout is scheduled [here](https://github.com/tendermint/tendermint/blob/404fca5fcc960e86db18b0ee2e41092d66865f49/consensus/state.go#L969) and [here](https://github.com/tendermint/tendermint/blob/404fca5fcc960e86db18b0ee2e41092d66865f49/consensus/state.go#L1038). In both cases, round is zero.

**Comment by fatcat22** [comment]
> This timeout is scheduled [here](https://github.com/tendermint/tendermint/blob/404fca5fcc960e86db18b0ee2e41092d66865f49/consensus/state.go#L969) and [here](https://github.com/tendermint/tendermint/blob/404fca5fcc960e86db18b0ee2e41092d66865f49/consensus/state.go#L1038). In both cases, round is zero.

You are right, sorry about my mistake.  I was brosing the master branch at first, for after reading the [development-procedure](https://github.com/tendermint/tendermint/blob/main/CONTRIBUTING.md#development-procedure)  document, I supposed that master branch is the default dev branch. (Am I wrong anain,  or the doc is out of date?)

Anyway, I still advise that using `ti.Round` but not `0`, or adding assertion like `if ti.Round != 0 panic(...)`. It up to you, if you think there's no need to do that, you can close this PR directly.

**Comment by cason** [comment]
No problems, and to nothing to be sorry about, you presented an evidence that this behavior is not clearly documented in the code.

**Comment by cason** [comment]
We migrated from `master` to `main` few weeks ago.

**Review by williambanfield — APPROVED** [review]
I still think we should make the change here, even if the it doesn't have an immediate effect. I wrote the code that used this method in `master` and assumed that it actually used the round number value. It introduced a bug just by using the code that one would expect.

**Review by tychoish — APPROVED** [review]

**Pull request merged**
