### PR TITLE
build: use only goleveldb

### PR DESCRIPTION
**Pull request by faddat**
PHILOSOPHY.md specifies that there should be only one single obvious way to do things.  

While the cosmos-sdk suffers from some database-related and iavl-related performance issues, tendermint does not. 

Instead of refactoring to sqlite, which would be a great deal of code and a fairly uncertain path, this PR takes only goleveldb and memdb from tm-db and allows us to:

* reduce build complexity
* reduce test complexity
* support more system architectures
* reduce configuration complexity
* deprecate tm-db
* improve code readability
* highlight the tm-db -> cosmos-db migration path

There's never been an issue with goleveldb in Tendermint itself, so instead of reinventing the wheel, this PR eliminates the database choices that make a number of tasks related to this repository far more complex than they need to be. 

---

#### PR checklist

- [x] Tests written/updated, or no tests needed
- [x] `CHANGELOG_PENDING.md` updated, or no changelog entry needed
- [x] Updated relevant documentation (`docs/`) and code comments, or no
      documentation updates needed

### CODE REVIEW

**Comment by faddat** [comment]
Hi-- this PR should be changed to include tm-db's commit history.

I talked to @liamsi about the "delete everything" commit in tendermint's commit history, and learned that it was bringing together consensus and abci.  I'd like to make this one, more like that one.

**Comment by ethanfrey** [comment]
I cannot comment on the code, but agree with the point.

Tendermint should strive to the simplest secure way to do what it does (which is complex enough).
We don't need to complicate it more than needed with extra abstractions and options.

If goleveldb doesn't work, we find a new one... maybe support both for some time as a transition, then transition to only the other one. But if it does work, why worry about something else.

**Comment by ethanfrey** [comment]
What could use a different db is events.
But loosely coupled, not a postgresql driver here. And then still custom query language that tried to hit the db.

Like just dump out events to a simple message queue (enabled/disabled in config) and there can be external solutions to consume those events, index them, expose APIs. These external APIs may be better or worse or even buggy. But very importantly *they will not impact the security or stability of Tendermint*

I'm all for removing code and allowing non-consensus stuff to be handled elsewhere

**Comment by thanethomson** [comment]
While I agree in terms of the philosophy, we unfortunately cannot accommodate this specific change, as we believe there's still quite a bit of work to be done before we can settle on LevelDB, especially in light of some of our planned changes toward improving storage efficiencies for operators. See #9749.

We also cannot accommodate such a substantial breaking change in our current development cycle as we work towards Tendermint v0.38 with full ABCI 2.0 (a.k.a. ABCI++). Our approach to technical risk management from v0.37 onwards involves making smaller breaking changes across releases, while attempting to release more frequently. The soonest we may consider such a change will probably be in the v0.39 release cycle (Q1/Q2 of 2023), and will have to be according to #9749.

@faddat, if you would like to help us make substantial changes, please come discuss with us synchronously in our community call first so we can share our current priorities and plans?

> Like just dump out events to a simple message queue (enabled/disabled in config) and there can be external solutions to consume those events, index them, expose APIs. These external APIs may be better or worse or even buggy. But very importantly they will not impact the security or stability of Tendermint

@ethanfrey have you had a chance to evaluate #9437? I still have some tweaks planned for that ADR to address some of the comments, but the overarching philosophy is to provide a configurable way to offload the requisite data (e.g. events) such that an external process can index and expose it however it wants.

**Comment by ethanfrey** [comment]
> @ethanfrey have you had a chance to evaluate https://github.com/tendermint/tendermint/pull/9437? I still have some tweaks planned for that ADR to address some of the comments, but the overarching philosophy is to provide a configurable way to offload the requisite data (e.g. events) such that an external process can index and expose it however it wants.

No, I haven't seen the ADR. This is something I brought up in late 2017 as the current event system was being built. I am a bit tired of being the grumpy old man who gives advice that is ignored and ends up saying "I told you so". So I just ignore most discussions these days.

I took a quick look at #9437 and agree with the general direction. But I would probably go more radical in the redesign / simplification. Not sure why only one "external companion service", and that could use some examples. I have quite some ideas here and have been sketching this out trying to get a usable indexing service for CosmWasm contracts.

If people will seriously listen to and discuss my ideas, I can make some input. But I've spent years of being ignored by all core teams on architecture, so very little desire to spend hours on this without serious engagement of all decision makers on the architecture.

**Pull request closed without merging**
