### PR TITLE
autofile processTicks

### PR DESCRIPTION
**Pull request by bradyjoestar**
In the `autofile.go`&`group.go` of `libs/autofile` ,

`processTicks` only run once .

So I add a loop to continue to listen the time.Ticker:

```
for {
		select {
		case <-af.ticker.C:
			af.closeFile()
		case <-af.tickerStopped:
			return
		}
	}
```

### CODE REVIEW

**Comment by bradyjoestar** [comment]
circlecI told me that
```
#!/bin/bash -eo pipefail
bash test/app/test.sh
bash: test/app/test.sh: No such file or directory
Exited with code 127
```

But what I commited didn't included those files.Be grateful for your help!

**Comment by bradyjoestar** [comment]
@melekes  of course! I was supposed to do it.
 It will take some time for my lack of experience.

**Comment by melekes** [comment]
Same thing here.

_Hey again! We've committed a quick fix for CircleCI. Could you please rebase your branch against latest develop and force push (git push -f)?_

**Comment by ebuchman** [comment]
Sorry we missed this earlier - will merge into https://github.com/tendermint/tendermint/pull/2261 and get it released tonight. 

Thanks!

**Comment by bradyjoestar** [comment]
I‘m sorry but I found a test_cover failure, I will close this pr until I solve the bug.

After then I will pr the `test` solely.

It's better to merge the  libs/autofile: bring back loops #2261 in consideration of time. :smile:

**Pull request closed without merging**
