### PR TITLE
Add missing endpoints to HTTPClient and LocalClient

### PR DESCRIPTION
**Pull request by danil-lashin**
* [ ] ~~Updated all relevant documentation in docs~~
* [x] Updated all code comments where relevant
* [x] Wrote tests
* [x] Updated CHANGELOG_PENDING.md

### CODE REVIEW

**Comment by danil-lashin** [comment]
Also, we need to update the `Client` interface. Where should we put this methods? May be introduce new `MempoolClient`?

**Comment by melekes** [comment]
> Also, we need to update the Client interface. Where should we put this methods? May be introduce new MempoolClient?

`MempoolClient` sounds OK

Can we also add tests for these methods? Thanks 👍

**Comment by melekes** [comment]
```
--- FAIL: TestTx (0.06s)
	rpc_test.go:344: client 0, case 0
	Error Trace:	rpc_test.go:356
	Error:      	Should be zero, but was 1
	Test:       	TestTx
	rpc_test.go:344: client 0, case 1
	Error Trace:	rpc_test.go:356
	Error:      	Should be zero, but was 1
	Test:       	TestTx
	rpc_test.go:344: client 0, case 2
	rpc_test.go:344: client 0, case 3
	rpc_test.go:344: client 0, case 4
	rpc_test.go:344: client 0, case 5
	rpc_test.go:344: client 1, case 0
	Error Trace:	rpc_test.go:356
	Error:      	Should be zero, but was 1
	Test:       	TestTx
	rpc_test.go:344: client 1, case 1
	Error Trace:	rpc_test.go:356
	Error:      	Should be zero, but was 1
	Test:       	TestTx
	rpc_test.go:344: client 1, case 2
	rpc_test.go:344: client 1, case 3
	rpc_test.go:344: client 1, case 4
	rpc_test.go:344: client 1, case 5
FAIL
```

not sure why TestTx is failing. seems not relevant to the changes made in this PR

**Comment by danil-lashin** [comment]
@melekes, this is because of new tests. Seems like TestTx expects empty mempool, but previous test leaves it with 1 tx. I will try to fix that.

**Pull request merged**
