### PR TITLE
adr: light client implementation

### LINKED ISSUE #2133: Create an ADR for lite/provider
See: https://github.com/tendermint/tendermint/pull/1815/files#r205110595

We should refactor lite/* after launch, to save components of the full commit rather than the whole full commit itself.  This refactor should start with an ADR that describes the new interfaces.

Post-launch, as it doesn't affect the chain itself so upgrading is relatively easy.

Probably also should include ADR for InquiringCertifier (to be renamed as DynamicVerifier).

### PR DESCRIPTION
**Pull request by melekes**
📝 [RENDERED](https://github.com/tendermint/tendermint/blob/4faa12f5978590d7fe50e7c061e06f335e941186/docs/architecture/adr-046-light-client-implementation.md)

Closes #2133

* [x] Referenced an issue explaining the need for the change
* [x] Updated all relevant documentation in docs
* [ ] ~~Updated all code comments where relevant~~
* [ ] ~~Wrote tests~~
* [ ] ~~Updated CHANGELOG_PENDING.md~~

### CODE REVIEW

**Comment by melekes** [comment]
> Do we need to add anything about the sequential or bisection methods?

don't see a need to duplicate https://pkg.go.dev/github.com/tendermint/tendermint/lite2?tab=doc#SequentialVerification

**Comment by cmwaters** [comment]
Okay, perhaps reference it? Or I guess it's fine if you don’t

**Comment by melekes** [comment]
> Okay, perhaps reference it?

as per our discussion, I don't think ADR should be a reference to API, but merely an explanation why certain choices were made (like having >= 1 witness, etc.)

**Comment by cmwaters** [comment]
Ah okay, I guess I’m still understanding the exact purpose of adr‘s and the level of context that is required.

**Pull request merged**
