### PR TITLE
Adding adr-048

### PR DESCRIPTION
**Pull request by b00f**
* [ ] Referenced an issue explaining the need for the change
* [x] Updated all relevant documentation in docs
* [ ] Updated all code comments where relevant
* [ ] Wrote tests
* [ ] Updated CHANGELOG_PENDING.md

### CODE REVIEW

**Comment by b00f** [comment]
@ebuchman May I know your idea about this?

**Comment by melekes** [comment]
This is an interesting idea!

> I fully support the TTL additions

can't you do it already via app & check_tx?

> Personally, I think transparency and auditability is a core concept to support.

This seems to be the culprit ☝️ 

@b00f what are the use-cases behind this?

**Comment by b00f** [comment]
> can't you do it already via app & check_tx?

No. Since a normal tx hasn't TTL. but stamped_tx has. An stamped_tx can be checked if it's alive yet in check_tx.

Transaction will be individual entity by stamping it.

**Comment by b00f** [comment]
> What are the use-cases behind this?

Many use-cases. For example:
* Reducing the size of blockchain. Blocks can only keep tx_hash not whole Tx data. 
* TTL can help to mange Txs in a better way. 
* stamped_tx binds to the main fork. So it helps security of blockchain.

**Comment by melekes** [comment]
> No. Since a normal tx hasn't TTL

I don't understand. Tendermint does not know content of transaction. You can put whatever you want in it - TTL, version, anything else you desire.

**Comment by ethanfrey** [comment]
The TTL stuff sounds like cosmos-sdk zone.
But pruning historical blocks (or not storing all tx data) would need a change in tendermint

**Comment by b00f** [comment]
> But pruning historical blocks (or not storing all tx data) would need a change in tendermint

This ADR is very general and can be applied to any blockchain. But since I love Tendermint I suggested it here.

If you look carefully it doesn't necessary need to change anything in Tendermint. Two interesting facts:
1- Application validate transactions. 
2- Tendermint is agnostic about transactions data

It will be like this: Application receive a Tx. Validate it and save it to its own DB and probably gossip it. (There is no consensus about this DB). Application now can only pass the hash of TX to the Tendermint. Then Tendermint do its routine works. If an application has that Tx in its own DB, simply can get it ad verify it, otherwise request it from other applications. 

Note: Mempool can move to app layer for better implementation. 

In this scenario block id will be simply block hash. We can get rid of block_parts, which is a little bit complicated. block never get that big to be partitioned.

**Comment by marbar3778** [comment]
>Interesting proposal, thanks for the writeup. It probably doesn't belong as an ADR yet, since it's more of a protocol change than an architecture document, but we don't have a better place for that yet. We're working on setting up a better process for RFCs to make protocol changes like this. cc @marbar3778

https://github.com/tendermint/spec/tree/master/rfc

**Comment by melekes** [comment]
> But since I love Tendermint I suggested it here.

❤️ 💙 💚 

> Note: Mempool can move to app layer for better implementation.

that's the plan

**Comment by b00f** [comment]
> How would you see this fitting in with Tendermint/ABCI though?

No big changes in Tendermint. Alos creating blocks will be more simple. Block structure in Tendermint is a bit complicated. ABCI also can be untouched. In better implementation mempool moves to the app side and Application will handle Txs. 

For coinbase blockchain like Bitcoin, this is very easy to implement and very useful. Transactions individually can be checked if it is unspent.
For state based blocckhain like Tendermint, we need to find a ways to validate a block without executing all transactions from genesis block. Maybe the perfect solution is a Coinbase blockchain with Tendermint core.

I wanted to implement it in Berlin hackathon, but unfortunately my visa get rejected. So sad ;(

**Comment by melekes** [comment]
@b00f would you mind to submit this as an RFC to https://github.com/tendermint/spec/tree/master/rfc?

As for app-level mempool, it's in the pipeline https://github.com/tendermint/tendermint/issues/3900.

**Comment by b00f** [comment]
@melekes Please check here. 
https://github.com/tendermint/spec/pull/58

**Pull request closed without merging**
