### PR TITLE
blockchain: update the maxHeight when a peer is removed

### PR DESCRIPTION
**Pull request by melekes**
Refs #2699

* [x] Updated all relevant documentation in docs
* [x] Updated all code comments where relevant
* [x] Wrote tests
* [x] Updated CHANGELOG_PENDING.md

### CODE REVIEW

**Comment by ancazamfir** [comment]
Changes look good to me!  I think they solve the critical issue caused by maxPeerHeight not being updated.

One minor comment. When we remove the peer with highest height, there may be requesters allocated for the higher hights, higher than the new pool.maxPeerHeight, left in pool.requesters map (up to maxTotalRequesters = 600). They will have nil block and peerID "", this is done by func (bpr *bpRequester) reset()
Also the pool.numPending includes these requesters in the count. I believe the requesters remain allocated even after blockchain reactor pool is stopped and the switch to consensus happens.
Maybe we could cleanup them in OnStop()? Also the pool.peers are left around, are they useful once the blockchain reactor is stopped?

**Comment by melekes** [comment]
> One minor comment. When we remove the peer with highest height, there may be requesters allocated for the higher hights, higher than the new pool.maxPeerHeight, left in pool.requesters map (up to maxTotalRequesters = 600)

Ethan said we only request blocks from peers if {peer.height} >= {needed block height}. So there should be no requesters (e.g. `peerB.NewMaxHeight 10 ... peerA.OldMaxHeight 12` deleting peerA should result in removing all requesters with 11-12 heights) after we delete peer with max height.

> Also the pool.numPending includes these requesters in the count. I believe the requesters remain allocated even after blockchain reactor pool is stopped and the switch to consensus happens.
Maybe we could cleanup them in OnStop()?

Yeah, we normally don't clean up such things. I.e. services can't be reset. The important thing is to make sure we decrement/increment when needed, we cleanup all structs allocated for a peer when it's removed and so on.

**Comment by ancazamfir** [comment]
> So there should be no requesters (e.g. `peerB.NewMaxHeight 10 ... peerA.OldMaxHeight 12` deleting peerA should result in removing all requesters with 11-12 heights) after we delete peer with max height.

Where do we remove them? I see that we "reset" them but they seem to be staying there. The only place where we remove requester is in PopRequest().

> If you want to work on `blockchain` package to simplify the code / streamline the logic, please go ahead.

I will probably try something there but after talking to Zarko today it seems that it is a bigger change that may take longer. I believe your fix should go in ASAP with or without the cleanup (if I am right which is not clear yet).

**Comment by melekes** [comment]
> Where do we remove them? I see that we "reset" them but they seem to be staying there. The only place where we remove requester is in PopRequest().

hmm.. can't find it either. I don't know what's the deal with `reset` method. And you may be right that `requesters` map is never cleaned up.

**Comment by ancazamfir** [comment]
> hmm.. can't find it either. I don't know what's the deal with `reset` method.

Not entirely sure either, but I think it's to retry the block request with another peer at that height or higher.

**Comment by ebuchman** [comment]
Merged develop. Had to resolve conflict to support https://github.com/tendermint/tendermint/commit/976b1c2ef73e557a702ef17600e1eeaf4865f292

**Pull request merged**
