### PR TITLE
C level stat to do

### PR DESCRIPTION
**Pull request by bradyjoestar**
In the `c_level_db.go`,the keys of Stats is Null.
```
// Implements DB.
func (db *CLevelDB) Stats() map[string]string {
	// TODO: Find the available properties for the C LevelDB implementation
	keys := []string{}
```

I searched the [golang/leveldb/db.h](https://github.com/google/leveldb/blob/09217fd0677a4fd9713c7a4d774c494a7d3c1f15/include/leveldb/db.h)
and in the line of `115` to `124`,it showed:
```
 // Valid property names include:
  //
  //  "leveldb.num-files-at-level<N>" - return the number of files at level <N>,
  //     where <N> is an ASCII representation of a level number (e.g. "0").
  //  "leveldb.stats" - returns a multi-line string that describes statistics
  //     about the internal operation of the DB.
  //  "leveldb.sstables" - returns a multi-line string that describes all
  //     of the sstables that make up the db contents.
  //  "leveldb.approximate-memory-usage" - returns the approximate number of
  //     bytes of memory in use by the DB.
```

### CODE REVIEW

**Comment by bradyjoestar** [comment]
Happy for your coming back.:smile:

**Comment by melekes** [comment]
@bradyjoestar  can you commit a dummy change (add whitespace or something) to restart CircleCI? It looks like they have fixed the above problem.

**Comment by melekes** [comment]
Hey again! We've committed a quick fix for CircleCI. Could you please rebase your branch against latest develop and force push (git push -f)?

**Comment by melekes** [comment]
screen shot 2018-08-27 at 14 12 57

You've probably done something wrong. These commits ^^^ should not be here.

https://stackoverflow.com/questions/7244321/how-do-i-update-a-github-forked-repository#7244456

```
git fetch upstream
git checkout develop
git rebase upstream/develop
```

**Comment by bradyjoestar** [comment]
sure , I will do it later on :ok_hand:

**Comment by ebuchman** [comment]
Thanks @bradyjoestar - I'm going to close it for now but please reopen here or a new once you fix the commits

**Pull request closed without merging**
