### PR TITLE
changelog: Add links everywhere, and script to auto-add links.

### PR DESCRIPTION
**Pull request by ValarDragon**
* [ ] Updated all relevant documentation in docs - should I document this anywhere? The comments in the script seem sufficient, unless we have another docs page for scripts
* [X] Updated all code comments where relevant
* [X] Updated CHANGELOG_PENDING.md

### CODE REVIEW

**Comment by ebuchman** [comment]
OMG this is amazing thank you !

**Comment by ebuchman** [comment]
Can we get just the script against https://github.com/tendermint/tendermint/pull/2340 please ? I made more changes there - will run it my self when done editing the changelog

**Comment by ValarDragon** [comment]
Sure!

**Comment by ValarDragon** [comment]
Closing in favor of #2342

**Pull request closed without merging**
