### PR TITLE
[crypto] fix sr25519 from raw import

### PR DESCRIPTION
**Pull request by sunnya97**
Fixes sr25519 pubkey generation and signing when importing from raw bytes

* [ ] Referenced an issue explaining the need for the change
* [ ] Updated all relevant documentation in docs
* [ ] Updated all code comments where relevant
* [ ] Wrote tests
* [ ] Updated CHANGELOG_PENDING.md

### CODE REVIEW

**Comment by marbar3778** [comment]
does this need a bump in the dependency? @sunnya97 If not could we do it anyways?

**Comment by marbar3778** [comment]
also in the last PR to add sr25519 we didnt add it to `crypto/multisig` codec. Should we add it in this PR or this was on purpose?

**Comment by sunnya97** [comment]
@marbar3778 You mean bump go-schnorrkel?  Yeah we can do that.

Also, good catch.  SR25519 should really have its own custom multisig eventually (because it can be an aggregate signature),  but there's no reason it can't also be in a normal multisig with other key types as well.  I'll add it to the multisig codec this PR as well.

**Comment by marbar3778** [comment]
yea,  bump go-schnorrkel if possible

**Comment by sunnya97** [comment]
Bumped `go-schnorrkel` 👍

**Pull request merged**
