### PR TITLE
p2p: Remove data race bug in netaddr stringer

### PR DESCRIPTION
**Pull request by alexanderbez**
## Description

Remove concurrent write access bug by removing the memoized string representation of a `NetAddress`.

Closes: #5047

### CODE REVIEW

**Comment by alexanderbez** [comment]
@marbar3778 can we get this in for 0.34?

**Comment by tessr** [comment]
Also, yes, I think we should be able to get this into 0.34. Were you able to confirm that it fixed the multiple-nodes-in-one-process issue?

**Comment by alexanderbez** [comment]
@tessr yes, I've added a very contrived test case that even demonstrates this. You'll see if you run it with `--race` it won't fail.  WRT to the commit messages sure, but they'll ultimately be squashed no? Unless you keep them in the commit body when squashing.

**Comment by tessr** [comment]
Yeah—sorry, I should’ve specified _the commits on master_. I don’t care what they are in the PR as long as they are correctly formatted when they land! 
GitHub <notifications@github.com> wrote:
“@tessr yes, I've added a very contrived test case that even demonstrates this. You'll see if you run it with --race it won't fail. WRT to the commit messages sure, but they'll ultimately be squashed no? Unless you keep them in the commit body when squashing.”

**Pull request merged**
