### PR TITLE
Merge master back to develop

### PR DESCRIPTION
**Pull request by melekes**

### CODE REVIEW

**Comment by melekes** [comment]
> This means we currently do changelogs for minor/fix releases directly into master?

Yes. At least that is how it was done before.

**Comment by melekes** [comment]
Can I squash this PR? Not sure

**Comment by melekes** [comment]
https://github.com/tendermint/tendermint/pull/3339

**Comment by Liamsi** [comment]
I think merging master to develop should not come with squashing:
image
The 3 commits from master won't make it to develop. Or do we want develop and master to diverge?

**Pull request merged**
