### PR TITLE
state: move package to internal

### PR DESCRIPTION
**Pull request by tychoish**
This is the second PR in the series of #6937 cleanups.

I'm not sure that this is something we should do right now (that's
fine! I did this all in about 10 minutes, editing the files entirely
with find/sed/xargs). The questions that we should ask ourselves

- this makes a number of public functions in the `inspect` module
  impossible to construct/use outside of our package. We could move
  inspect to an internal package, or change `inspect.New` in some way.

- the rpc/core package now depends/uses a bunch of types that are
  internal, and it might make sense to move this package into the
  internal package.

### CODE REVIEW

**Comment by cmwaters** [comment]
> this makes a number of public functions in the inspect module
impossible to construct/use outside of our package. We could move
inspect to an internal package, or change inspect.New in some way.

I think the rpc package within inspect can probably be for the most part private. I can't see why someone would want to use it to construct their own server without just using the `Inspector` itself. 

> the rpc/core package now depends/uses a bunch of types that are
internal, and it might make sense to move this package into the
internal package.

But there are parts of the RPC that need to remain public like all the response types right? And the RPC clients that external users may want to use. I think there's nothing wrong with depending on internal packages.

**Comment by tychoish** [comment]
> I think the rpc package within inspect can probably be for the most part private. I can't see why someone would want to use it to construct their own server without just using the Inspector itself.

I think, in this case, the `inspect/rpc` package should become `inspect/internal/rpc`. 

I'm also coming around to the idea that `inspect.New()` should probably become `inspect.makeInspector()` because it's arguments are publicly constructable. 

I'll let @williambanfield weigh in on this. 

> But there are parts of the RPC that need to remain public like all the response types right? And the RPC clients that external users may want to use. I think there's nothing wrong with depending on internal packages.

It depends a little bit: depending on internal packages is 100% ok, but exporting dependencies that aren't externally constructable, is kind of a problem, as it's impossible for external consumers to write code that can compile that calls/uses this code.

**Comment by creachadair** [comment]
The changes that are here so far seem fine. I think we should be a bit more cautious about which parts of `rpc` we make internal—for example, the response types are surfaced to the clients, and I think that's probably the right thing.

One additional thing we should be careful about is making a package internal that defines a type a caller needs to refer to, even if only indirectly through a public package. Otherwise the user of the external package can't even utter the names of the types it needs. We can do it, but I think we'll want to be somewhat deliberate about which bits we move around.

**Comment by williambanfield** [comment]
> I think, in this case, the inspect/rpc package should become inspect/internal/rpc.

This change seems pretty reasonable to me. There's really no need for external users of tendermint to rely on these libraries. 

My mild preference would be to do https://github.com/tendermint/tendermint/issues/6855 and have the routes and types be publicly accessible. They're part of our public API as RPC endpoints anyway so maintaining them that way seems fine. This would also basically eliminate much of the need for the `inspect/rpc` package as is. 


> I'm also coming around to the idea that inspect.New() should probably become inspect.makeInspector() because it's arguments are publicly constructable.

Hmm, I'm not totally sure I get the reasoning behind this? If all of its args are public types, shouldn't that be more reason to keep it public, since consumers can then actually use the constructor? I think it's very unlikely someone will consume the inspect API as part of a library, so I'm generally fine with internalizing as much of it as possible. Part of me wants to keep it external so that people can play around with it, but ultimately I feel that Tendermint's Go API should really be as small as possible so internalizing  constructors like that is really the right course.

**Comment by creachadair** [comment]
> > I'm also coming around to the idea that inspect.New() should probably become inspect.makeInspector() because it's arguments are publicly constructable.
> 
> Hmm, I'm not totally sure I get the reasoning behind this? If all of its args are public types, shouldn't that be more reason to keep it public, since consumers can then actually use the constructor? I think it's very unlikely someone will consume the inspect API as part of a library, so I'm generally fine with internalizing as much of it as possible. Part of me wants to keep it external so that people can play around with it, but ultimately I feel that Tendermint's Go API should really be as small as possible so internalizing constructors like that is really the right course.

I agree with the idea of reducing API surface area, but in this case I don't think unexporting the constructor is the right tool for that job. Since unexporting is per-package (not per-module), unexporting hurts even our own "internal" uses within the rest of the core. I don't think that's worth the minor benefit of removing the constructor name from the godoc, unless it protects us from hurting ourselves in some other way. I don't really see that here.

IMO: A good rule of thumb for unexporting is that, f you need the functionality to write tests in a separate `pkg_test` package, it should almost always be exported from the package itself. 

Exporting is just too narrow a tool to lean on too heavily. If we do it, it shouldn't be on "general principle" grounds, but because we really know the name isn't used outside the package (even by its tests!)

That said: I'm open to counter-arguments. 🙂

**Comment by tychoish** [comment]
> I agree with the idea of reducing API surface area, but in this case I don't think unexporting the constructor is the right tool for that job. Since unexporting is per-package (not per-module), unexporting hurts even our own "internal" uses within the rest of the core. I don't think that's worth the minor benefit of removing the constructor name from the godoc, unless it protects us from hurting ourselves in some other way. I don't really see that here.

I don't believe that there's a use case for constructing nodes *except* from the config object, except potentially for testing workflows, which are decidedly internal. For example, don't expect to allow external users to interact with low-level data structures (`state.Store` and `state.State`,) and are moving those to be internal (which is a good move in support of database work,.) We don't expect "inspect' nodes to run currently with production nodes (in a single process), and we don't provide an external way to access these underlying APIs (state/store, etc.) in the production node case.

**Comment by creachadair** [comment]
> I don't believe that there's a use case for constructing nodes _except_ from the config object, except potentially for testing workflows, which are decidedly internal. For example, don't expect to allow external users to interact with low-level data structures (`state.Store` and `state.State`,) and are moving those to be internal (which is a good move in support of database work,.) We don't expect "inspect' nodes to run currently with production nodes (in a single process), and we don't provide an external way to access these underlying APIs (state/store, etc.) in the production node case.

That's all fair. However, I think "except for testing" is exactly why we shouldn't defend against "outside users" in the API of an "inside package". If the tests can't create one except by wiring up a whole config, then our job is harder even if external users don't use it. I realize right now we're kind of stuck with that because node has a lot of other dependencies. 

I have some hope that if we make packages usable in a self-contained manner, we can dump some of the mocks and other fol-de-rol we currently have lying around the repo as workarounds. 

I think the right way to look at this is not in terms of "outside users"—we protect ourselves from external dependencies using the build tool's "internal" directory hack. Once we're inside that boundary, I think we should view this as a normal library that we don't need to defend from abuse (except by ourselves). 😀

**Comment by tychoish** [comment]
I think moving `inspect` to `inspect/internal` (which is #6966) makes most of this kind of moot. 

`state` isn't part of our public API, and things that depend on it probably shouldn't be either. This is only really an issue along the margins, I think.

**Review by creachadair — APPROVED** [review]

**Pull request merged**
