### PR TITLE
docker: release Linux/ARM64 image

### PR DESCRIPTION
**Pull request by odidev**
## Description

1. The build tendermint process has been added to the Dockerfile because github actions do not support direct AArch64 builds, and we require the tendermint binary to build tendermint docker image for both the platforms.
2. Installed QEMU via docker.yml file, and added platforms as "linux/amd64" and "linux/arm64" to the buildx, to release both architecture specific docker images for tendermint. Changed the context to the root of the package, to ease the build tendermint process via Dockerfile.
3. Added the build tendermint part to the Dockerfile in stage 1, and copied the generated binary to the desired location in stage 2. Changed the base image to "golang:1.15-alpine", to incorporate the go1.15 installation.

Signed-off-by: odidev <odidev@puresoftware.com>

### CODE REVIEW

**Comment by tessr** [comment]
Hi odidev, 

Thanks for this contribution. We are meticulous about understanding the motivation behind any build/tooling changes. Can you zoom out and first describe the problem you have, and then explain how this PR will fix it?

**Comment by odidev** [comment]
@tessr 
Thanks for the response.

I am working on adding Linux/ARM64 support to a project that uses both Tendermint binary and docker image.

I have already raised a PR for releasing binaries for Linux/ARM64 and thanks to you that it got merged and binaries have been released. But the docker image is only available for Linux/AMD64. Hence, this PR is focused to release Tendermint docker images for both Linux/AMD64 and Linux/ARM64 via workflows using buildx.

Tendermint uses Github actions to first build the tendermint binary and then copy it to the Dockerfile, and release the docker image. However, github actions do not support direct AArch64 builds, so generating the Linux/ARM64 tendermint binary via workflows is not possible. 

To accomplish this build process, I have moved the ‘build tendermint’ stage into the Dockerfile itself. Buildx uses QEMU to create Linux/ARM64 environments, and hence will build tendermint from source to generate the tendermint binary inside the Dockerfile itself in stage 1. Further in stage 2, the binary is just copied to the desired location. Breaking the Dockerfile in multi-stage will reduce the size of the docker image. 

The base image has been replaced with ‘golang:1.15-alpine’, because the build requires Go 1.15 or above, and this base image incorporates Go 1.15.6 along with the alpine environment.
The ‘context’ clause in the workflows has been set to the root of the project, to execute the ‘make build-linux’ command. Henceforth, the COPY clause in the Dockerfile has been changed from “./docker-entrypoint.sh /usr/local/bin/” to “./DOCKER/docker-entrypoint.sh /usr/local/bin/”.

Please let me know if you need more information.

**Comment by tessr** [comment]
I see - I think that all sounds reasonable. @marbar3778: while you're looking at Docker stuff, can you take a look at this PR, as well?

**Review by marbar3778 — APPROVED** [review]
LGTM. Thank you for the contribution.

**Pull request merged**
