### PR TITLE
Create adr-036-app-data.md

### PR DESCRIPTION
**Pull request by b00f**
* [ ] Updated all relevant documentation in docs
* [ ] Updated all code comments where relevant
* [ ] Wrote tests
* [ ] Updated CHANGELOG_PENDING.md

### CODE REVIEW

**Comment by ebuchman** [comment]
I don't think we should do this, at least not in the header. The Header isn't the right place to store arbitrary information like this. If anything, we want to reduce the header size, and make it more deterministic, for instance https://github.com/tendermint/tendermint/issues/2530.

We could consider putting some app-returned data into the block itself, but we'd have to allocate some space in the block for this, and probably not much. For instance, the block.Data might become:

```
type Data struct {
  Proposer []ProposerData // proposer data included in block by the proposer
  Txs Txs // user data included in block by proposer
  App []AppData // app data included in block by the app
}
```

and we'd set some limit on the size of []AppData and []ProposerData. But all of this is more parameterization and complexity, and especially the AppData part can effectively be done already by the App, so I'm not sure it's worth it right now. The ProposerData is a separate issue.

The app can also return Data in every DeliverTx, but note we don't provide a Data field in EndBlock, just Tags and updates. It would be much simpler to just consider returning the data in EndBlock, and making it queryable (like with tags and other result data), rather than putting it in the block. Can we start with that?

**Comment by ebuchman** [comment]
I'm going to close this for now - happy to see a new one with more details around the various considerations as mentioned above.

**Comment by b00f** [comment]
Thanks for your comment. 
I think we both agree that Tendermint should give some space for the application to save some data inside the block. But where and how?
I do agree that header might not be a good place. But I believe it should pass though EndBlock method (Before committing phase).

I have a question. Can application use Tags for saving data inside the block? For example `tag.Fee = 100`.
I remember when I send the original PR there was no `Tags` in `ResponseEndBlock`. If yes, then we have already what we need!

**Comment by ebuchman** [comment]
Tags aren't stored inside the block itself, but they are indexed in the node and queryable, just like DeliverTx response data (and tags). Is that sufficient, or is there some strong reason why the data must be directly in the block itself?

**Comment by b00f** [comment]
Tendermint as a service should provide more and request less ! I think there will be strong requests by applications for saving some deterministic data (not only txs) inside the block. 
Please keep this silent for the moment. If anyone else has same request later please let me know, then we can discuss more and decide the best for lovey Tendermint project. ;) cheers and thanks

**Comment by ebuchman** [comment]
Ok, thanks @b00f 

>  I think there will be strong requests by applications for saving some deterministic data (not only txs) inside the block.

If you want to provide some of your own rationale for why you think this is the case, would be happy to hear. Maybe this is a good topic for a forum post. We can gather feedback/sentiment there, before it turns into a github issue again.

Thanks!

**Pull request closed without merging**
