### PR TITLE
standardize PRNG access

### LINKED ISSUE #1343: all: standardize use of rand
Standardize use of rand in the codebase. 

We should exclusively use https://github.com/tendermint/tmlibs/blob/develop/common/random.go

See eg. p2p where we make various use of different rand sources.

### PR DESCRIPTION
**Pull request by tomc974**
Fixes #1343
Depends on https://github.com/tendermint/tmlibs/pull/191 https://github.com/tendermint/tmlibs/pull/194

Replaces usage of `math/rand` with `tmlibs` equivalent in non-test files.

Should we also replace `math/rand` in test files?

### CODE REVIEW

**Comment by tomc974** [comment]
Now that `tmlibs` dependencies have been merged, could someone re-run the CI?

**Comment by melekes** [comment]
You can update `tmlibs` yourself by executing `dep ensure -update github.com/tendermint/tmlibs`.

**Comment by tomc974** [comment]
@melekes Yeah, I know how to upgrade `tmlibs` locally, but I can't re-run the Circle CI tests to update the CI status of the merge request which failed because of missing methods in `tmlibs`.

**Comment by melekes** [comment]
1) dep ensure -update ...
2) commit newer Gopkg.lock
3) profit 👍

**Comment by tomc974** [comment]
Oh I see, thanks!

**Comment by melekes** [comment]
codecov 😞

**Comment by tomc974** [comment]
Anything I should do about the codecov issue?

**Comment by melekes** [comment]
🥇 🏎 🍰

**Pull request merged**
