### PR TITLE
improvement: move consensus package to internal

### PR DESCRIPTION
**Pull request by alexanderbez**
- Move consensus reactor to `internal` pkg.
- Remove `ConsensusState()` and `ConsensusReactor()` on the `Node` type.
- Expose public variants of metrics types on `Node` type.

### CODE REVIEW

**Comment by tychoish** [comment]
I think this would need to remove the following code from node.go 

```goi 
// ConsensusState returns the Node's ConsensusState.
func (n *Node) ConsensusState() *cs.State {
	return n.consensusState
}

// ConsensusReactor returns the Node's ConsensusReactor.
func (n *Node) ConsensusReactor() *cs.Reactor {
	return n.consensusReactor
}
```

and also remove `DefaultMetricsProvider`, `MetricsProvider` from the public interface of node.go.

**Comment by alexanderbez** [comment]
> and also remove DefaultMetricsProvider, MetricsProvider from the public interface of node.go.

We shouldn't remove these, but rather expose public variants.

**Review by marbar3778 — APPROVED** [review]
utACK

**Comment by tychoish** [comment]
I'd be inclined to avoid having many sub-packages within metrics and just have one "metrics" package?

I also don't know that we want to keep the metrics API separate/public? I don't think people would offer  their own implementations, really, and also I can imagine wanting to make a change to the metrics API without breaking semver.

**Comment by alexanderbez** [comment]
> I'd be inclined to avoid having many sub-packages within metrics and just have one "metrics" package?

This is because they're named all the same thing.

**Comment by tychoish** [comment]
> This is because they're named all the same thing and grouping by domain is typically a good thing (e.g. cmd).

It's easy enough to change the name, but I think the bigger questions are really "why do they need to be public?" and "is our metrics format part of our stable API?"

I think by making them public we're effectively leaking some details of our private implementation into the public API which doesn't quite feel worthwhile, but perhaps I'm missing something. 

The metrics provider can be made private pretty easily, and I think that's a far better change.

**Comment by alexanderbez** [comment]
I don't know if they need or need not be public, but I think it's a safer play to be honest. I do not think we should change the names -- the package name provides the context.

I'll move them back.

**Comment by tychoish** [comment]
I think we'll handle this via a different direction! I think it definitely brings up all of the right questions about how to restrict access to these components.

**Pull request closed without merging**
