### PR TITLE
Draw deps

### PR DESCRIPTION
**Pull request by ebuchman**
Replaces https://github.com/tendermint/tendermint/pull/435

### CODE REVIEW

**Comment by ebuchman** [comment]
Hmm I'm not getting the same result:

dependency-graph

**Comment by ebuchman** [comment]
@adrianbrink ^

**Comment by adrianbrink** [comment]
@ebuchman What do you mean by: "I'm not getting the same results."

**Comment by ebuchman** [comment]
My png looks different than the one you originally uploaded!

**Comment by adrianbrink** [comment]
Mh, the difference between the big graph and the small graph is whether you pass 2 or 1 to the -d option. Maybe there is also a difference between platforms.

**Comment by adrianbrink** [comment]
Should I change anything else before we can merge this?

**Comment by ebuchman** [comment]
Mmm I'm using `-d 2` on a mac. I'd like to be able to reproduce that same graph with all the actual deps before we merge

**Comment by adrianbrink** [comment]
I just ran it off the most current ```develop``` branch and ran ```glide install``` and now I am getting this image.

dependency-graph

**Comment by ebuchman** [comment]
yeh. so what gives ?

**Comment by adrianbrink** [comment]
I generated the [original image](https://github.com/tendermint/tendermint/pull/435/files#diff-0ff7d988a264a22196dcb21b415934ad) with ```-d 1```. 

Aren't we now getting the same results, which means that this should be mergeable :-)

Even though there is one small difference between the two pictures. You have an extra dependency ```github.com/spf13/cobra```. Are you also building on the most recent version of ```develop```?

**Comment by ebuchman** [comment]
dependency-graph

That's what I get with `-d 1` :(

**Comment by ebuchman** [comment]
`-d 3` ftw

**Pull request merged**
