### PR TITLE
crypto: remove SimpleHashFromMap() and SimpleProofsFromMap()

### LINKED ISSUE #2593: merkle/simpleMap: remove hash of the value parameter
Line in reference: https://github.com/tendermint/tendermint/blob/ee7b3d260e35c656290caace6255bee3a639a2bc/crypto/merkle/simple_map.go#L30

Despite the comment there, there is no advantage to this in our current usage. For everything were taking a simple map of, a hash is of the same size or larger than the value. So this will just increase net size. Worse, this adds another `proof` in the tree. 

I think we should prioritize fixing this prelaunch, as otherwise we need to special case our proof logic for these maps. (I.e. thats a bug that exists now, but would be resolved by changing this) Its an easy fix, and most of the work is in updating the test cases.

### PR DESCRIPTION
**Pull request by erikgrinaker**
Fixes #2593

@alexanderbez This is used in a single place in the SDK, how upset are you about removing it?

______

For contributor use:

- [x] ~Wrote tests~
- [x] Updated CHANGELOG_PENDING.md
- [x] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [x] Updated relevant documentation (`docs/`) and code comments
- [x] Re-reviewed `Files changed` in the Github PR explorer
- [x] Applied Appropriate Labels

### CODE REVIEW

**Comment by marbar3778** [comment]
should we put a deprecation warning in the godoc for one minor release and then remove it? in that time we can move it to the sdk. I'm not sure if anyone who doesnt uses the sdk uses this.

**Comment by erikgrinaker** [comment]
>should we put a deprecation warning in the godoc for one minor release and then remove it? in that time we can move it to the sdk

Sure, but do you think it'll make any difference? I'd imagine the people who rely on this wouldn't notice the deprecation warning anyway. I'm fine with either option anyway.

**Comment by marbar3778** [comment]
I'll open a PR in the sdk with these changes and then we can merge.

**Comment by marbar3778** [comment]
if no one has any objections we can move forward with the merge here

SDK PR: https://github.com/cosmos/cosmos-sdk/pull/6069

cc @melekes

**Pull request merged**
