### PR TITLE
fix issue3460

### PR DESCRIPTION
**Pull request by Zerppen**
When replaying blocks we should check apphash,however current logic will result in replaying too many wrong blocks if current block's apphash is wrong.
To solve this problem,check each block's appash is import and necessary .
* [ ] Updated all relevant documentation in docs
* [ ] Updated all code comments where relevant
* [ ] Wrote tests
* [ ] Updated CHANGELOG_PENDING.md

### CODE REVIEW

**Comment by Zerppen** [comment]
@melekes hi melekes,I'm sorry for disturbing you .
Can you give me you email  for more contribution.

**Comment by Zerppen** [comment]
@melekes  Hi,I don't know this result of "ci/circleci: test_cover".Can you do me a faver.

**Comment by Liamsi** [comment]
Looks like the pull request is created from a very old version of the software. I'm not sure why there aren't more changes showing up on github but:
image

I checked out the PR locally and I can confirm that there are many errors like:
```
../proxy/app_conn.go:4:2: cannot find package "github.com/tendermint/abci/client" in any of:
	/Users/ismail/go/src/github.com/tendermint/tendermint/vendor/github.com/tendermint/abci/client (vendor tree)
	/usr/local/Cellar/go/1.12.1/libexec/src/github.com/tendermint/abci/client (from $GOROOT)
	/Users/ismail/go/src/github.com/tendermint/abci/client (from $GOPATH)
```

**Comment by Zerppen** [comment]
@Liamsi  yeah,this version I cloned one year ago.I will open another PR.

**Pull request closed without merging**
