### PR TITLE
fuzz: initial support for fuzzing

### PR DESCRIPTION
**Pull request by cuonglm**
Updates #6557

### CODE REVIEW

**Comment by cuonglm** [comment]
cc @odeke-em

**Review by odeke-em — APPROVED** [review]
LGTM, thank you @cuonglm! Howdy Tendermint team, please help us with a merge for this as it is blocking us moving forward with adding Tendermint to oss-fuzz. Thank you

**Comment by cmwaters** [comment]
Hey @odeke-em and @cuonglm, we already have a fuzz directory in `test/fuzz` so I would prefer consolidating this all into the same single directory. In addition, I'm a bit hesitant with merging a `README` file that isn't complete / self explanatory.

**Comment by cuonglm** [comment]
> Hey @odeke-em and @cuonglm, we already have a fuzz directory in `test/fuzz` so I would prefer consolidating this all into the same single directory. In addition, I'm a bit hesitant with merging a `README` file that isn't complete / self explanatory.

Done, PTAL!

**Review by cmwaters — APPROVED** [review]
👍  thanks

**Comment by cmwaters** [comment]
If you can rebase this PR @cuonglm I will merge it

**Comment by cuonglm** [comment]
> If you can rebase this PR @cuonglm I will merge it

Thanks, done.

**Pull request merged**
