### PR TITLE
p2p: delete unused and untested *IPRangeCount functions

### LINKED ISSUE #602: p2p: delete functions AddToIPRangeCounts and CheckIPRangeCount
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Not either

I was reading through the source code to try to figure out my way through and saw functions
AddToIPRangeCounts and CheckIPRangeCount with TODOs to write tests.
However, those functions aren't used anywhere with the entire tendermint ecosystem
Doing a search for them

### CheckIPRangeCount
https://github.com/search?q=CheckIPRangeCount&type=Code&utf8=%E2%9C%93
yields zero results and 1 issue asking what they are for https://github.com/tendermint/go-p2p/issues/24
screen shot 2017-08-03 at 12 16 12 am

### AddToIPRangeCounts
https://github.com/search?q=AddToIPRangeCounts&type=Code&utf8=%E2%9C%93
yields 8 results of which all are just copy-paste of the functions
screen shot 2017-08-03 at 12 18 26 am

On top of that they are uncommented and the name AddToIPRangeCounts is a little misleading
because IPRangeCounts seems like it deals with IPv4 addresses and ranges yet in the implementation is splits IPv6 addresses by the colon(since IPv6 octets are separated by ":" while IPv4 are separated by "."), and also the implementation shows that it just counts prefixes, as shown below
screen shot 2017-08-03 at 12 22 35 am

   
If we are to keep them, perhaps let's name them `AddToIPv6OctetPrefixes and` `AllIPv6OctetPrefixesMatch`?

/cc @ebuchman @jaekwon @ethanfrey

### PR DESCRIPTION
**Pull request by odeke-em**
Fixes #602

Delete unused and untested functions:
- AddToIPRangeCounts
- CheckIPRangeCounts

### CODE REVIEW

**Comment by melekes** [comment]
I am against the dead code also.

**Comment by odeke-em** [comment]
Thank you for the review @melekes, I'll merge it in.

**Comment by melekes** [comment]
I'd prefer @ebuchman to merge all the PRs, but I guess in this case it is fine.

**Comment by odeke-em** [comment]
Aye aye, gotcha @melekes, I'll keep that in mind next time. Thanks for the tip :)

**Pull request merged**
