### PR TITLE
[blockchain] respond with nil on block request to indicate no block (…

### PR DESCRIPTION
**Pull request by melekes**
…Refs #514)

### CODE REVIEW

**Comment by ebuchman** [comment]
I'm not sure about this, since I think the reactor is designed so this doesn't happen. If it does happen, it might be a sign of a malicious peer. @jaekwon  ?

**Comment by jaekwon** [comment]
This can help with debugging.  But lets also add information about the block, so bcBlockResponseMessage includes a height, and nil means we don't have it yet.  Or, we can maybe create a new message, like bcNoBlockMessage

**Comment by jaekwon** [comment]
Lets also add a comment to note that according to Tendermint spec, if all nodes are honest, it shouldn't happen.

**Comment by zramsay** [comment]
what's this blocking on? Looks like only addressing jae's last comment (of adding a comment). @melekes can you add the comment?

**Comment by ebuchman** [comment]
lets add the `bcNoBlockMessage` so it's not a breaking change.

@odeke-em want to take a stab at this ?

**Comment by odeke-em** [comment]
@ebuchman for sure, I can take a stab at it, thanks for the tag.

**Comment by ebuchman** [comment]
Closing in favour of #648

**Pull request closed without merging**
