### PR TITLE
rewrite node test to use new pubsub

### PR DESCRIPTION
**Pull request by melekes**

### CODE REVIEW

**Comment by melekes** [comment]
```

Broadcast Tx aadeadbeefbeefbeef01
{
  "jsonrpc": "2.0",
  "id": "",
  "result": {
    "check_tx": {
      "code": 0,
      "data": "",
      "log": ""
    },
    "deliver_tx": {
      "code": 0,
      "data": "",
      "log": ""
    },
    "hash": "47933448C5011049104D881A9E89B7B6CA7CD6B9",
    "height": 7
  }
}
App hash for node 4 doesn't match. Got "0868DF55293831D787E3556CE146265F07ED64EF", expected "4609DEC49F67D0B6CBFC018987F6614424D2C536"
```

**Comment by melekes** [comment]
Observing some nondeterministic failures.

**Comment by melekes** [comment]
```
{
  "jsonrpc": "2.0",
  "id": "",
  "result": {
    "node_info": {
      "pub_key": "49A163893D936BBED04A3DB122CEDE54E3D73F88883AD558DD4BF21629C96B41",
      "moniker": "anonymous",
      "network": "chain-9ujDWI",
      "remote_addr": "",
      "listen_addr": "172.57.0.103:46656",
      "version": "0.12.0",
      "other": [
        "wire_version=0.7.1",
        "p2p_version=0.5.0",
        "consensus_version=v1/0.2.2",
        "rpc_version=0.7.0/3",
        "tx_index=on",
        "rpc_addr=tcp://0.0.0.0:46657"
      ]
    },
    "pub_key": {
      "type": "ed25519",
      "data": "AE67AC697D135AA0B4601EA57EAAB3FEBF4BAA4F229C45A598C2985B12FCD1A1"
    },
    "latest_block_hash": "0EB9CC9342E7649564FE525811FA622E9288C116",
    "latest_app_hash": "4609DEC49F67D0B6CBFC018987F6614424D2C536",
    "latest_block_height": 8,
    "latest_block_time": 1510184386130000000,
    "syncing": false
  }
}{
  "jsonrpc": "2.0",
  "id": "",
  "result": {
    "node_info": {
      "pub_key": "8C7929129E03AD9716C3EB6BD451F6A69352B3DAFAB6A630603543D19E36FF5B",
      "moniker": "anonymous",
      "network": "chain-9ujDWI",
      "remote_addr": "",
      "listen_addr": "172.57.0.104:46656",
      "version": "0.12.0",
      "other": [
        "wire_version=0.7.1",
        "p2p_version=0.5.0",
        "consensus_version=v1/0.2.2",
        "rpc_version=0.7.0/3",
        "tx_index=on",
        "rpc_addr=tcp://0.0.0.0:46657"
      ]
    },
    "pub_key": {
      "type": "ed25519",
      "data": "9EBC8F58CED4B46DCD5AB8ABA591DD253CD7CB5037273FDA32BC0B6461C4EFD9"
    },
    "latest_block_hash": "1DA852943750088789D92F86B5562C6FDA1B6414",
    "latest_app_hash": "0868DF55293831D787E3556CE146265F07ED64EF",
    "latest_block_height": 6,
    "latest_block_time": 1510184379857000000,
    "syncing": false
  }
```

4th node lags behind

**Comment by melekes** [comment]
```
2017-11-08T23:39:36+00:00 172.17.0.1 local_testnet_3[887]: E[11-08|23:39:36.435] Stopping peer for error                      module=p2p peer="Peer{MConn{172.57.0.104:46656} 8C7929129E03 out}" err="Error: runtime error: invalid memory address or nil pointer dereference\nStack: goroutine 1270 [running]:\nruntime/debug.Stack(0xc4223cd968, 0xb16ae0, 0x114ff50)\n\t/usr/local/go/src/runtime/debug/stack.go:24 +0xa7\ngithub.com/tendermint/tendermint/p2p.(*MConnection)._recover(0xc4220f41e0)\n\t/go/src/github.com/tendermint/tendermint/p2p/connection.go:206 +0x6e\npanic(0xb16ae0, 0x114ff50)\n\t/usr/local/go/src/runtime/panic.go:491 +0x283\ngithub.com/tendermint/tendermint/vendor/github.com/tendermint/tmlibs/common.(*BitArray).Update(0xc4228d4ba0, 0x0)\n\t/go/src/github.com/tendermint/tendermint/vendor/github.com/tendermint/tmlibs/common/bit_array.go:316 +0x70\ngithub.com/tendermint/tendermint/consensus.(*PeerState).ApplyVoteSetBitsMessage(0xc421e40340, 0xc422ae03c0, 0x0)\n\t/go/src/github.com/tendermint/tendermint/consensus/reactor.go:1164 +0x112\ngithub.com/tendermint/tendermint/consensus.(*ConsensusReactor).Receive(0xc42012b080, 0xc42156c723, 0x1115ba0, 0xc42018c6c0, 0xc422336000, 0x35, 0x400)\n\t/go/src/github.com/tendermint/tendermint/consensus/reactor.go:297 +0x1c99\ngithub.com/tendermint/tendermint/p2p.createMConnection.func1(0x1183e23, 0xc422336000, 0x35, 0x400)\n\t/go/src/github.com/tendermint/tendermint/p2p/peer.go:337 +0xbd\ngithub.com/tendermint/tendermint/p2p.(*MConnection).recvRoutine(0xc4220f41e0)\n\t/go/src/github.com/tendermint/tendermint/p2p/connection.go:478 +0x4a3\ncreated by github.com/tendermint/tendermint/p2p.(*MConnection).OnStart\n\t/go/src/github.com/tendermint/tendermint/p2p/connection.go:170 +0x187\n"
```

**Comment by ebuchman** [comment]
Merging this to fix develop.

**Pull request merged**
