### PR TITLE
feat: bring back filterlogging

### PR DESCRIPTION
**Pull request by marbar3778**
this pr brings back filter logging removed previously. There is a few outstanding things to do.

### CODE REVIEW

**Review by tychoish — COMMENTED** [review]
could you please outline the things left to do that you had in mind, and let me know when this is ready to review/continue. I have some time to work on this this week.

**Comment by marbar3778** [comment]
In testing, the filtering wasn't being caught, all logs were being spewed. Some debugging to find why is the rest that's needed.

**Comment by tychoish** [comment]
> In testing, the filtering wasn't being caught, all logs were being spewed. Some debugging to find why, is the rest that's needed.

Is your sense that the filtering mechanism doesn't work or it's not wired up?

**Comment by marbar3778** [comment]
> Is your sense that the filtering mechanism doesn't work or it's not wired up?

I had two assumptions I haven't looked into. First our wrapper of zerolog needs to be rewritten a big or I missed the place its suppose to be wired

**Comment by tychoish** [comment]
I think we should close this: 
- if we want to implement filtering I think it'd be better to implement as a set of hooks using zerolog's hook functionality, which would be more correct and behave more predictably. 
- the core functionality already exists in the legacy branches, as is, and there are no plans to release from the branches that use zerolog, it makes sense to keep things as they are.

**Pull request closed without merging**
