### PR TITLE
light: fix net_info call on light rpc

### PR DESCRIPTION
**Pull request by cmwaters**
Whilst poking around the light client, I realised that the `/net_info` endpoint ends up panicking the light client rpc server. Did a sneaky git blame and it looks like this bugs been around for 2 years.

I've tested this locally to make sure that the endpoint is working now

### CODE REVIEW

**Review by marbar3778 — APPROVED** [review]
Nice find!

**Comment by cmwaters** [comment]
@marbar3778 (I hope this works in my editor) - do you think we should move `running-in-production` to `node`

**Comment by marbar3778** [comment]
> @marbar3778 (I hope this works in my editor) - do you think we should move `running-in-production` to `node`

Yea that works. There is weird overlap between those two sections.

**Comment by cmwaters** [comment]
Lol how did it get on this PR (It was meant for the other one)

**Pull request merged**
