### PR TITLE
Update changelog for v0.35.0-rc2.

### PR DESCRIPTION
**Pull request by creachadair**
Move items from the pending changelog.

The diff is larger than expected because I think we forgot to re-run the linkifier before the last RC tag.

### CODE REVIEW

**Comment by cmwaters** [comment]
I think in the past the changelog was split across the rc versions i.e. v0.35-rc1 and v0.35-rc2 so that users can recognise the diff between the two. Then when we release the final candidate we collapse the changelogs across the multiple rc's into one.

**Comment by creachadair** [comment]
> I think in the past the changelog was split across the rc versions i.e. v0.35-rc1 and v0.35-rc2 so that users can recognise the diff between the two. Then when we release the final candidate we collapse the changelogs across the multiple rc's into one.

So, I went to look for examples of this to emulate, but I can't see where we have marked release candidates before. Do you have an example, or shall I just follow the existing pattern with RC labels?

**Comment by cmwaters** [comment]
I think if you checkout v0.34-rc2 you might be able to see how the Changelog was formatted there

**Comment by creachadair** [comment]
Ok! @cmwaters based on your recommendation I re-labelled the existing v0.35 section as rc1, and added the new items to a new rc2 section at the top. We can rewrite these if we want to once we do make the branch cut.

**Comment by cmwaters** [comment]
> I'm glad to do it, but it does mean we'd have the RC history in the master changelog even after the branch cut

I think that's fine with me (remember I'm not so particular about my git history). I also am hesitant with the flurry of small PR's landing to cut a branch yet because of having to follow up with backports for each.

**Review by cmwaters — APPROVED** [review]
LGTM. Thanks for preparing this

**Review by tychoish — APPROVED** [review]

**Pull request merged**
