### PR TITLE
Add Code of Conduct

### PR DESCRIPTION
**Pull request by adrianbrink**

### CODE REVIEW

**Comment by melekes** [comment]
Are we gonna put it in every repo?

**Comment by adrianbrink** [comment]
I don't know, but I think it can't hurt. I've put it in ethermint and rust-abci.

**Comment by ebuchman** [comment]
I think we should have a central source of truth for these things. Maybe put them all in the coding repo and the md in all the other repos can just point there, and contain any exceptions for that particular repo

**Comment by adrianbrink** [comment]
The code of conduct is very fundamental and shouldn't have any exceptions. I think from a central point would be good as well, but it seemed easier to just add it to the repos. :-)

**Pull request merged**
