### PR TITLE
lite2: Prevent falsely returned double voting error

### PR DESCRIPTION
**Pull request by cmwaters**
Closes: #4618

______

For contributor use:

- [ ] Wrote tests
- [ ] Updated CHANGELOG_PENDING.md
- [x] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [ ] Updated relevant documentation (`docs/`) and code comments
- [ ] Re-reviewed `Files changed` in the Github PR explorer

### CODE REVIEW

**Comment by cmwaters** [comment]
Q: How come we check for double voting for `VerifyCommitTrusting()` but not for `VerifyCommit()` ?

**Comment by melekes** [comment]
we need to write a test here

**Comment by melekes** [comment]
> Q: How come we check for double voting for VerifyCommitTrusting() but not for VerifyCommit() ?

because in VerifyCommit we know all validators (1 - 1), if vote from earlier validator is used - signature verification will fail.

in VerifyCommitTrusting, we don't know all validators

**Comment by cmwaters** [comment]
I created tests but I'm still not convinced about needing to check for double votes.

> in VerifyCommitTrusting, we don't know all validators

It's not about the validators though, we are checking to see if a commit has two votes and if we're assuming the commit is not faulty then this double vote can only occur when the validator set has two of the exact validators which shouldn't occur if someone is using a validator set properly.

**Comment by melekes** [comment]
> assuming the commit is not faulty

what makes you think you can make that assumption? malicious attackers can construct any data

**Pull request merged**
