### PR TITLE
Fix mistake in Mempool Reap documentation

### PR DESCRIPTION
**Pull request by silasdavis**
Minor, but caught me out.

### CODE REVIEW

**Comment by silasdavis** [comment]
Looks like it got you too at one point: https://github.com/tendermint/tendermint/commit/7bf34d1fae5c1c8b7364f34e2a53dc0d7660d4dc :)

**Comment by jaekwon** [comment]
Thanks Silas, 
Yeah it's kinda weird, why would we want to get 0 txs? :/

**Comment by jaekwon** [comment]
Ethan says the reason why we want 0 mean "get nothing" is for testing.  You can set a config to cap the max number of txs at 0, creating empty blocks.

**Comment by silasdavis** [comment]
@jaekwon ah I didn't realise about that config value, indeed it is useful for testing ListUnconfirmedTxs

**Pull request merged**
