### PR TITLE
crypto: add in secp256k1 support

### PR DESCRIPTION
**Pull request by marbar3778**
# Description

secp was removed in the protobuf migration, this pr adds it back in order to provide this functionality for users (band)

Closes: #5495 

Screen Shot 2020-10-14 at 2 15 53 PM

Genesis:
```json
{
  "genesis_time": "2020-10-14T12:08:40.876184Z",
  "chain_id": "test-chain-rk6Ytz",
  "initial_height": "0",
  "consensus_params": {
    "block": {
      "max_bytes": "22020096",
      "max_gas": "-1",
      "time_iota_ms": "1000"
    },
    "evidence": {
      "max_age_num_blocks": "100000",
      "max_age_duration": "172800000000000",
      "max_bytes": "1048576"
    },
    "validator": {
      "pub_key_types": [
        "secp256K1"
      ]
    },
    "version": {}
  },
  "validators": [
    {
      "address": "D6CC883D2C187CAE16B1E112360D21618BB7AC15",
      "pub_key": {
        "type": "tendermint/PubKeySecp256k1",
        "value": "Apm/YzkRdOECsw/W3RecNdIAUz0QaAV5n34GRLZ0caQT"
      },
      "power": "10",
      "name": ""
    }
  ],
  "app_hash": ""
}
```

### CODE REVIEW

**Review by melekes — APPROVED** [review]

**Comment by erikgrinaker** [comment]
We should also add support for different key algorithms to the E2E tests, and use secp for a couple of nodes in the CI testnet. This can go in a separate PR, if you prefer.

**Comment by marbar3778** [comment]
> We should also add support for different key algorithms to the E2E tests, and use secp for a couple of nodes in the CI testnet. This can go in a separate PR, if you prefer.

I can look at adding it. It would only be a `.toml` file, correct?

**Comment by erikgrinaker** [comment]
No, you'll have to:

- Add an option `key_algorithm` to the manifest `pkg/manifest.go` (default to `ed25519`) and validate it.
- Generate node key based on the key algorithm setting when building the testnet (in `pkg/testnet.go`).
- Change the CI testnet `networks/ci.toml` to use `key_algorithm: secp256k1` for a couple of validators.
- Change the random testnet generator in `generator/` to randomly pick a key algorithm when generating testnets.

**Comment by marbar3778** [comment]
> No, you'll have to:
> 
>     * Add an option `key_algorithm` to the manifest `pkg/manifest.go` (default to `ed25519`) and validate it.
> 
>     * Generate node key based on the key algorithm setting when building the testnet (in `pkg/testnet.go`).
> 
>     * Change the CI testnet `networks/ci.toml` to use `key_algorithm: secp256k1` for a couple of validators.

If what you mean that some nodes run secp and other ed25519(?), this is not possible. All validators must have the same key. It would need to be a second job `e2e-ed25519` & `e2e-secp256k1`

>     * Change the random testnet generator in `generator/` to randomly pick a key algorithm when generating testnets.

Privval is Hardcoded to ed25519 currently. We would need to generate secp256k1 keys out of band and place them in the `privval_node_key.json file` or we make it configurable on `tendermint init --key_algo secp256k1`

**Comment by erikgrinaker** [comment]
> Privval is Hardcoded to ed25519 currently. We would need to generate secp256k1 keys out of band and place them in the privval_node_key.json file or we make it configurable on tendermint init --key_algo secp256k1

Eh ok. In that case we can probably put this off until we fully support it, unless it's trivial to implement.

**Comment by marbar3778** [comment]
This pr also removes secp with cgo, this was not used by Tendermint but the Cosmos-sdk. Since they have their own version of secp with cgo we were able to remove it.

**Comment by marbar3778** [comment]
> Eh ok. In that case we can probably put this off until we fully support it, unless it's trivial to implement.

I do believe its trivial, I can look at adding it

**Comment by marbar3778** [comment]
@sorawit and @joe-bowman could you take a look at this PR. 

Within this PR we are using the secp key from `"github.com/btcsuite/btcd/btcec"` does this suite your needs?

**Pull request merged**
