### PR TITLE
[rpc] unsubscribe does not work

### LINKED ISSUE #1368: Unsubscribe with a query doesn't work
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

BUG REPORT

**Tendermint version** (use `tendermint version` or `git rev-parse --verify HEAD` if installed from source):

0.16.0-c8a2bdf7

**ABCI app** (name for built-in, URL for self-written if it's publicly available):

https://github.com/confio/weave (mycoind)

**Merkleeyes version** (use `git rev-parse --verify HEAD`, skip if you don't use it):

**Environment**:
- **OS** (e.g. from /etc/os-release): Ubuntu 16.04.4
- **Install tools**:
- **Others**:

**What happened**:

`/subscribe`: `{query: "tm.event = 'NewBlock'"}`

I get a nice stream of blocks.

`/unsubscribe`: `{query: "tm.event = 'NewBlock'"}`

Blocks keep coming :frowning_face: 

`/unsubscribe`: `{query: "tm.event = 'NewBlock'"}`

Error telling me I already unsubscribed:
```
{
  "code": -32603,
  "message": "Internal error",
  "data": "subscription not found"
}
```

`/unsubscribe_all`:

Streaming blocks stop :smile: 

**What you expected to happen**:

I expect `/unsubscribe` to unsubscribe, given the identical query to `/subscribe`.
This is described behavior in godoc.

**How to reproduce it** (as minimally and precisely as possible):

See above

**Anything else do we need to know**:

Please don't reject these issues just cuz they come from me.

### PR DESCRIPTION
**Pull request by melekes**
https://github.com/tendermint/tmlibs/pull/181

Fixes #1368

### CODE REVIEW

**Comment by melekes** [comment]
@ethanfrey can you try this branch with your example?

**Comment by ethanfrey** [comment]
Okay, will do.

```
git checkout 1368-unsubscribe-does-not-work
make get_tools && make get_vendor_deps && make install
```

make get_vendor_deps seems rather slow (first time with dep I guess).
I'll let you know.

**Comment by ethanfrey** [comment]
0.17 is breaking header format from 0.16? I tried restarting the exisiting chain with the new tendemint and got:

```
I[03-27|16:03:10.845] ABCI Replay Blocks                           module=consensus appHeight=32270 storeHeight=32271 stateHeight=32270
I[03-27|16:03:10.845] Replay last block using real app             module=consensus 
ERROR: Failed to create node: Error starting proxy app connections: Error on replay: Wrong Block.Header.ConsensusHash.  Expected 56FFD86672A5EB6BFEBEB46F13AAD1B7B61F06C3, got 0B8CEF95EC57AC2D96038FD0AE3901C14FAE8E73
```

After wiping out db, seems like it started fine.

**Comment by ethanfrey** [comment]
Got the same results as before.
`/tx_search` works, and subscribing to all Tx works.
Subscribing to a tag doesn't ever get called.

**Comment by melekes** [comment]
I know, but what about unsubscribing to blocks?

**Comment by ethanfrey** [comment]
ahh... sorry, i thought this was the other issue.
will check now

**Comment by ethanfrey** [comment]
no luck with unsubscribe either...

```
> let query = "tm.event = 'NewBlock'"
> client.client.subscribe({query}, x => foo.push(x)).catch(pprint)
> foo.length
5
> foo.length
6
> client.client.unsubscribe({query}).catch(pprint)
{}
> foo.length
18
> foo.length
20
> foo.length
21
> client.client.unsubscribe({query}).catch(pprint)
{
  "code": -32603,
  "message": "Internal error",
  "data": "subscription not found"
}
```

**Comment by ethanfrey** [comment]
The last update (34c800c) works great from my manual integration tests:

```
> let foo = 0
> foo
0
> let q = {query: "tm.event='NewBlock'"}
> client.client.subscribe(q, x => foo++).catch(pprint)
> foo
2
> client.client.unsubscribe(q, pprint).catch(pprint)
{}
> foo
10
// I wait 15 seconds...
> foo
10
```

**Pull request merged**
