### PR TITLE
cli: add command to manually reindex tx and block events (backport: #6676)

### PR DESCRIPTION
**Pull request by marbar3778**
This is a backport of https://github.com/tendermint/tendermint/pull/6676 which adds a new cli to reindex missed blocks (if the node has the respective ABCIResponses)

This will help node operators who offer indexing service the ability to reindex missed events i.e. in the case their node goes down

### CODE REVIEW

**Comment by creachadair** [comment]
Note that if #8946 is implemented, it will make reindexing stop working for blocks prior to the latest. That's not necessarily a blocker to doing it, but it's worth considering the interaction.

**Comment by marbar3778** [comment]
ah good point, It seems like the abciresponses would move to a abci.db and be optional to not bloat state.db. For archive nodes they may opt to store those and provide snapshots to others to reindex data.

**Comment by cmwaters** [comment]
This will still be a configurable option. Users will be able to save ABCI responses if they want which will allow them to reindex missed blocks. I assume those running indexers probably care less about minimizing storage.

**Comment by cmwaters** [comment]
Have a test that's not passing because apparently an incorrect connection url is given to the postgres instance but no error is returned when one is expected

**Comment by cmwaters** [comment]
One minor difference here to the original backport is that v0.34 only supports a single indexer whereas v0.35+ supports multiple

**Review by tychoish — APPROVED** [review]

**Review by cmwaters — APPROVED** [review]
🙃

**Pull request merged**
